### ISSUE TITLE
[BUG] CI key problem

### ISSUE THREAD

**Issue by sjthales** [openhwgroup/cva6#1001]
### Is there an existing CVA6 bug for this?

- [X] I have searched the existing bug issues

### Bug Description

Hello @zarubaf @JeanRochCoulon @eyssartk @jquevremont  ,

I am currently having a problem with CI tests.
<img width="439" alt="ci_error" src="https://user-images.githubusercontent.com/57099003/204299400-d7b10ed8-702a-42d6-b418-83c157d2e046.png">

There seems to be a problem with the key https://download.opensuse.org/repositories/home:phiwag:edatools/xUbuntu_20.04/Release.key in the cva6/ci/setup.sh file
<img width="617" alt="key_error" src="https://user-images.githubusercontent.com/57099003/204299481-54ee38df-f0bf-4fe8-8681-e18a49d836af.png">

Have you observed this kind of problem on your side?

**Comment by XiaoAn109** [comment]
Did you mean the ci/setup.sh? Me too. And I change the curl -fsSL https:\..... to curl -fsSL http:\. Then it works

**Comment by zarubaf** [comment]
@XiaoAn109 thanks! @sjthales would you mind defaulting to the http protocol until we can figure out what happened exactly?

I’ve seen that the `edatools` dep registry grew stale. I will think about what to do with it, maybe a OpenHW registry would make sense?

**Comment by sjthales** [comment]
On Monday, that didn't work and yesterday, that worked (in the same environment)

**Comment by XiaoAn109** [comment]
Yep. Today it works.

**Comment by AnikBalo** [comment]
Probably curl is not installed in your ubuntu. Install curl: sudo apt install curl
Then try ./ci/setup.sh

**Comment by MikeOpenHWGroup** [comment]
Hi @sjthales, what is the status of this issue?
