### ISSUE TITLE
[BUG] CVA6 does not compile when COMMIT_PORT=1

### ISSUE THREAD

**Issue by JeanRochCoulon** [openhwgroup/cva6#1069]
### Is there an existing CVA6 bug for this?

- [X] I have searched the existing bug issues

### Bug Description

Solved by #1068

**Comment by MikeOpenHWGroup** [comment]
Hi @JeanRochCoulon.  Please ensure that all issues you create have:
1. An Assignee.  This is most important - no Issue should be unassigned.
2. `Component`, `Status` and `Type` labels.
