### ISSUE TITLE
PMP Granularity needs to be discussed in User Manual

### ISSUE THREAD

**Issue by MikeOpenHWGroup** [openhwgroup/cva6#1095]
The PMP granularity of CVA6 is fixed at 8.  This is fine, but as PMP granularity is visible to the user (e.g. software developers), this information needs to be available in the [PMP Chapter of the User Guide](https://docs.openhwgroup.org/projects/cva6-user-manual/01_cva6_user/PMP.html).  Currently it is only specified in the Design Specification of the [Execution Stage](https://docs.openhwgroup.org/projects/cva6-user-manual/03_cva6_design/ex_stage.html#pma-pmp-checks).

**Comment by Moschn** [comment]
A small comment: The PMP granularity _is_ visible to the user. The RISC-V priviledge spec states: 

> Software may determine the PMP granularity by writing zero to pmp0cfg, then writing all ones to pmpaddr0, then reading back pmpaddr0. If G is the index of the least-significant bit set, the PMP granularity is 2G+2 bytes.

**Comment by zarubaf** [comment]
All added in #1092
