### ISSUE TITLE
minstreth CSR is failing while verifying access modes

### ISSUE THREAD

**Issue by spidugu444** [openhwgroup/cva6#1116]
### Is there an existing CVA6 bug for this?

- [X] I have searched the existing bug issues

### Bug Description

As per riscv priviliged specification **minstreth CSR return bits 63–32 of machine instructions retired counter**.

While trying to verify access modes for minstreth CSR test is failing on verilator end as it is always reading Zero.
whereas on spike end test is reading expected values and test is passing.
For reference please find attached spike and verilator log files

[riscv_spike_minstreth_csr_test_0.log](https://github.com/openhwgroup/cva6/files/10976594/riscv_spike_minstreth_csr_test_0.log)
[riscv_verilator_minstreth_csr_test_0.log](https://github.com/openhwgroup/cva6/files/10976599/riscv_verilator_minstreth_csr_test_0.log)

**Comment by JeanRochCoulon** [comment]
Thanks @spidugu444 for having reported this issue. The concern is that so far no designer has been identified to fix the RTL. The main thing is the fact that the issue is tracked.

**Comment by spidugu444** [comment]
Hi @Moschn, with your fix test is working fine, Thanks for your fix.
I am closing this issue.

**Comment by JeanRochCoulon** [comment]
@spidugu444  do you have double checked that the PR fixes the bug before closing the Issue ?

**Comment by spidugu444** [comment]
HI @JeanRochCoulon, before closing the issue I confirmed it by running arch-test suite regression and minstreth CSR access mode test.
please find the attached minstreth CSV files for your reference.

[riscv_spike_minstreth_csr_test_0.csv](https://github.com/openhwgroup/cva6/files/10987385/riscv_spike_minstreth_csr_test_0.csv)
[riscv_verilator_minstreth_csr_test_0.csv](https://github.com/openhwgroup/cva6/files/10987386/riscv_verilator_minstreth_csr_test_0.csv)

**Comment by JeanRochCoulon** [comment]
Great !   Thanks Sai, have a nice day
