### ISSUE TITLE
[BUG] mstatush is not implemented in RV32

### ISSUE THREAD

**Issue by ASintzoff** [openhwgroup/cva6#1160]
### Is there an existing CVA6 bug for this?

- [X] I have searched the existing bug issues

### Bug Description

The `mstatush` CSR which contains the 32 most significant bits of `mstatus` CSR in RV32 is not implemented.

For more details, see The RISC-V Instruction Set Manual Volume II: Privileged Architecture, section 3.1.6 - Machine Status Registers (`mstatus` and `mstatush`).

**Comment by MikeOpenHWGroup** [comment]
Hi @ASintzoff, I took the liberty of adding `Component` and `Status` labels.  Also, the issue was not assigned and since I am unsure who will update the RTL, I assigned the issue to you.  :stuck_out_tongue_winking_eye:.  You will know better than me who the proper victim should be.

**Comment by AyoubJalali** [comment]
Hello, so as I can't modify the issue to add how to reproduce the bug i'll give it here : 
So I was working on adding tests on the CI for ISACOV agent, and i had a failing test so i reproduce the test, and found the bug mention above so to reproduce it here is the steps : 

1. Add the yaml description of the test in [cva6_base_testlist.yaml](https://github.com/openhwgroup/core-v-verif/blob/master/cva6/sim/cva6_base_testlist.yaml) (i'm working on a PR to merge this also)
**### - test: riscv_arithmetic_basic_illegal
  description: >
    Arithmetic instruction test, no load/store/branch instructions
  gen_opts: >
    +instr_cnt=500
    +num_of_sub_program=0
    +no_data_page=1
    +no_branch_jump=1
    +boot_mode=m
    +no_csr_instr=1
    +illegal_instr_ratio=100
    +tvec_alignment=8
  iterations: 2
  gen_test: cva6_instr_base_test_c
  rtl_test: core_base_test**
3. and run the commend : **python3 cva6.py --testlist=cva6_base_testlist.yaml --test riscv_arithmetic_basic_illegal --iss_yaml cva6.yaml --target cv32a60x --iss=vcs-uvm,spike -i 10 --simulator_yaml ../env/corev-dv/simulator.yaml --iss_timeout 300 --seed 1391044193** in core-v-verif/cva6/sim (branch cva6/dev & RTL matser)
