### ISSUE TITLE
[Enhancement] Micro TLB + Multilevel TLB

### ISSUE THREAD

**Issue by msfschaffner** [openhwgroup/cva6#117]
Splitting the TLB into a micro TLB with 4 entries and a larger (possibly multilevel) TLB can improve the timing on the cache tag comparison paths.

**Comment by MikeOpenHWGroup** [comment]
@zarubaf, was is the status of this enhancement? I recommend we either:
1. Set the `Status:Wont-fix` label and close it, or
2. Assign this issue to @JeanRochCoulon and ask for him to find an owner for this enhancement.

**Comment by MikeOpenHWGroup** [comment]
@zarubaf, was is the status of this enhancement? I recommend we either:
1. Set the `Status:Wont-fix` label and close it, or
2. Assign this issue to @JeanRochCoulon and ask for him to find an owner for this enhancement.

**Comment by jquevremont** [comment]
@sjthales is working on this topic.

**Comment by zarubaf** [comment]
This support has been merged for the 32-bit version. Not planned for 64-bit at the moment, afaik. If it is than we should add it as a new task.

**Comment by jquevremont** [comment]
> This support has been merged for the 32-bit version. Not planned for 64-bit at the moment, afaik. If it is then we should add it as a new task.

To anyone who reads this: If you intend to do this, come and synchronize with the CVA6 team.
The context is the following: we have several MMUs in the repo and we'd like to refactor them.
