### ISSUE TITLE
[Enhancement] Speculatively forward data from load unit

### ISSUE THREAD

**Issue by msfschaffner** [openhwgroup/cva6#120]
Forwarding data coming from the load unit could improve IPC, but needs additional control logic as it has to be done speculatively.

**Comment by MikeOpenHWGroup** [comment]
@zarubaf, was is the status of this enhancement?  I recommend we either:
1. Set the `Status:Wont-fix` label and close it, or
2. Assign this issue to @JeanRochCoulon and ask for him to find an owner for this enhancement.
