### ISSUE TITLE
[BUG] Missing required CSRs: mhpmevent9-31

### ISSUE THREAD

**Issue by flaviens** [openhwgroup/cva6#1212]
### Is there an existing CVA6 bug for this?

- [X] I have searched the existing bug issues

Hi there!

### Bug description

The privileged specification says, in section `3.1.10`:

> All counters should be implemented, but a legal implementation is to make both the counter and its corresponding event selector be read-only 0.

However, reading any of mhpmevent9 to mhpmevent31 raises an exception. 

### Example snippet

This snippet should store 0 to address 0x10 but stores 1 instead.

```
  .section ".text.init","ax",@progbits
  .globl _start
  .align 2
_start:

  la 	  ra, trap_handler
  csrrw	zero,mtvec,ra
  csrr	zero,mhpmevent9

  li a0, 0x10
  li t0, 0

  sd t0, (a0)
  sd zero, (zero)

infinite_loop0:
  j infinite_loop0

.section ".trap_handler","ax",@progbits
trap_handler:

  li a0, 0x10
  li t0, 1

  sd t0, (a0)
  sd zero, (zero)

infinite_loop1:
  j infinite_loop1
```

Thanks!

**Comment by MikeOpenHWGroup** [comment]
Thanks for the issue and associated code snippit @flaviens.  I must admit I am a bit confused:

>However, reading any of mhpmevent9 to mhpmevent31 raises an exception.
This snippet should store 1 to address 0x10 but stores 0 instead.

My read of your code is exactly inverted: an exception writes 1 to 0x10. If you are seeing 0 written to 0x10 then there was no exception (as expected).

**Comment by flaviens** [comment]
Hi @MikeOpenHWGroup , sorry I mixed up 1 and 0 in the post above. We expect 0 but we get 1.

**Comment by JeanRochCoulon** [comment]
@TulikaSi   can you give us more visibility on this bug ?   Is it prensent in current RTL ?

**Comment by TulikaSi** [comment]
Hi @flaviens @JeanRochCoulon 
mhpmevent CSRs are already present in CVA6. 
@flaviens Can you run the test again and let me know if the CSRs are still not accessible?

**Comment by TulikaSi** [comment]
Hi @flaviens 
We ran a testcase to read the **mhpmevent9 CSR** recently . I have attached the snips of the logfile and the testcase for your reference. As we can see from the log file that the current RTL behaves properly and does not raise an exception that clearly indicates the mhpmevent has been implemented as per the RISC-V specification. I did not use Cascade but I believe this small testcase can help us to close the issue.

![mhpmevent_log_1](https://github.com/openhwgroup/cva6/assets/98868403/208032f6-99fb-4a48-aa6a-e3b7607de7f8)

![mhpmevent_testcase](https://github.com/openhwgroup/cva6/assets/98868403/56923661-04b1-4ce7-9f19-e0f8b27a27c4)


@JeanRochCoulon

**Comment by TulikaSi** [comment]
Also,
This PR (https://github.com/openhwgroup/cva6/pull/1227)done on 10th May covers the mhpmevent9-31 and the issue was raised by you on 27th April so maybe you got this error at the time these CSRs were not implemented.

**Comment by flaviens** [comment]
Looks good thanks for the fix!
