### ISSUE TITLE
[Enhancement] Improve throghput of AXI adapter

### ISSUE THREAD

**Issue by msfschaffner** [openhwgroup/cva6#122]
The AXI adapter currently has one FSM that controlls the request and response channels. Hence, it cannot have multiple pending transactions. Decoupling request and response paths could improve data throughput.

**Comment by MikeOpenHWGroup** [comment]
This issue is more than four years old and I _think_ this enhancement has been added by now.

@zarubaf, can you add a comment and close the issue if possible?   Thanks.

**Comment by zarubaf** [comment]
A lot has changed since then (new caches, etc.). I think we can safely close this now.
