### ISSUE TITLE
version `CXXABI_1.3.9' not found (required by   ./../work-dpi/ariane_dpi.so)

### ISSUE THREAD

**Issue by AnikBalo** [openhwgroup/cva6#1244]
### Is there an existing CVA6 bug for this?

- [X] I have searched the existing bug issues

### Bug Description

While trying to perform simulation in synopsys VCS I am getting the following error: 
![vcs_issue](https://github.com/openhwgroup/cva6/assets/96606368/e5f36026-9b85-406a-bce6-20c229898913)

The command I have used: **make vcs elf-bin=<path-to-hello.elf-file>**

Can anyone suggest I can I fix this apart from upgrading gcc?
Thanks

**Comment by zarubaf** [comment]
It seems you've compiled `ariane_dpi.so` with a different compiler than `vcs` is using. Make sure that you don't have an`CC` override or so. I don't recall having to set anything specifically for VCS. In `QuestaSim` in older versions the compiler was so old, that you needed to supply your own and then this could become a problem.

You can see that `ariane_dpi.so` is compiled in the Makefile separately and it is crucial that you use the same compiler to compile the shared object as `vcs` is using to compile the final binary.

We are in the process of deprecating this toolflow (for obvious shortcomings) so this hopefully will be resolved in the future.
