### ISSUE TITLE
[BUG] dhrystone and hello baremetal execution failed on fpga by openocd

### ISSUE THREAD

**Issue by StilluSmile** [openhwgroup/cva6#1255]
### Is there an existing CVA6 bug for this?

- [X] I have searched the existing bug issues

### Bug Description

When I load the program hello.elf and dhrystone.riscv in the benchmark folder through gdb, I found that it cannot be executed normally, and it seems to stop at Continuing... without printing any output. I guess there may be a compilation problem or a wrong link script. I checked the disassembly text of dhrystone.riscv, which starts from 0x80000000. May be I missed something. How can the bare metal program be successfully executed through gdb loading?

The output information of gdb is as follows:

(gdb) load hello.elf
Loading section .text, size 0x2532 lma 0x100b0
Loading section .rodata, size 0x18 lma 0x125e8
Loading section .eh_frame, size 0x4 lma 0x13600
Loading section .init_array, size 0x10 lma 0x13608
Loading section .fini_array, size 0x8 lma 0x13618
Loading section .data, size 0xf58 lma 0x13620
Loading section .sdata, size 0x40 lma 0x14578
Start address 0x100c8, load size 13566
Transfer rate: 47 KB/sec, 1938 bytes/write.
(gdb) pwd
Working directory /home/cva6/tmp/riscv-tests/build.
(gdb) load ./benchmarks/dhrystone.riscv
Loading section .text.init, size 0x1c6 lma 0x80000000
Loading section .tohost, size 0x48 lma 0x80001000
Loading section .text, size 0x96c lma 0x80002000
Loading section .text.startup, size 0x6fe lma 0x8000296c
Loading section .rodata.str1.8, size 0x668 lma 0x80003070
Loading section .rodata, size 0x158 lma 0x800036d8
Start address 0x80000000, load size 6712
Transfer rate: 31 KB/sec, 1118 bytes/write.
(gdb) c
Continuing.

Thank you very much for any replies and suggestions~

**Comment by zarubaf** [comment]
Difficult to debug without `dhrystone` sources, etc. Closing it for now, if you still encountering the problem, feel free to re-open.
