### ISSUE TITLE
Issue with SIE CSR Access modes

### ISSUE THREAD

**Issue by spidugu444** [openhwgroup/cva6#1260]
### Is there an existing CVA6 bug for this?

- [X] I have searched the existing bug issues

### Bug Description

HI,

While verifying Access mode for SIE(Supervisor Interrupt enable) CSR on CVA6 core, test got failed due to CSR is always reading Zero on both spike  and verilator.
As per CVA6 user manual please find the access modes for SIE CSR is as mentioned below, 

![SIE_CSR](https://github.com/openhwgroup/cva6/assets/103561542/bbcab029-a63c-4e18-bcac-007065fbef9b)

**Comment by MikeOpenHWGroup** [comment]
Hi @spidugu444, in the test-program that tests the access mode behavior of the SIE CSR, do you set values of the `MIDELEG` CSR?  I believe if you want to write non-zero to MIE or SIE, you need to set the appropriate bits in MIDELEG.

**Comment by spidugu444** [comment]
@MikeOpenHWGroup, by configuring MIDELEG CSRs supervisor Interrupt bits, now I am able to verify access modes for SIE CSR.

**Comment by spidugu444** [comment]
As I am able to access SIE CSR, I am closing this issue.
