### ISSUE TITLE
[TASK] Tag and banner to inform users of ongoing parameterization

### ISSUE THREAD

**Issue by jquevremont** [openhwgroup/cva6#1269]
### Is there an existing CVA6 task for this?

- [X] I have searched the existing task issues

### Task Description

As the parameterization changes is on-ongoing in a progressive fashion, we need to inform CVA6 users to limit the inconvenience for them:
- Add a banner at the beginning of README.md
- Add a tag

### Description of Done

Banner available
Tag added

**Comment by JeanRochCoulon** [comment]
Done. Look at https://github.com/openhwgroup/cva6.

**Comment by jquevremont** [comment]
Closing. We'll open a new task as needed to remove the banner.
