### ISSUE TITLE
[BUG] Hardware Performance Monitoring tool - missing `mhpmeventX` and `hpmcounterX` CSRs

### ISSUE THREAD

**Issue by filippofontana** [openhwgroup/cva6#1282]
### Is there an existing CVA6 bug for this?

- [X] I have searched the existing bug issues

### Bug Description

Hi,
I'm using an emulated version of CVA6 (64 bit executed on the VCU118 FPGA) which is aligned with the version 1.10 of the RISC-V privileged specifications and supports the H-extension. I'm facing an issue while interacting with openSBI (v1.1 which is required by the Hypervisor I'm using). I think it could be somehow related to https://github.com/openhwgroup/cva6/issues/1213 (not sure), but I need to extend it a bit more. 
>Actually, I'm a software guy so bear with me if this is something you have already faced and solved (in that case, if you can give the right pointers it would be great). 

**Briefly**, I need to profile the CVA6 core from S-mode and I noticed that in my current version of the core, the `mhpmeventX` and `hpmcounterX` CSRs are not available , which makes profiling a bit trickier from S-mode, but I've implemented a custom vendor extension in openSBI to read the M-mode register and return them in S-mode. 
In any case, the way machine HPM counters are implemented in this version of CVA6, can block openSBI boot by executing illegal instructions while trying to interact (read/write) with `mhpmeventX` CSRs.

In the end, it would be great if the CSRs I'm mentioning could be implemented (if they are not already here) since they would reduce the overhead of calling an `ecall` each time I need to access the perf counters (this will also make the SBI's PMU extension available for CVA6), but here I will post the details of the problem I'm facing since it could be an issue also for others that are trying to integrate a recent version of openSBI with CVA6.

### Detailed explanation of the problem
The CVA6 version (priv-1.10) I'm using on the VCU118 has a peculiar feature which does not "follow" the actual standard of the RISC-V privileged specifications: usually when you want to monitor an hardware event, you should "enable" it through the `mhpmeventX` CSR which then cause the `mhpmcounterX` CSR to increment when the specific event happens.

In our case, we have `mhpmcounter3` and `mhpmcounter4` enabled by default (bypassing `mhpmevent3` and `mhpmevent4` (which are not implemented for the core emulated by the VCU118)) to count instruction and data L1 cache misses , which is convenient for fast testing, but doesn’t respect the logic of external firmware that should detect specific features (e.g. openSBI).

By using openSBI as the bootloader for the Hypervisor I need to run on CVA6, I encountered an issue that sometimes causes the hart to hang. 
There is a function which tests if the hardware performance counters are working correctly (by setting a value and then by checking if it didn’t change). Obviously 9 times out of 10 it “works” by detecting no performance counters (since they are already enabled, the two values read from the registers are different and the test fails), but it could happen (and sometimes it does) that the performance counters are detected correctly, but then there is an attempt to interact (read/write) with the related `mphmeventX` registers which are not available and a write to their addresses cause an illegal instruction (the hart will then hang).

### How to replicate the issue

- openSBI v1.1
- source file: opensbi/lib/sbi/sbi_hart.c

The issue is actually really "hard" to replicate, the problem basically happens after this functions stack:

[![](https://mermaid.ink/img/pako:eNpNkE0PgjAMhv_K0hMkcPDjxMFE4agXvS4hkxVZdMOMEmMI_90y_Oqp6fv07ccAVasRMqhv7aNqlCexP0onOLaRhIVIRXc25SSUxhmKYgmxSNON2LG8ZDlIGgkrKmtU1HvsAvV2CXDO8Orfy-PXbebywBXMrZmzHbFT9xsJCVj0VhnNuw5TiwRq0KKEjFOt_FWCdCNzqqf29HQVZOR7TKC_a0VYGHXxyn6KqA21_jDfHl4wvgDQuFJd?type=png)](https://mermaid.live/edit#pako:eNpNkE0PgjAMhv_K0hMkcPDjxMFE4agXvS4hkxVZdMOMEmMI_90y_Oqp6fv07ccAVasRMqhv7aNqlCexP0onOLaRhIVIRXc25SSUxhmKYgmxSNON2LG8ZDlIGgkrKmtU1HvsAvV2CXDO8Orfy-PXbebywBXMrZmzHbFT9xsJCVj0VhnNuw5TiwRq0KKEjFOt_FWCdCNzqqf29HQVZOR7TKC_a0VYGHXxyn6KqA21_jDfHl4wvgDQuFJd)

1. `sbi_hart_init()` → parent function
2. `hart_detect_features()` → determines if the hardware supports performance counters or not (this is the function that behaves bad by validating sometimes the performance counters)
3. `sbi_hart_reinit()` → caller of mstatus_init() which then will cause the illegal instruction
4. `mstatus_init()` → since the performance counters are found, it writes to the related `mhpmeventX` CSRs which cause the crash

By single stepping with GDB the instructions that are in `hart_detect_features()` I can avoid the problem (i.e. the two compared values are different since the counters are already enabled), but if I execute the code straightforwardly, the boot process is blocked by the illegal instruction which happens in step 4.

Hope this is clear enough, I'm available for additional information.

**Comment by JeanRochCoulon** [comment]
Hello @TulikaSi 
As designer of performance counter, you should able to answer to @filippofontana
Regards

**Comment by TulikaSi** [comment]
Hi @filippofontana 
The current version of CVA6 has six generic 64-bit performance counters located in **mhpmcounter3 to mhpmcounter8** **(including their upper 32 bits counterparts in CV32A6: mhpmcounter3h to mhpmcounter8h**). 
Also, the event selectors **mhpmevent3 - mhpmevent8**, **read only shadows of the mhpmcounterX** have been also implemented. 
The other performance counters that are not implemented should be able to give read only 0 value if called.

Are you using the current CVA6 version??

**Comment by filippofontana** [comment]
Hi @TulikaSi, 

I've talked with the hardware guys and they will cherry-pick the relevant commit and port them to our frozen version. 

Thanks for the answer!

P.S. I'm closing the issue since this is not an issue as of now.
