### ISSUE TITLE
[TASK] Replace AxiCompliant with interface-specific enum

### ISSUE THREAD

**Issue by Jbalkind** [openhwgroup/cva6#1319]
### Is there an existing CVA6 task for this?

- [X] I have searched the existing task issues

### Task Description

The ArianeCfg.AxiCompliant parameter was introduced to differentiate between the use of AXI and P-Mesh TRI for the output from the L1 caches. I'd like to continue using this as I remove PITON_ARIANE ifdefs but I'm aware that we now made the "noc" interface generic and the TCC project will use ACE rather than AXI or TRI. I'd like if we defined an enum instead, like we do for WT vs WB L1 cache to specify the different interfaces.

### Description of Done

ArianeCfg.AxiCompliant replaced with a new parameter (say, Cva6Cfg.NoCProtocol) that relies on a new enum which to begin with has AXI and TRI as variants.

/cc @suppamax

**Comment by Jbalkind** [comment]
@zarubaf can you self-assign? I don't have the privileges to assign this

**Comment by zarubaf** [comment]
Got it, thanks!

**Comment by Jbalkind** [comment]
For reference, my slightly outdated commit for removing PITON_ARIANE is here: https://github.com/Jbalkind/ariane/commit/6a38132a704ae9b4fb0feeb83ce67ffaf2cc5c0e
