### ISSUE TITLE
Resolve CI ASIC synthesis regression

### ISSUE THREAD

**Issue by zarubaf** [openhwgroup/cva6#1322]
### Is there an existing CVA6 bug for this?

- [X] I have searched the existing bug issues

### Bug Description

There is somehow a synthesis regression in #1317 that needs to be resolved according to @JeanRochCoulon.

**Comment by JeanRochCoulon** [comment]
@ASintzoff  ASIC synthesis is down.  Can you provide information to @domenicw to solve this regression ?

**Comment by ASintzoff** [comment]
ASIC synthesis is fixed.
