### ISSUE TITLE
RVFI Limitation

### ISSUE THREAD

**Issue by AyoubJalali** [openhwgroup/cva6#1338]
### Is there an existing CVA6 bug for this?

- [X] I have searched the existing bug issues

### Bug Description

Hello,
this issue is about the **RVFI** tracer that drive all sort of information related to an instruction _(GPR, PC, CSR , MEM_ADDR ...)_, the problem or the limitation in this tracer is that it can't drive information of an instruction does not been committed (killed or raised an exception), I really want to think about a possibility to update this tracer to be more practical in that way, because it affect **ISACOV** coverage.

**Comment by JeanRochCoulon** [comment]
To my mind, an information is missing: getting an exception without the related instruction is a mess to monitor the cva6 behaviour. I confirm the need to fix it.

**Comment by JeanRochCoulon** [comment]
Related to #1441 
RVFI will be revisited by @Gchauvon, I reassigned this issue.

**Comment by MikeOpenHWGroup** [comment]
Please keep in mind that we want to use the [OpenHW version of RVFI](https://docs.openhwgroup.org/projects/cv32e40s-user-manual/en/latest/rvfi.html), as specified in the CV32E40S User Manual.  It is a super-set of the SymbioticEDA version and contains information needed to operate the ISS as a reference model (e.g. Spike Tandem).

**Comment by zchamski** [comment]
Now RVFI provides extensive information when exceptions are triggered.  @AyoubJalali : is the information provided by RVFI sufficient?  If so, can you close this issue?

**Comment by AyoubJalali** [comment]
> Now RVFI provides extensive information when exceptions are triggered. @AyoubJalali : is the information provided by RVFI sufficient? If so, can you close this issue?

good for me
