### ISSUE TITLE
Decoding LWU as a RV32 instruction

### ISSUE THREAD

**Issue by AyoubJalali** [openhwgroup/cva6#1342]
### Is there an existing CVA6 bug for this?

- [X] I have searched the existing bug issues

### Bug Description

Hello,
I try inject some RV64 instruction with RV32, just to be sure that CVA6 raise an exception on RV64 instruction because the STEP1 configuration is a RV32, so I notice that CVA6 is decoding **LWU** as RV32 instruction.
![image](https://github.com/openhwgroup/cva6/assets/110232072/b0f3d9e1-34e2-4f1d-8291-03b610430942)
to reproduce the BUG you just need to inject a **LWU** (in binary format) for example try to add in your test.S   ->  **### .4byte 0x6f9a6f83**

**Comment by JeanRochCoulon** [comment]
Hello @AyoubJalali 
The merged PR #1344 fix the issue, can you confirm it and close the issue ?

**Comment by AyoubJalali** [comment]
Great You Merge the Fix 
Yes I confirm the PR #1344 fix the issue

**Comment by AyoubJalali** [comment]
The bug is fixed
