### ISSUE TITLE
[QUESTION] MRET in baremetal debugging

### ISSUE THREAD

**Issue by shuvagataUF** [openhwgroup/cva6#1356]
### Is there an existing CVA6 bug for this?

- [X] I have searched the existing bug issues

### Bug Description

I am debugging a baremetal code that is supposed to switch to user mode and attempt to access machine CSRs in user mode. The code is given below:
```
	int main(int argc, char const *argv[]) {
        asm volatile ("csrwi mstatus, 0"); //set MPP to 0 to switch to U mode, MIE and MPIE are same
	asm volatile ("auipc ra, 0"); // save pc to ra
	asm volatile ("csrw mepc, ra"); // write to mepc
	asm volatile ("mret");
        asm volatile ("addiw a0, a0, -136); //some dummy user mode code
	asm volatile ("csrwi mepc, 0") ; // attempt to access machine csr
       }
```
When I am debugging what I expect to see immediately after **mret** is that **mepc** and **pc** will hold the same value and the access attempt from the last line is going to throw an illegal instruction exception. However, when debugging what I get following executing **mret** is that **mepc** and **pc** do not hold the same value as shown:

```
> (gdb) n           
> 9		asm volatile ("mret");
> (gdb) i r mstatus
> mstatus        0x0000000a00000000	SD:0 VM:00 MXR:0 PUM:0 MPRV:0 XS:0 FS:0 MPP:0 HPP:0 SPP:0 MPIE:0 HPIE:0 SPIE:0 UPIE:0 MIE:0 HIE:0 SIE:0 UIE:0
> (gdb) n
> 10		asm volatile ("addiw a0, a0, -136");
> (gdb) i r mstatus
> mstatus        0x0000000a00000080	SD:0 VM:00 MXR:0 PUM:0 MPRV:0 XS:0 FS:0 MPP:0 HPP:0 SPP:0 MPIE:1 HPIE:0 SPIE:0 UPIE:0 MIE:0 HIE:0 SIE:0 UIE:0
> (gdb) i r pc
> pc             0x0000000080000010	2147483664
> (gdb) i r mepc
> mepc           0x0000000080000004	2147483652
```
The last line is executed and does indeed write the CSR which tells me that the switch to user mode wasn't successful. Interestingly, **mpie** is indeed set to the correct value. I should mention that I don't have any startup code written to handle trap vectors but I would still expect **mepc** and **pc** to hold the same value after executing **mret**

What am I missing? Appreciate your help.

**Comment by zarubaf** [comment]
Imho that is a general RISC-V question and I suggest to get the exact behavior from the privileged spec. You can also try around with spike which could be an easier way to get your hands dirty. In this particular case I think you miss setting `mpp` to user mode before executing the `mret`. Closing this for now, feel free to repopen in case you think there is a bug in CVA6.
