### ISSUE TITLE
[BUG] Improving Verilator model generation speed

### ISSUE THREAD

**Issue by pcotret** [openhwgroup/cva6#1374]
### Is there an existing CVA6 bug for this?

- [X] I have searched the existing bug issues

### Bug Description

In a [recent PR](https://github.com/openhwgroup/cva6/pull/1341/commits/2e702bcd82bed617e4b10e856c3e0b97e418d444#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52L566), I've removed the `-j(NUM_JOBS)` because it crashed my virtual machine.

Unfortunately, generation of Verilator model is wayyyy slower...
Should I put it back in a new PR ? (I'll use NUM_JOBS=2 or 4 on my clone)
It may imply as well a short modification of the Readme when we perform `make verilate` ("you can use NUM_JOBS=$(nproc)" or something similar).

**Comment by JeanRochCoulon** [comment]
Related to #1569
