### ISSUE TITLE
[TASK] Add CSRs to Spike RVFI

### ISSUE THREAD

**Issue by zchamski** [openhwgroup/cva6#1384]
**Background**

**What (objective description)**

**How To**

**Current  Status**

**Risks**

**Prerequisites**

**KPI**

**Description of DONE**

**Comment by JeanRochCoulon** [comment]
@mario, can we consider you have already started this task or is it conditionned by the completion of #1402 ?

**Comment by MarioOpenHWGroup** [comment]
@JeanRochCoulon this task is not yet started as first I wanted to have a working version of the tandem without the CSRs. I will start this one today :+1:

**Comment by MarioOpenHWGroup** [comment]
Need to be discussed. All of them or just some?

**Comment by zchamski** [comment]
This is clearly an open question as we can proceed incrementally, or do a small pilot set followed by the Big Bang deployment.  @JeanRochCoulon , @ASintzoff , @MikeOpenHWGroup : what is your take on the approach to choose?

**Comment by JeanRochCoulon** [comment]
@MarioOpenHWGroup Could you close it if done ?

**Comment by MarioOpenHWGroup** [comment]
Sure!
