### ISSUE TITLE
[TASK] Give access to CI logs

### ISSUE THREAD

**Issue by JeanRochCoulon** [openhwgroup/cva6#1388]
***What*** Provide more logs to ease debugging.

***Howto*** Add steps to jobs to collect logs. Then make them publicly available.

***Current status*** Logs are collected from smoke tests only.

***Risks*** Logs can quickly fill disks so the choice of kind of public storage is important. A malicious PR could modify the yaml files or scripts to extract secrets (tokens for instance) so security is a really important question for this task.

***Prerequisites*** Factorizing the regress scripts might help.

***KPI*** None

***Description of done*** The logs are accessible by everyone right from the dashboard.

**Comment by valentinThomazic** [comment]
Considered done (https://github.com/openhwgroup/cva6/pull/1928 https://github.com/openhwgroup/cva6/pull/1931 https://github.com/openhwgroup/cva6/pull/2001)  after discussing with @JeanRochCoulon
