### ISSUE TITLE
[TASK] Implement new instructions with Zcb, Zcmp in riscv-dv

### ISSUE THREAD

**Issue by JeanRochCoulon** [openhwgroup/cva6#1399]
***What (objective description) ?*** Implement new instructions with Zicond, Zcb, Zcmp in riscv-dv.

***How to ?*** Add new class in cva6-dv to decribe all the new instructions, then use the cva6-dv test to generate it.

***Current Status ?*** None.

***Risks ?*** None

***Prerequisites ?*** Zicond, Zce, Zb spec

***KPI ?*** None

***Description of done?*** New generate tests with new intructions.

**Comment by AyoubJalali** [comment]
I add [Zicond](https://github.com/openhwgroup/cva6/pull/1473) & [Zcb](https://github.com/openhwgroup/cva6/pull/1496) instructions into the generator cva6-dv 
for Zcmp I'm waiting for a spec

**Comment by jquevremont** [comment]
@fatimasaleem is working on the spec. Zcmp expected e/o October.

**Comment by JeanRochCoulon** [comment]
Zicond has been disabled in embedded configuration #1534

**Comment by AyoubJalali** [comment]
A MR is ready to be approved

**Comment by AyoubJalali** [comment]
Now we have zcb instructions in the core-dv, but still Zcmp (need a spec)

**Comment by JeanRochCoulon** [comment]
Zcmp can be compiled by GCC master, and simulate with Spike.

**Comment by AyoubJalali** [comment]
Zcmp is implemented due to the PR #1648

**Comment by JeanRochCoulon** [comment]
@ASintzoff  Can you review the task ?   If you think the task is completed, can you update the status from "Done" to "finished" ?
