### ISSUE TITLE
[TASK] Generate random test with Zce, Zb in riscv-dv

### ISSUE THREAD

**Issue by JeanRochCoulon** [openhwgroup/cva6#1400]
***What (objective description) ?*** Generate ramdom tests with the new intruction of the embedded config.

***How to ?*** Add the new tests in generated tests scripts.

***Current Status ?*** None.

***Risks ?*** None

***Prerequisites ?*** Zicond, Zce, Zb spec, implement new intruction in riscv-dv.

***KPI ?*** None

***Description of done ?*** Tests in the CI with the embedded cva6 ISA config.

**Comment by AyoubJalali** [comment]
Need a Zb spec, because I'm sure the riscv-dv support it, but not all of them

**Comment by JeanRochCoulon** [comment]
Zicond has been disabled in embedded configuration #1534

**Comment by AyoubJalali** [comment]
We need to change the gcc compiled on the CI, because the gcc-13 available now do not support these new instructions

**Comment by AyoubJalali** [comment]
I have a ready MR to be reviewed to workaround the gcc-13 problem

**Comment by AyoubJalali** [comment]
for Zb it's done

**Comment by JeanRochCoulon** [comment]
Gcc master to get Zce extension. PR to be done.

**Comment by AyoubJalali** [comment]
the task is done by PR #1617

**Comment by JeanRochCoulon** [comment]
@ASintzoff Can I ask you to review this task. If you think it is completed, please change the status from "Done" to "Finished".
