### ISSUE TITLE
[TASK] Compare Spike and RTL in tandem

### ISSUE THREAD

**Issue by zchamski** [openhwgroup/cva6#1404]
**Background**

Lockstep ("tandem") co-simulation allows early detection of divergences between behaviors of different simulation models on the same test case.  Typically, an Instruction Set Simulator (ISS) and an RTL simulator are fed with the same binary program. The simulation can be stopped as soon as a divergence is detected, or can be pursued for a controlled amount of steps (instruction commits + exceptions) to observe the consequences of the divergence.

For CVA6, the current ISS simulator is Spike and the primary RTL simulator is VCS, set up in either "test harness" or full UVM mode.

**What (objective description)**

Build a software system in which Spike and VCS simulations are executed concurrently and the observable state of both models is compared at every instruction commit and at every exception triggered.

**How To**

* extend CVA6 RVFI implemented in SystemVerilog with the information on CSR state (or state changes), cf. #1402.
* extend/adapt Spike RVFI information to match CVA6-side CSR information, cf. #1384.
* connect the Spike simulator as a slave of the RTL simulation model
* feed instruction commits and exceptions raised on the RTL side to the Spike model
* compare state changes reported by Spike with those reported by the RTL.

**Current  Status**

In progress.  Working prototype available for `vcs-testharness` and `vcs-uvm`, but it only compares PC values, instruction content, and GPR and memory writes.

**Risks**

TBD

**Prerequisites**

Dependency on completion of #1402 and #1384.  For the Embedded configuration additional dependency on #1403.

**KPI**

TBD

**Description of DONE**

Identical set of PASS and FAIL results on CI tests between full trace comparison and lockstep simulation.

**Comment by MarioOpenHWGroup** [comment]
A working version of the Tandem has been pushed to my repo that implements the following:
- Tandem comparing exceptions, interrupts, destination GPR, instruction and pc. 
- Common package that implements the functionality for the testharness and UVM implementation

**Comment by MarioOpenHWGroup** [comment]
Tandem rebased to last cva6/master commit. Some discussion needed regarding integration Sim*.cc  `corev_apu/tb/common/Sim`  into riscv-isa-sim

**Comment by MarioOpenHWGroup** [comment]
Fixing Github CI in order to merge.
Also fixing the issues commented in both PRs.

**Comment by MarioOpenHWGroup** [comment]
CI has been fixed and it shows green on Thales CI and on Github

**Comment by MarioOpenHWGroup** [comment]
PR has been merged already

**Comment by MarioOpenHWGroup** [comment]
On going efforts to make the tandem available on verilator

**Comment by MarioOpenHWGroup** [comment]
I am working on make verilator work on 64bits but it has issues in the DPI interface

**Comment by zchamski** [comment]
Task completed for CV32A65X.  Adding other configurations is a matter of providing the necessary configuration files for Spike, and possibly, of adding futher configurability if needed.
