### ISSUE TITLE
[TASK] Edit the User manual to add embedded description (configuration)

### ISSUE THREAD

**Issue by Gchauvon** [openhwgroup/cva6#1406]
### Is there an existing CVA6 task for this?

- [x] I have searched the existing task issues

### Task Description

Add a description of the embedded configuration (list of all parameters).

### Required Changes

Modification of the user manual

### Current Status

In progress

### Risks

No specific risk

### Description of Done

Description of embedded configuration is accepted and merged

**Comment by JeanRochCoulon** [comment]
Zicond has been discarded. Cache configuration to be decided.

**Comment by JeanRochCoulon** [comment]
Description of params needed to configure 65X is specified in 65x Design Doc. 
See https://github.com/openhwgroup/cva6/blob/master/docs/04_cv32a65x_design/source/parameters_cv32a65x.rst.
This file is automatically generated. this closes the task.
This file can be also referenced by User manual if needed.
