### ISSUE TITLE
[TASK] Condition RTL with A extension parameter

### ISSUE THREAD

**Issue by Gchauvon** [openhwgroup/cva6#1407]
### Is there an existing CVA6 task for this?

- [X] I have searched the existing task issues

### Task Description

Adding `if(CVA6Cfg.*)` in RTL to identify the dead code and remove the dead gates from netlist. 
Based on if() directives, VCS is able to identify the unused code, this will allow to reach 100% code coverage. 

### Required Changes

Modification of multiple RTL files to remove gates if A extension is disabled

### Current Status

Not started

### Description of Done

Removal of all gates related to A extension in cva6 RTL when the A extension is disabled.

**Comment by JeanRochCoulon** [comment]
@AEzzejjari  Have you started this task ?   If it is the case, do not hesitate to ask for the assignment and status changes (or do it if you have the rights)

**Comment by JeanRochCoulon** [comment]
@AEzzejjari  Do you confirm this task is done ?   Can you link with the related PR

**Comment by AEzzejjari** [comment]
The task has been completed, and the related PR number is 1554.

**Comment by JeanRochCoulon** [comment]
I confirm. The modification has been merged, kgate have been reduced. To my mind, the task is finished.
