### ISSUE TITLE
[TASK] Add Zc* in user guide and Requirement Specification

### ISSUE THREAD

**Issue by fatimasaleem** [openhwgroup/cva6#1411]
### Is there an existing CVA6 task for this?

- [x] I have searched the existing task issues

### Task Description

When Zc RTL code is merged, update the requirement specification and user guide (instruction description included) to mention Zc* and Zicond extension support

### Required Changes

Update Requirement spec & user manual

### Current Status

Zc is not mentioned in the specs

### Description of Done

merged PR

**Comment by JeanRochCoulon** [comment]
Any news about this task ?  Needed by #1397

**Comment by jquevremont** [comment]
Expected October 11th or 12th.

**Comment by zarubaf** [comment]
@jquevremont I have added a `due` field to the project so that we can search/track 😄

**Comment by jquevremont** [comment]
> @jquevremont I have added a `due` field to the project so that we can search/track 😄

@zarubaf where did you add it?

**Comment by zarubaf** [comment]
![Screenshot 2023-10-11 at 15 51 18](https://github.com/openhwgroup/cva6/assets/199415/83c0f8db-3178-441c-ad56-ea1d7f720c4d)

Here, and its now a field in the projects list.

**Comment by fatimasaleem** [comment]
Zcb is done. Zcmp is remaining.
