### ISSUE TITLE
Create VPLAN to report code and functional coverages

### ISSUE THREAD

**Issue by JeanRochCoulon** [openhwgroup/cva6#1433]
***What (objective description)?*** Define cva6 vPlan features structure, this will include all cva6 features including optional ones. vPlan coverage report can be filtered by functionality or version

***How to?*** Define feature structure and coverage to be mapped to vPlan

***Current Status?*** draft version, to be submitted to CVA6 verification team for discussions

***Risks?*** None

***Prerequisites ?*** None

***KPI ?*** None

***Description of done?*** vPlan file

**Comment by AnouarZajni** [comment]
Done on Merge request [!77](https://gitlab-tss.gemalto.com/riscv/ohg-pr/cva6/-/merge_requests/77)

**Comment by JeanRochCoulon** [comment]
If the feature is not yet merge on master branch, I would prefer to keep the status "In progress" then "done".

**Comment by AnouarZajni** [comment]
@JeanRochCoulon , Updated HVP to align to cva6 master verification plan, waiting for review

**Comment by JeanRochCoulon** [comment]
@AyoubJalali @MikeOpenHWGroup Can you approve this Task ?   The objective is to validate the way we display the verification status.
