### ISSUE TITLE
[TASK] Generate CSR DVplan

### ISSUE THREAD

**Issue by JeanRochCoulon** [openhwgroup/cva6#1434]
### Is there an existing CVA6 task for this?

- [x] I have searched the existing task issues

### Task Description

Generate the Dvplan for CSRs in embedded config: field access, illegal CSRs

### Required Changes

Updating STEP1 Dvplan

### Current Status

STEP1 dvplan 

### Risks

none

### Prerequisites

CSR Spec for embedded

### KPI (KEY Performance Indicators)

none

### Description of Done

CSR Dvplan file for embedded config

**Comment by JeanRochCoulon** [comment]
is this task started ?

**Comment by AnouarZajni** [comment]
I started it today.

**Comment by AnouarZajni** [comment]
@JeanRochCoulon, task done waiting for merge approval.

**Comment by JeanRochCoulon** [comment]
Can you refer the PR number ?

**Comment by AnouarZajni** [comment]
CSR DVPLAN embedded is PR !86
I've also updated hvp and RAL files to achieve dvplan goals in !87

**Comment by AnouarZajni** [comment]
@ASintzoff, updated CSR Dvplan and pushed to the same merge request !86

**Comment by AnouarZajni** [comment]
@ASintzoff , RAL files updated to reflect Dvplan with Legal/Illegal values and CSR counter features. Pushed to 87

**Comment by AnouarZajni** [comment]
@ASintzoff , Updated merge !86 following feedbacks

**Comment by AnouarZajni** [comment]
Merge Done, closing the the task

**Comment by JeanRochCoulon** [comment]
@MikeOpenHWGroup  Can I ask you to review this task ? If you think this task is completed, please change the status from "Done" to "finished". Thanks

https://github.com/openhwgroup/cva6/tree/master/verif/docs/VerifPlans/csr_access

**Comment by MikeOpenHWGroup** [comment]
I am re-opening this Issue as @JeanRochCoulon has requested a review of the CSR DV Plan.

**Comment by MikeOpenHWGroup** [comment]
I have conducted a review of the CSR DVPlan, see #1697.

**Comment by JeanRochCoulon** [comment]
@AnouarZajni @ASintzoff  Is this task completed ?   If yes, please refer the related PR.

**Comment by AnouarZajni** [comment]
@JeanRochCoulon , yes task is done in MR !85 with PR #1606
