### ISSUE TITLE
[TASK] Generate CSR tests for embedded config

### ISSUE THREAD

**Issue by JeanRochCoulon** [openhwgroup/cva6#1435]
### Is there an existing CVA6 task for this?

- [x] I have searched the existing task issues

### Task Description

Generate tests for CSRs in embedded config

### Required Changes

To de defined

### Current Status

A first version of tests have been produced and merged on master

### Risks

none

### Prerequisites

CSR Spec for embedded

### KPI (KEY Performance Indicators)

none

### Description of Done

Reset and Read/Write CSR tests for embedded

**Comment by AnouarZajni** [comment]
Test generated, @AyoubJalali will test and merge.

**Comment by AyoubJalali** [comment]
> Test generated, @AyoubJalali will test and merge.

Yes working on it

**Comment by AnouarZajni** [comment]
List of all tests generated:
1- csr_test.S : with following scenarios:
      - csrrst_test.S : Read all registers reset value
      - csrrw_test.S  : Write/Read all read/write registers
      - csrrwi_test.S : Write/Read all read/write registers using immediate instructions
      - csrcs_test.S  : Write/Read all read/write registers using Clear/Set instructions
      - csrcsi_test.S : Write/Read all read/write registers using Clear/Set immediate instructions
      -csrrw_fields_test.S : Write/Read all registers fields

2- csrrw_ro_test.S : Write/Read all registers including read only ones
3- csrrw_unmapped_test.S : Write/Read all non-existent registers
4- csrrw_fullrandom_test.S : Write/Read all registers from 0 to 0xFFF addresses

**Comment by JeanRochCoulon** [comment]
@AEzzejjari   Can I ask you to review this task. If you think the task is finished, please comment and update the task from "Done" to "finished".

**Comment by AEzzejjari** [comment]
The code coverage report shows that these tests give us access to all CVA6 CSR registers. So this task is done.
