### ISSUE TITLE
[TASK] Trap DV plan for embedded configuration

### ISSUE THREAD

**Issue by ASintzoff** [openhwgroup/cva6#1459]
### Is there an existing CVA6 task for this?

- [x] I have searched the existing task issues

### Task Description

Write trap DV plan for embedded configuration (no Supervisor mode, no User mode)

### Required Changes

Add new DV plan

### Current Status

In Progress

### Description of Done

DV plan approved

**Comment by ASintzoff** [comment]
Waiting Thales internal review

**Comment by JeanRochCoulon** [comment]
@AnouarZajni    Dvplan has been created by @ASintzoff    Can I ask you to review it ?   It is an opportunity to be aware of it before switching to its execution.   If you think it is completed, please comment and switch status from "done" to "finished".

**Comment by AnouarZajni** [comment]
@JeanRochCoulon, review done
