### ISSUE TITLE
[BUG] install riscvpk failed

### ISSUE THREAD

**Issue by RonxBulld** [openhwgroup/cva6#1499]
### Is there an existing CVA6 bug for this?

- [X] I have searched the existing bug issues

### Bug Description

in the description of [#1358](https://github.com/openhwgroup/cva6/issues/1358), riscv64-unknown-elf to be replaced by riscv-non-elf, but my build system always talk:
```
checking build system type... x86_64-pc-linux-gnu
checking host system type... Invalid configuration `riscv-none-elf': machine `riscv-none' not recognized
configure: error: /bin/bash ../scripts/config.sub riscv-none-elf failed
```
And the $PATH is:
```
/home/cva/tools/bin:/home/cva/tools:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin
```

**Comment by JeanRochCoulon** [comment]
@sjthales  Are you familiar with riscvpk command ?   I twould be nice to help @RonxBulld and @hhhsiang if it is the case.

**Comment by JeanRochCoulon** [comment]
Related tash #1569

**Comment by valentinThomazic** [comment]
Hey @RonxBulld, did you manage to solve your issue ? If you did, could you close it ?

**Comment by JeanRochCoulon** [comment]
Hi @RonxBulld    Thanks @valentinThomazic having given recommendation to help. But as proxy kernel is not maintained by CVA6 repository, that's why I propose to close the Github issue and I invite you to contribute to add this feature.
