### ISSUE TITLE
[TASK] Add Architectural tests for Bitmanip extensions

### ISSUE THREAD

**Issue by fatimasaleem** [openhwgroup/cva6#1528]
### Is there an existing CVA6 task for this?

- [x] I have searched the existing task issues

### Task Description

Add the arch-tests for Bitmanip in the CVA6 CI yaml files.
Bitmanip tests are already upstream in riscv-arch test repository

### Required Changes

Update the hash for install arch-tests 
Update yaml files for cv32 and cv64 for adding bitmanip tests 

### Current Status

Bitmanip tests are not included in the CVA6 regressions

### Description of Done

Merged PR

**Comment by fatimasaleem** [comment]
Adding arch tests for Bitmanip extensions in the regressions for 64-bit config step 1 config, and embedded config.

**Comment by JeanRochCoulon** [comment]
@AyoubJalali  Can you confirm these tests have been added to the CI ?   If you think the task is complete, can I ask you to comment and update the status from "done" to "finished" ?

**Comment by AyoubJalali** [comment]
> @AyoubJalali Can you confirm these tests have been added to the CI ? If you think the task is complete, can I ask you to comment and update the status from "done" to "finished" ?

Yes the tests are in the CI now, but I don't have the rights to the change "status"
