### ISSUE TITLE
[Enhancement] Add RVFI  

### ISSUE THREAD

**Issue by zarubaf** [openhwgroup/cva6#153]
Add support for RISC-V formal interface.

**Comment by raulbehl** [comment]
Hi Florian, 

I know you guys have a lot on-going but any heads up on when this would be done? 

Thank you, 
Rahul

**Comment by zarubaf** [comment]
Hi Rahul,

unfortunately, at this stage, we don't have any further information on when we can tackle to add this feature. There are a couple of other fixes planned first, so this probably has to wait for a little longer (at least from our side).

Best,
Florian

**Comment by raulbehl** [comment]
Sure. I understand. I have actually used the basic RVFI in one of the project and can help with the integration. Though I would need help to capture the right RTL state as needed by the interface. 

Do you think that can be done?

**Comment by hyunsuchae** [comment]
Hi, I am trying to add RVFI feature to Ariane, if there isn't a version of this yet.
Is there a way for me to get the SystemVerilog code that does not have cache integrated in Ariane?
Thanks.

**Comment by MikeOpenHWGroup** [comment]
RVFI has been supported for some time.  Closing.
