### ISSUE TITLE
[BUG] UVM failed on questa Sim

### ISSUE THREAD

**Issue by AnikBalo** [openhwgroup/cva6#1533]
### Is there an existing CVA6 bug for this?

- [X] I have searched the existing bug issues

### Bug Description

Hi, I was trying to simulate CVA6 in questaSim. 
While running the command:
"make sim elf-bin=<elf_path_of_dhrystone>"
 I am not getting any error but UVM FAILED. Actually, I want to generate the activity file from the simulation. Any idea if this is okay or how to debug this issue? Thanks!  

The output: 
![uvm_error](https://github.com/openhwgroup/cva6/assets/96606368/d9b64243-c744-4c87-93af-6dae3acd3a96)

**Comment by JeanRochCoulon** [comment]
Hello
As you can read in README.md, make sim is not the right way to simulate the CVA6. You should use cva6.py command. But on my side, I use only VCS and verilator, I cannot confirm the Questasim is fully functional, but I wold be pleased to get your feedback.

**Comment by AnikBalo** [comment]
@JeanRochCoulon I thnik CVA6 section has been removed from [core-v-verif](https://github.com/openhwgroup/core-v-verif#core-v-verif) repository.

**Comment by JeanRochCoulon** [comment]
The README.md with the commands to be executed is in cva6 repo (and not core-v-verif)

**Comment by valentinThomazic** [comment]
Hi, did you manage to solve your issue ?

**Comment by JeanRochCoulon** [comment]
Hello @AnikBalo    Today Questa is not supported by CVA6 repository. If you are ready to contribute the target questa-testharness can be updated to work. I propose to close this issue becasue it is not supported.
