### ISSUE TITLE
Missing license in `bootrom`

### ISSUE THREAD

**Issue by zarubaf** [openhwgroup/cva6#1551]
@Moschn would you be okay licensing the Bootrom under Apache? As far as I've seen there isn't any license associated with it.

`https://github.com/openhwgroup/cva6/tree/master/corev_apu/fpga/src/bootrom`

**Comment by Moschn** [comment]
Sure. 

With SMP.h we should be careful, as I believe it is mostly a copy from the SiFives old Freedom boot repo: https://github.com/sifive/freedom/blob/master/bootrom/sdboot/include/smp.h. However, they are also Apache 2.0, so it should not be an issue (and they also do not have a file header). Actually, to be compliant with the license we should have added it to the file in the first place. My bad!
