### ISSUE TITLE
[TASK] Use cva6.py to simulate cva6 and clean-up env setup

### ISSUE THREAD

**Issue by JeanRochCoulon** [openhwgroup/cva6#1569]
### Is there an existing CVA6 task for this?

- [x] I have searched the existing task issues

### Task Description

Support only cva6.py commands to simulate cva6.
Today two set of commands are available to simulate cva6: cva6.py coming from riscv-dv repo and "make verilate" supported by Makefile. To reduce confusion for newcomers and increase the simulation env quality, we will support only the cva6.py commands and remove the "make verilate" commands from Makefile.

### Required Changes

Move Github action CI to cva6.py commands

### Current Status

Today two set of commands are available to simulate cva6

### Risks

Users using "make verilate" should change their habits.

### Prerequisites

Before removing make verilate, 
- GitHub actions CI must be move to cva6.py commands and 
- we must confirm all current features are supported by cva6.py

### Description of Done

"make verilate" removed from Makefile

**Comment by JeanRochCoulon** [comment]
@ValentinThomazic

**Comment by valentinThomazic** [comment]
Usage of the proxy kernel which was still using Makefile targets to run simulation has been dropped.
See : https://github.com/openhwgroup/cva6/pull/1663
This means that, at this point, all simulation features should be supported by cva.py

**Comment by JeanRochCoulon** [comment]
GitHub Actions uses "make verilate" to simulate. A possible action would be to switch this CI from "make verilate" to "cva6.py".     The ideal action would be to adapt Github Actions to "cva6.py" and to remove the relative "make verilate" commands from the Makefile.  I wonder what is the plan for you @MarioOpenHWGroup and @MikeOpenHWGroup ?

**Comment by JeanRochCoulon** [comment]
Good job. The task is finished.
