### ISSUE TITLE
[Question] Synthesis error

### ISSUE THREAD

**Issue by mahdi259** [openhwgroup/cva6#1570]
### Is there an existing CVA6 bug for this?

- [X] I have searched the existing bug issues

Hi
My target was implementing CVA6 on FPGA. I run `make clean` and `make fpga` and I got error. The output of command line and vivado log is attached. 
[error.txt](https://github.com/openhwgroup/cva6/files/13110947/error.txt)
[hs_err_pid42902.log](https://github.com/openhwgroup/cva6/files/13110948/hs_err_pid42902.log)

**Comment by mahdi259** [comment]
I opened ariane.xpr now and run synthesis. Here is the picture of vivado.
![Screenshot from 2023-10-24 09-03-40](https://github.com/openhwgroup/cva6/assets/73544027/4ea6c7ed-bbd8-430b-a134-bd7177ae1243)

**Comment by JeanRochCoulon** [comment]
@Gchauvon    Do you have an idea ?

**Comment by mahdi259** [comment]
The problem was missing packages.
I run
 `sudo apt install libcanberra-gtk-module libcanberra-gtk3-module`
And was synthesized successfully.
Thanks.
![IMG_20231024_114135_540](https://github.com/openhwgroup/cva6/assets/73544027/a80900f5-9d19-455e-9fa2-53202b4ede8d)
