### ISSUE TITLE
Hardcoded path to the wrong position

### ISSUE THREAD

**Issue by rejsys** [openhwgroup/cva6#1572]
Hello,

the hardcoded path shown here is pointing to the wrong position:

https://github.com/openhwgroup/cva6/blob/53d388071d51f4cca018e5f4ddf08ccacb45ecff/Makefile#L55

This creates an error if the flag `TRACE_FAST=1` is set in `make verilator`:

https://github.com/openhwgroup/cva6/blob/53d388071d51f4cca018e5f4ddf08ccacb45ecff/Makefile#L563

**Comment by JeanRochCoulon** [comment]
Related to #1569

**Comment by valentinThomazic** [comment]
Hey @rejsys, https://github.com/openhwgroup/cva6/pull/1686 adressing this issue has been merged. If you are ok with the changes, please close your issue.

**Comment by rejsys** [comment]
fixed here: #1686
