### ISSUE TITLE
[Compressed decoder] : Missing XLEN condition on RV64C instructions

### ISSUE THREAD

**Issue by AyoubJalali** [openhwgroup/cva6#1578]
### Is there an existing CVA6 bug for this?

- [X] I have searched the existing bug issues

### Bug Description

Hello,
To make long story short, there's bunch of RV64C instructions without a XLEN == 64 condition, and that affect code coverage as you see : 
![image](https://github.com/openhwgroup/cva6/assets/110232072/6c5f7159-ca4b-4f4d-9e98-2bcd668acc8d)

**Comment by fatimasaleem** [comment]
Got it. Let me fix this in the same PR as for https://github.com/openhwgroup/cva6/issues/1565

**Comment by AyoubJalali** [comment]
Thanks
