### ISSUE TITLE
L1+L2 cache coherency 

### ISSUE THREAD

**Issue by HimalSubedi787** [openhwgroup/cva6#1611]
### Is there an existing CVA6 bug for this?

- [X] I have searched the existing bug issues

### Bug Description

How is L2 cache writeback, and refill counted in CVA6 Multicore? 

What happens if a dirty cache line is evicted from the L1 cache? Will it be kept as a dirty cache line in the L2 cache or written back to memory?

And what happens then if two cores do a LOAD to this cache line?

Is there a mechanism that forwards the dirty cache line between the cores without writing it back to L2 or memory in Openpiton cache Bus system of cva6?

**Comment by MikeOpenHWGroup** [comment]
Hi @HimalSubedi787, thanks for your interest in the CVA6.

Please note that the CVA6 is not a multicore project, so such questions are out of scope for this repo.  There are several projects that use the CVA6 in a multicore environment (such as OpenPiton), and you can consult those projects to see how they addressed the issue.

Having said that, there is extension treatment of the caches in the [CVA6 User Manual](https://docs.openhwgroup.org/projects/cva6-user-manual/).  Please let us know if there is a specific section of this document that requies further clarification.

**Comment by JeanRochCoulon** [comment]
@HimalSubedi787   As these questnios are out of the scope of CVA6 repository project, can I ask you to close the issue ?

BTW I know that @cfuguet is interrested in this kind of topics, he maybe get some answer to your questions
