### ISSUE TITLE
[TASK] Make Github CI to use cva6.py

### ISSUE THREAD

**Issue by MarioOpenHWGroup** [openhwgroup/cva6#1681]
### Is there an existing CVA6 task for this?

- [X] I have searched the existing task issues

### Task Description

Currently, the Github CI utillizes the Makefile directly with verilator for running the tests. We should move to `verif/sim/cva6.py` to standarize the way of executing cva6. 

### Required Changes

Edit github CI yamls to use `cva6.py`

### Current Status

Currently Makefile is directly used with verilator 

### Description of Done

Transition to `cva6.py`

**Comment by JeanRochCoulon** [comment]
Done thanks to @MarioOpenHWGroup
