### ISSUE TITLE
[BUG] : MVENDORID Reset value

### ISSUE THREAD

**Issue by AyoubJalali** [openhwgroup/cva6#1735]
### Is there an existing CVA6 bug for this?

- [x] I have searched the existing bug issues

### Bug Description

Hello, I'm a little confuse about the reset value of MVENDORID CSR : 

1. RTL read 0x00000602
2. The [doc](https://github.com/openhwgroup/cva6/blob/master/docs/01_cva6_user/CV32A6_Control_Status_Registers.rst#:~:text=Instruction%20Retired%20counter-,mvendorid,-0xF11) has 0x0 as reset value.

for sure there's a BUG but where ? 
IS it the CVA6 or the CSR documentation

**Comment by MarioOpenHWGroup** [comment]
@JeanRochCoulon probably the documentation is wrong?

**Comment by ASintzoff** [comment]
The RTL is correct (see issue #715).

**Comment by AyoubJalali** [comment]
@JeanRochCoulon but in https://github.com/openhwgroup/cva6/blob/master/docs/01_cva6_user/CV32A6_Control_Status_Registers.rst ?

**Comment by JeanRochCoulon** [comment]
#1754 requests to remove the CSR chapter from USer Manual. This GitHub issue can be close. Thank @AyoubJalali for the warning.
