### ISSUE TITLE
Remove deprecated CSR chapter from User Manual

### ISSUE THREAD

**Issue by JeanRochCoulon** [openhwgroup/cva6#1754]
### Is there an existing CVA6 bug for this?

- [X] I have searched the existing bug issues

### Bug Description

The User Manual includes the CSR file done a long time ago by Jade https://github.com/openhwgroup/cva6/blob/master/docs/01_cva6_user/CV32A6_Control_Status_Registers.rst. This created confusion in #1735. As this description is deprecated and wrong, can we remove it from this document, in the meantime we find a solution to specify the CSR whatever the configuration.

**Comment by jquevremont** [comment]
First attempt in #1766

**Comment by jquevremont** [comment]
@JeanRochCoulon, can you confirm the issue is closed?

**Comment by JeanRochCoulon** [comment]
Indeed the PR is closed. Of course the CSR description need to be improved, this task is planned.
