### ISSUE TITLE
[BUG] Undefined reference to functions specified in corev-apu/tb/ariane_tb.cpp file while running CVA6 on Verilator

### ISSUE THREAD

**Issue by Shreesh-Kulkarni** [openhwgroup/cva6#1759]
### Is there an existing CVA6 bug for this?

- [X] I have searched the existing bug issues

### Bug Description

I got this error while running CVA6 on verilator via the Makefile. 
![image](https://github.com/openhwgroup/cva6/assets/78203773/3207f6b8-8f15-426b-9ddd-74468417a86e)
After inspecting the `ariane_tb.cpp` file, there are the 3 instructions declared as `extern` functions, most probably referring to a different file which the makefile/.cpp file is unable to fetch.
![image](https://github.com/openhwgroup/cva6/assets/78203773/4bc7da63-a172-472d-ac00-b56555abbade)

Would appreciate help regarding this and any suggestions regarding the cause of the error and how one would fix it.

**Comment by JeanRochCoulon** [comment]
Hello @Shreesh-Kulkarni   thanks for the report.
Can you confirm you simulate executing cva6.py ?

**Comment by Shreesh-Kulkarni** [comment]
Thank you for replying, @JeanRochCoulon. I simulated and executed cva6.py and I received the same error. I am attaching the screenshots for the same.
![image](https://github.com/openhwgroup/cva6/assets/78203773/796cfbb3-6d32-453e-9977-6b77dce54409)
I inspected the log file and the same error popped up as attached below :
![image](https://github.com/openhwgroup/cva6/assets/78203773/99060b59-34f5-4e85-bdd9-8c43a9149afd)

**Comment by MarioOpenHWGroup** [comment]
The problem here is probably that spike is not installed, which commands have you run before the `cd ./verif/sim` ?

**Comment by MarioOpenHWGroup** [comment]
Which version of verilator are you using? Verilator headers should include this `svdpi.h`.

**Comment by bekbeis** [comment]
I have Verilator 4.028 installed globally, and Verilator 5.018 installed locally.

The `svdpi.h` is indeed present in the local directory of Verilator. However, it is absent in the global directory.

Could it be that `verif/regress/install-spike.sh` refers to the global version of Verilator instead of the local one? If yes, can you please tell me how I can fix that?

**Comment by MarioOpenHWGroup** [comment]
Yes it is what is happening. The setup-env should have set it correctly, can you unset the `VERILATOR_INSTALL_DIR` and source the `regress/sim/setup-env.sh` again?

**Comment by bekbeis** [comment]
That helped, thank you so much!

**Comment by Shreesh-Kulkarni** [comment]
@bekbeis Did you try running it with just verilator?

**Comment by bekbeis** [comment]
@Shreesh-Kulkarni not really, I just followed the instructions from the readme file

**Comment by JeanRochCoulon** [comment]
Did you try ?   If it works, please comment and close the github issue.

**Comment by bekbeis** [comment]
I tried running cva6 with just Verilator, and it seems to work for me (but this was after fixing my issue with Spike)

**Comment by Shreesh-Kulkarni** [comment]
Sorry for responding late. But I'm still facing the issue even after installing Spike.
![image](https://github.com/openhwgroup/cva6/assets/78203773/81228ee3-77cf-4101-94b5-97959121b5b3)
The below image I have attached clearly shows that Spike has been installed in the tools directory.
![image](https://github.com/openhwgroup/cva6/assets/78203773/0a93be0f-26a0-4ed9-8791-433142676632)

**Comment by Shreesh-Kulkarni** [comment]
Sorry for responding late. The issue was with the toolchain I had already installed. I reconfigured it and it works fine now. Sorry for the trouble.
