### ISSUE TITLE
[BUG] Small typo in GCC toolchain builder "Getting Started" instructions

### ISSUE THREAD

**Issue by TommyMurphyTM1234** [openhwgroup/cva6#1840]
### Is there an existing CVA6 bug for this?

- [X] I have searched the existing bug issues

### Bug Description

The GCC toolchain builder "Getting Started" instructions:

* https://github.com/openhwgroup/cva6/tree/master/util/gcc-toolchain-builder#getting-started

include this text:
```
# 3. Build and install the toolchain (requires write+create permissions for $INSTALL_DIR.)
You can set 
sh build-toolchain.sh $INSTALL_DIR
```
It looks like "You can set" is prematurely truncated and probably should be a comment rather than a command?

**Comment by valentinThomazic** [comment]
Hey @TommyMurphyTM1234, you are right ! Don't hesitate to submit a PR to fix the issue :)

**Comment by valentinThomazic** [comment]
You can do what you deem the most appropriate, I would delete it.

**Comment by JeanRochCoulon** [comment]
Done by #1901
