### ISSUE TITLE
Work-ver/Variane_testharness failed when runing an elf file

### ISSUE THREAD

**Issue by niuzhi1221** [openhwgroup/cva6#1875]
I write a helloworld.c file, and then generate a helloworld binary file. After that, I execute :
**work-ver/Variane_testharness verif/tests/custom/hello_world/hello_world**
but it failed , just like this:
![QQ20240226-212731](https://github.com/openhwgroup/cva6/assets/114903615/b633f3f2-35a8-4169-b7ed-4c37a6755faa)

**Comment by valentinThomazic** [comment]
Hey @niuzhi1221, this is not the correct way to run simulation with the CVA6. 
Please follow the README instructions.

**Comment by niuzhi1221** [comment]
> Hey @niuzhi1221, this is not the correct way to run simulations with the CVA6. Please follow the README instructions.

Ok, I know it. So I must use cva6.py to run simulation by configuring something?

**Comment by valentinThomazic** [comment]
Well, there is already a hello_world example in the Quickstart so I suggest you follow the example.

**Comment by niuzhi1221** [comment]
> Well, there is already a hello_world example in the Quickstart so I suggest you follow the example.

Thanks so much!
