### ISSUE TITLE
RVFI : Missing CSRs in the RVFI implementation

### ISSUE THREAD

**Issue by AyoubJalali** [openhwgroup/cva6#1880]
### Is there an existing CVA6 bug for this?

- [X] I have searched the existing bug issues

### Bug Description

Hello,
Thanks to @yanicasa, now the RVFI implement CSRs in the design, but there's some missing CSRs.
The idea here is to implement all the RISCV supported CSRs, as we know the CVA6 has more then one configuration, so that's help us to filter the CSRs coming from the RVFI depend on the configuration.

it's a work should be done now or later

**Comment by yanicasa** [comment]
Hello,
Most of the missing CSRs are related to performance counters. 
Do you have a particular missing CSR to add?

**Comment by yanicasa** [comment]
do you have an exemple of registers name?

**Comment by AyoubJalali** [comment]
> do you have an exemple of registers name?

like uie, ustatus, uip, ucause ...

**Comment by JeanRochCoulon** [comment]
Any news on this issue ?

**Comment by JeanRochCoulon** [comment]
@AyoubJalali Can you status on this Github issue?   Yannick and Côme have fixed CSRs several weeks ago, is it ok for you ?

**Comment by AyoubJalali** [comment]
I think this is fine for me !!
