### ISSUE TITLE
Setup error

### ISSUE THREAD

**Issue by michael116688** [openhwgroup/cva6#1883]
### Is there an existing CVA6 bug for this?

- [X] I have searched the existing bug issues

### Bug Description

After I executed the commands:
`export DV_SIMULATORS=veri-testharness,spike
bash verif/regress/smoke-tests.sh`
I encountered some errors.
![image](https://github.com/openhwgroup/cva6/assets/128683287/417be826-09a6-4d82-b165-0c0bd0085218)
![image](https://github.com/openhwgroup/cva6/assets/128683287/a0f8a7a3-492a-4846-b8fe-7c3500e23e5d)

Is that the Spike install problem? How could I resolve this?
Thanks.

**Comment by JeanRochCoulon** [comment]
Have you executed the following command :   git submodule update --init --recursive    ?
