### ISSUE TITLE
setup problem

### ISSUE THREAD

**Issue by michael116688** [openhwgroup/cva6#1892]
### Is there an existing CVA6 bug for this?

- [X] I have searched the existing bug issues

### Bug Description

After I executed the commands:
`export DV_SIMULATORS=veri-testharness,spike bash verif/regress/smoke-tests.sh`
I encountered some problems.

> ls: cannot access '/123/cva6/util/gcc-toolchain-builder/src/bin/riscv*-gcc': No such file or directory

> Tue, 05 Mar 2024 23:24:08 ERROR ERROR return code: True/127, cmd:/123/cva6/util/gcc-toolchain-builder/src/bin/-gcc --version

It seems like dosen't find "/bin/riscv*-gcc" & "/bin/-gcc" , but where should it be ?

![image](https://github.com/openhwgroup/cva6/assets/128683287/4e83464c-60c5-4bc0-9310-ebbd5fef54c2)
![image](https://github.com/openhwgroup/cva6/assets/128683287/4e686510-dcb4-4ea1-9e86-096a79988600)
![image](https://github.com/openhwgroup/cva6/assets/128683287/11b42f35-a900-40e4-ad8d-099869d8321d)

**Comment by JeanRochCoulon** [comment]
Have you installed the tools following the README ?     A env variable is not setup in /123/cva6/util/gcc-toolchain-builder/src/bin/-gcc

**Comment by JeanRochCoulon** [comment]
BTW your issue is not a "BUG" but a "QUESTION" (so far)

**Comment by michael116688** [comment]
> Have you installed the tools following the README ? A env variable is not setup in /123/cva6/util/gcc-toolchain-builder/src/bin/-gcc

I have reset my env variable, and installed the tools again. The problems were fixed.
Thank you very much.
