### ISSUE TITLE
[Question] <Running regression tests simulations>

### ISSUE THREAD

**Issue by michael116688** [openhwgroup/cva6#1895]
I run the riscv-arch-test regression test suite with the Verilator model by the following command.
```
export DV_SIMULATORS=veri-testharness,spike
bash verif/regress/dv-riscv-arch-test.sh
``` 
![image](https://github.com/openhwgroup/cva6/assets/128683287/69930576-346e-4ab8-9aad-9303068b413c)

And, I get `add-01.cv64a6_imafdc_sv39.log.iss`. There are failed & error here. How could I fixed it?

![image](https://github.com/openhwgroup/cva6/assets/128683287/eb8d9d92-59a6-4e47-ace8-49b6098a5e20)

**Comment by JeanRochCoulon** [comment]
Please rebase your repository, and retry the command. A env checkup has been added Yesterday, it could help to debug.

**Comment by JeanRochCoulon** [comment]
Does it work ?

**Comment by michael116688** [comment]
> bash verif/regress/dv-riscv-arch-test.sh

It can start simulation, but when testing "B/src/zext.h-01.S" I met the error like bellow.
 
![image](https://github.com/openhwgroup/cva6/assets/128683287/33749242-6534-40f0-8084-6488a6cbba72)

The .log.iss file is here.
![image](https://github.com/openhwgroup/cva6/assets/128683287/0c3588ed-a228-404d-9525-91197baf1c66)

**Comment by JeanRochCoulon** [comment]
The simulation does not stop. I think we get the same behaviour on our side. @valentinThomazic or @cathales can you double check it ?

**Comment by valentinThomazic** [comment]
Yes we do, the failed test is not caused by your environment which seems fine since you can run simulations.
As to why does the test timeouts, this is another question.

**Comment by michael116688** [comment]
OK, thank you. 
I'll open another question for this.
