### ISSUE TITLE
Exclude unread module from toggle coverage

### ISSUE THREAD

**Issue by JeanRochCoulon** [openhwgroup/cva6#1903]
### Is there an existing CVA6 bug for this?

- [X] I have searched the existing bug issues

### Bug Description

This module is instantiated to tie the unconnected nets. They are not functional and can be excluded from code coverage.

**Comment by JeanRochCoulon** [comment]
@ASintzoff @AEzzejjari @AnouarZajni

**Comment by AyoubJalali** [comment]
@JeanRochCoulon which module specifically ?

**Comment by JeanRochCoulon** [comment]
The module name is "unread". 

![image](https://github.com/openhwgroup/cva6/assets/56552370/d45984ec-f9f3-41c6-a24e-754056cabc06)

**Comment by JeanRochCoulon** [comment]
Done by #1907

**Comment by AnouarZajni** [comment]
@AyoubJalali, it could be better to exclude using "-module unread" instead of "-tree "
