### ISSUE TITLE
[Question] simulation of CVA6 using cva6.py not successful

### ISSUE THREAD

**Issue by yulong-lan** [openhwgroup/cva6#1909]
I have strictly followed READ.ME step by step, but I still cannot run smoke-tests or the hello world test in the section: Running standalone simulations.

```
riscv-none-elf-gcc -v
gcc version 13.1.0 (GCC)

verilator -version
Verilator 5.008 2023-03-04 rev v5.008 (mod)
```

I have installed RISCV toolchain based on READ.ME step 2, and Spike, verilator .etc from `bash verif/regress/smoke-tests.sh`, before that `help2man `and `device-tree-compiler` were also installed.

No matter smoke tests or the hello_world standalone binary result in this error message:
`Fri, 08 Mar 2024 22:11:14 ERROR    ERROR return code: True/2, cmd:make veri-testharness target=cv32a60x variant=rv32imac_zba_zbb_zbs_zbc_zicsr_zifencei elf=/home/zen3/cva6_new/cva6/verif/sim/out_2024-03-08/directed_c_tests/hello_world.o path_var=/home/zen3/cva6_new/cva6/ tool_path=/home/zen3/cva6_new/cva6/tools/spike/bin isscomp_opts="" issrun_opts="+debug_disable=1 +ntb_random_seed=1" isspostrun_opts="0x0000000080000000" log=/home/zen3/cva6_new/cva6/verif/sim/out_2024-03-08/veri-testharness_sim/hello_world.cv32a60x.log &> /home/zen3/cva6_new/cva6/verif/sim/out_2024-03-08/veri-testharness_sim/hello_world.cv32a60x.log.iss `

Can anyone help point out what could possibly be wrong?

**Comment by JeanRochCoulon** [comment]
Error description is inside /home/zen3/cva6_new/cva6/verif/sim/out_2024-03-08/veri-testharness_sim/hello_world.cv32a60x.log.iss
