### ISSUE TITLE
[Question] <Running regression tests simulations: stop at test "B/src/zext.h-01.S"> 

### ISSUE THREAD

**Issue by michael116688** [openhwgroup/cva6#1918]
It can start simulation, but when testing "B/src/zext.h-01.S" I met the error like bellow.
#1895 @valentinThomazic told that the test was timeout. How can I fix it?

![image](https://github.com/openhwgroup/cva6/assets/128683287/fee07efb-eafe-4884-b54b-466e23a419f9)
The .log.iss file is here.
![image](https://github.com/openhwgroup/cva6/assets/128683287/6ad66fca-5bbb-48be-820b-6dd5dbdf8f82)

**Comment by JeanRochCoulon** [comment]
When we face this kind of problem, we compare the log trace coming from Spike and RTL to understand the discrepancy, and try to solve the issue. Traces are under out_xxxx/

**Comment by michael116688** [comment]
In this problem, I used the command 
`export DV_SIMULATORS=veri-testharness,spike
bash verif/regress/dv-riscv-arch-test.sh`
It seem like to used verilator& ISS to run this simulation.
However, I tried to use these two simulation types separately. (not at the same round of simulation)
Then, it works.

So, I think this problem just like what #1895 @valentinThomazic said, the test is timeout.
When using two simulation types, ex. verilator& ISS, at the same time, the simulation time will too long
that the error comes out or the simulation stop.
For another solution, I think the simulation time maybe can be modified more longer.

**Comment by michael116688** [comment]
> When we face this kind of problem, we compare the log trace coming from Spike and RTL to understand the discrepancy, and try to solve the issue. Traces are under out_xxxx/

I tried to use the two simulation types (veri-testharness& Spike) separately. (not at the same round of simulation)

I use Spike first. It can completely run riscv-arch-test.
Than, when I use veri-testharness, it still have the same problem come out.
Is it still the same method to solve the issue?

**Comment by valentinThomazic** [comment]
Your result is normal, the issue is coming from the RTL. Spike can run the test fine.

**Comment by valentinThomazic** [comment]
Maybe this issue can be closed since you identified the cause and opened another issue about it.

**Comment by michael116688** [comment]
OK
