### ISSUE TITLE
How to simulate my own C Program using cva-6

### ISSUE THREAD

**Issue by Tanishqgithub** [openhwgroup/cva6#1936]
### Is there an existing CVA6 bug for this?

- [X] I have searched the existing bug issues

### Bug Description

Respected Sir 

I am a new User to CVA-6 and i am trying to run my own C program instead of hello_world.c given in the Repo 
I am facing an error while doing the above 

Is it possible to give detailed steps , where if we want to give our own C program to the simulation rather than hello_world.c

I tried to replace the hello_world.c code with other C code: Bubble Sort Code given below
[hello_world.txt](https://github.com/openhwgroup/cva6/files/14622911/hello_world.txt)

then i ran the Smoke test and the iss_regr.log file is as follows : 
[iss_regr.txt](https://github.com/openhwgroup/cva6/files/14622919/iss_regr.txt)

and finally i used the commands to run the hello_world.c file which is given in readme i,e this :
https://github.com/openhwgroup/cva6?tab=readme-ov-file#running-standalone-simulations

And the output in the command prompt i got is :
<img width="925" alt="command_prompt_output" src="https://github.com/openhwgroup/cva6/assets/108278729/304f7ad5-a080-4b74-8dc6-62b1d9f76369">

and the log file for hello_world[note which is updated C code one] is :
[hello_world_log_iss.txt](https://github.com/openhwgroup/cva6/files/14622929/hello_world_log_iss.txt)

Please help me out in this matter

**Comment by yunhaigushu** [comment]
hello,Tanishqgithub.I try to simulate your C program,and i meet the same problem.But when i delete the '\n' in the function printf,the program run successfully.Hope my try can help you.
