### ISSUE TITLE
[BUG] Fails to Trigger Illegal Instruction Exception for some illegal Instructions

### ISSUE THREAD

**Issue by youzi27** [openhwgroup/cva6#1967]
### Is there an existing CVA6 bug for this?

- [X] I have searched the existing bug issues

### Bug Description

**Describe the bug:**
The CVA6 does not trigger an illegal instruction exception when encountering the illegal instruction like `'0x5162e55b'`. This issue is reminiscent of the previously reported issue #1953 . Despite switching to a newer version of the core (commit: f73724b7e2cc6752d543b8ddaf61f66a9eb50042), the problem persists for certain instructions, including `‘0x5162e55b’`. In addition, there are the instructions mentioned in issue #1966.

**Expected behavior:**
Upon encountering an illegal instruction, such as ‘0x5162e55b’, the CVA6 core is expected to trigger an illegal instruction exception. 

**The log is as follows**
```
core   0: 0x0000000080002020 (0x5162e55b) unknown
```

**Comment by JeanRochCoulon** [comment]
Thnak you for this feedback. If I understand this bug was already detected and reported in #1953 and #1966, why to create a new GitHub issue. Do I misunderstand ?

**Comment by JeanRochCoulon** [comment]
I like getting feedbacks on CVA6 implementation, so let's go on with your work and contributions.
When a github issue is open, it means that it is not fixed. When someone fixes it, we close the Github issue.
That is why I would ask you to comment the existing Github issues (is needed), and close the current one. Thanks !

**Comment by youzi27** [comment]
Thank you for your encouraging response. I appreciate the clarity regarding the Github issue management process and will follow your guidance by commenting on the existing issues as needed and closing the current one. Thanks again for your support!😊
