### ISSUE TITLE
[BUG] MIE Supervisor Bits not RO if S is not present

### ISSUE THREAD

**Issue by MarioOpenHWGroup** [openhwgroup/cva6#2004]
### Is there an existing CVA6 bug for this?

- [X] I have searched the existing bug issues

### Bug Description

The MIE fields `SSIE`, `STIE`, `SEIE` are not being disabled when supervisor is not enabled.

Hash: 5920e3d12596347e1796ef22e80e3c533182869f
Test: `csr_test.S`

**Comment by JeanRochCoulon** [comment]
Bug is in RTL or Spike side ?

**Comment by JeanRochCoulon** [comment]
RTL !

**Comment by JeanRochCoulon** [comment]
I think (I hope) the issue has been closed by #2017. @MarioOpenHWGroup you can close if agree.
