### ISSUE TITLE
Use only cva6_cfg parametrization structure

### ISSUE THREAD

**Issue by JeanRochCoulon** [openhwgroup/cva6#2027]
### Is there an existing CVA6 bug for this?

- [X] I have searched the existing bug issues

### Bug Description

In the UVM testbench, the following variables must point new cva6_cfg defined by parametrization and not the localparams. 

![image](https://github.com/openhwgroup/cva6/assets/56552370/b3ee4d72-a099-441c-a391-c699c7a60af5)

**Comment by AyoubJalali** [comment]
@JeanRochCoulon I think this was fixed !!

**Comment by JeanRochCoulon** [comment]
Indeed !
