### ISSUE TITLE
[AXI dv Plan]: Minor feedback

### ISSUE THREAD

**Issue by ludovicpion** [openhwgroup/cva6#2065]
### Is there an existing CVA6 bug for this?

- [X] I have searched the existing bug issues

### Bug Description

Hi,
As agreed, we (CEA) hae reviewed the AXI dv_plan. Only minor points to highlight.

Item: 013
•	XLEN is not mentioned in the specification. Do we have to understand the XLEN= AXI DATA WIDTH ?

Item: 014
In the dvPlan: ARSIZE can not be equal to 3 if ARID = 1 
but in the spec: if(RV32) ARSIZE != 3 && ARLEN = 0 && ARID = 1. 
=> So the ARLEN = 0 condition is missing in the dvplan

In the dvPlan: ARSIZE can not be equal to 0, 1 or 2 if ARLOCK = 1 
but in the spec if(RVA) AxLOCK = 1 => AxSIZE > 1. 
=> Should be 
ARSIZE can not be equal to 0 or 1 if ARLOCK = 1 (already present in the Item: 015)
ARSIZE is equal to 2 if ARLOCK = 1

Regards,
Ludovic

**Comment by JeanRochCoulon** [comment]
Thank you @ludovicpion for this feedback

**Comment by JeanRochCoulon** [comment]
@AEzzejjari   Do you confirm the feedbacks are inserted in the doc ?    If ok, the issue can be closed.

**Comment by AEzzejjari** [comment]
Yes I do
