### ISSUE TITLE
AXI UVM issue when integrating HPDCache

### ISSUE THREAD

**Issue by JeanRochCoulon** [openhwgroup/cva6#2076]
### Is there an existing CVA6 bug for this?

- [X] I have searched the existing bug issues

### Bug Description

When switching WT cache to HPD cache, 4 AXI assertions stop the simulations:
![image](https://github.com/openhwgroup/cva6/assets/56552370/f0911ce1-8a55-45c6-ad7a-4ae23c65bc21)

When commenting the 4 assertions, the hello word test stops on timeout after 300s. When switching the AXI from active to passive, the test passes.

This failure is using vcs-uvm target.
The Thales developing branch is hpdcache0

**Comment by cfuguet** [comment]
Hello,

Thank you for the report.

Can you please send the command line to rerun your test ?

When I debugged one of the ADD assembly tests, I saw that the problem came effectively for a write, but what I saw, is that the HPDcache sent both the address (AW) and the data (W) but it never received a response for it (B). So, in my case it looks more like a problem from the test environment.

**Comment by AEzzejjari** [comment]
When I reviewed the log file, I didn't notice that the agent didn't sent response, but when you mentioned it, I observed the waveform and I realized that when the address is accepted by the agent after the data, the agent does not send a response. Therefore, this is a bug in the agent.

**Comment by cfuguet** [comment]
Ok, yes, that was what I observed too. Let me know if I can help.

**Comment by cfuguet** [comment]
Hi @AEzzejjari,

Do you have any news on this issue ? :)

Thanks and regards

**Comment by JeanRochCoulon** [comment]
I think @AEzzejjari is oOo Today.
Alae has fixed the AXI agent.
I am (trying) to bump core-v-verif to CVA6... Not sure to succeed soon, because two PRs are in collision.

**Comment by cfuguet** [comment]
Ok great ! No problem, I'm glad that you have found some issues.

**Comment by JeanRochCoulon** [comment]
fixed by #2125
