### ISSUE TITLE
[BUG] <smoke-tests.sh fails to build Spike>

### ISSUE THREAD

**Issue by ibooga** [openhwgroup/cva6#2090]
### Is there an existing CVA6 bug for this?

- [X] I have searched the existing bug issues

### Bug Description

Upon reaching step 6 of the quick setup instructions after entering:
export DV_SIMULATORS=veri-testharness,spike
bash verif/regress/smoke-tests.sh

I am told that Spike did not install due to missing makefiles.

Attached you will find the output of the failed installation.
[smoke-test_failure_spike.txt](https://github.com/openhwgroup/cva6/files/15172672/smoke-test_failure_spike.txt)

**Comment by ibooga** [comment]
Spike failing due to missing file
![Screenshot from 2024-04-30 19-16-28](https://github.com/openhwgroup/cva6/assets/1752488/54baa767-52ac-439f-9be4-565694b2b46f)

**Comment by ibooga** [comment]
It seems like within
g++ -MMD -MP  -DPREFIX=\"/home/cai/cache_project/cva6/tools/spike\" -Wall -Wno-unused -Wno-nonportable-include-path -g -O2 -fPIC -DSPIKE_HASH_VERSION=0xdeb75451 -g -O2 -DPREFIX=\"/home/cai/cache_project/cva6/tools/spike\" -Wall -Wno-unused -Wno-nonportable-include-path -g -O2 -fPIC -DSPIKE_HASH_VERSION=0xdeb75451 -std=c++17 -g -O2   -I. -I.. -I../fesvr -I../riscv -I../disasm -I../customext -I../fdt -I../softfloat -I../spike_main -I../spike_dasm -I/include -I//include -I/include -I/share/verilator/include/vltstd/ -I/usr/include   -c ../fesvr/fesvr_dpi.cc

That

-I/share/verilator/include/vltstd/

Is attempting to direct the compiler to where svdpi.h lives but is doing so unsuccessfully.

**Comment by ibooga** [comment]
Started from scratch and Spike seems to build properly.

**Comment by cllll402** [comment]
Can I get in touch with you more?  VX：aaaslla
