### ISSUE TITLE
Error in gcc-toolchain-builder build

### ISSUE THREAD

**Issue by cllll402** [openhwgroup/cva6#2091]
### Is there an existing CVA6 bug for this?

- [X] I have searched the existing bug issues

### Bug Description

I encountered a difficulty when building the gcc compiler toolchain, and I don't know how to solve it, can you help me?

I pre-installed the installation package required by the project, set the RISCV path, and obtained the source code of the tool chain.
![图片1](https://github.com/openhwgroup/cva6/assets/64417143/31f7ff74-21dd-47f4-bbb6-14a67e0a2bf7)
![图片2](https://github.com/openhwgroup/cva6/assets/64417143/b3e50fc8-6c43-49d7-8449-328d9b212545)
![图片3](https://github.com/openhwgroup/cva6/assets/64417143/527ec62e-2b4e-446d-b4ae-1bef4ea73384)

But when I used the following command, I was told that the command format was wrong, so I used  sh build-toolchain.sh  gcc-13.1.0-baremetal $INSTALL_DIR command to build with the following error message:
![image](https://github.com/openhwgroup/cva6/assets/64417143/7e8b1e79-50c7-4421-8e74-0212adb5244f)

g++ -std=gnu++11 -c   -O2     -DIN_GCC  -DCROSS_DIRECTORY_STRUCTURE   -fno-exceptions -fno-rtti -fasynchronous-unwind-tables -W -Wall -Wno-narrowing -Wwrite-strings -Wcast-qual -Wmissing-format-attribute -Woverloaded-virtual -pedantic -Wno-long-long -Wno-variadic-macros -Wno-overlength-strings   -DHAVE_CONFIG_H  -DGENERATOR_FILE -I. -Ibuild -I../../../src/gcc/gcc -I../../../src/gcc/gcc/build -I../../../src/gcc/gcc/../include  -I../../../src/gcc/gcc/../libcpp/include  \
	-o build/genrvv-type-indexer.o ../../../src/gcc/gcc/config/riscv/genrvv-type-indexer.cc
../../../src/gcc/gcc/config/riscv/genrvv-type-indexer.cc: In function ‘std::string same_ratio_eew_type(unsigned int, int, unsigned int, bool, bool)’:
../../../src/gcc/gcc/config/riscv/genrvv-type-indexer.cc:118:30: error: ‘log2’ is not a member of ‘std’
     elmul_log2 = lmul_log2 - std::log2 (sew / eew);
                              ^
../../../src/gcc/gcc/config/riscv/genrvv-type-indexer.cc:118:30: note: suggested alternative:
In file included from /usr/include/features.h:375:0,
                 from /usr/include/stdio.h:27,
                 from ../../../src/gcc/gcc/system.h:46,
                 from ../../../src/gcc/gcc/config/riscv/genrvv-type-indexer.cc:18:
/usr/include/bits/mathcalls.h:145:1: note:   ‘log2’
 __MATHCALL (log2,, (_Mdouble_ __x));
 ^
../../../src/gcc/gcc/config/riscv/genrvv-type-indexer.cc:120:30: error: ‘log2’ is not a member of ‘std’
     elmul_log2 = lmul_log2 + std::log2 (eew / sew);
                              ^
../../../src/gcc/gcc/config/riscv/genrvv-type-indexer.cc:120:30: note: suggested alternative:
In file included from /usr/include/features.h:375:0,
                 from /usr/include/stdio.h:27,
                 from ../../../src/gcc/gcc/system.h:46,
                 from ../../../src/gcc/gcc/config/riscv/genrvv-type-indexer.cc:18:
/usr/include/bits/mathcalls.h:145:1: note:   ‘log2’
 __MATHCALL (log2,, (_Mdouble_ __x));
 ^
make[2]: *** [build/genrvv-type-indexer.o] Error 1
make[2]: Leaving directory `/home/autumn/cva6/util/gcc-toolchain-builder/build/gcc/gcc'
make[1]: *** [all-gcc] Error 2
make[1]: Leaving directory `/home/autumn/cva6/util/gcc-toolchain-builder/build/gcc'
make: *** [all] Error 2
*** Could not build GCC (even after removing target dirs), bailing out!

Environment: centos7

**Comment by JeanRochCoulon** [comment]
Hello,
Reading your log, it seems the INSTALL_DIR is not setup. Before executing "sh build-toolchain.sh $INSTALL_DIR" can you "echo $INSTALL_DIR" ?

**Comment by cllll402** [comment]
Thank you so much for answering my question.

![image](https://github.com/openhwgroup/cva6/assets/64417143/10b71624-0750-4da8-81e0-e05e05f95bae)

I have set the paths to $RISCV and $INSTALL_DIR in my bashrc. Aside from this problem, are there any other factors that might cause a build to fail?

**Comment by cllll402** [comment]
No error occurs after the INSTALL_DIR directory is specified as the cva6 peer directory and the centos gcc version 4.85 is upgraded to 9.3.1
