### ISSUE TITLE
[BUG] Unexpected Result When fsqrt.s Processes Negative Floating-Point Numbers

### ISSUE THREAD

**Issue by fly-1011** [openhwgroup/cva6#2100]
### Is there an existing CVA6 bug for this?

- [x] I have searched the existing bug issues

### Bug Description

When the `fsqrt.s` instruction is executed on a negative double-precision floating-point number, the resulting output differs from that of Spike. Spike returns `0x7fc00000`, which represents a NaN value.

**How to reproduce and the logs are as follows:**
**Example:**
Initialize `ft0` with `0xC08140003F800000` (a negative double-precision floating-point value) and execute `fsqrt.s ft2, ft0` .

Spike results are:  `ft2= 0x7fc00000`
CVA6 results are:  `ft2= 0x3f800000`

**Comment by JeanRochCoulon** [comment]
Same commen than #2102. Please close this issue after migration to cvfpu project.
