### ISSUE TITLE
Simulation Results of Dhrystone

### ISSUE THREAD

**Issue by GeorgeWu1204** [openhwgroup/cva6#2103]
Hi, when I tried to simulate cva6 on the dhrystone benchmark. I got a similar problem as the #1837. May I ask if I want to obtain the simulation results of the Dhrystone benchmark, where can I find the simulation results like the provided sample?

"Microseconds for one run through Dhrystone: 392
Dhrystones per Second:                      2550
mcycle = 196024
minstret = 196029"

Thank you so much.

**Comment by JeanRochCoulon** [comment]
The display of test result is not supported by CVA6 environment so far. You can either have the will to contribute with such a feature (by implementing pk support for instance), otherwise I would ask you to close the Github issue. Thanks
