### ISSUE TITLE
There was a problem installing spike

### ISSUE THREAD

**Issue by cllll402** [openhwgroup/cva6#2106]
The following error occurs when I run this step.
![image](https://github.com/openhwgroup/cva6/assets/64417143/0b9e9d82-1c55-457d-8e07-c4a47a0ce0ca)
![image](https://github.com/openhwgroup/cva6/assets/64417143/00512400-2556-4de5-aad0-f24412ff3c07)
![image](https://github.com/openhwgroup/cva6/assets/64417143/1674dc00-f610-47fc-b5c8-dc400442179d)
![image](https://github.com/openhwgroup/cva6/assets/64417143/a4cef4ff-6344-403a-a00e-2f580895f90c)

When I look up the tools path, I find that spike doesn't exist.
![image](https://github.com/openhwgroup/cva6/assets/64417143/542962f4-4522-4186-9c92-448cc34c01f2)

So I tried to run the install-spike.sh file separately, again encountering difficulties.
![image](https://github.com/openhwgroup/cva6/assets/64417143/0f58c1fa-36ed-4250-b87d-07444a66db41)

I checked the integrity of the file in the corresponding path.
![image](https://github.com/openhwgroup/cva6/assets/64417143/09a5ab98-12ca-4267-9965-1e69e106ebc2)

What am I supposed to do now?

**Comment by JeanRochCoulon** [comment]
Can you start from the first step, that is to say by cloning the cva6 repository?

**Comment by cllll402** [comment]
Yes, I've tried that. I once again followed the instructions in step 1 to remove the project and pull the code repeatedly. I repeated the process, but there was still no spike in the /tools path.And just in case I missed something, I used cat cva6/.gitmodules to check each one.

**Comment by cllll402** [comment]
Solve the problem after repeated pull item installation.

**Comment by JeanRochCoulon** [comment]
Thanks for the feedback
