### ISSUE TITLE
Add support for PMAs

### ISSUE THREAD

**Issue by zarubaf** [openhwgroup/cva6#212]
Add support for: 

- [x] `execute` PMA on instruction port
- [x] `non-idempotent` and `non-cacheable` support on peripheral space
- [ ] `atomicity` support on main memory only.

**Comment by msfschaffner** [comment]
The NC PMAs are supported now.

**Comment by zarubaf** [comment]
Support is partially there. I don't think we have added a requirement on atomicity PMAs in the user-guide, hence it is out of scope IMHO. Feel free to re-open @jquevremont or @JeanRochCoulon.
