### ISSUE TITLE
How to get the Power consumption of CVA6

### ISSUE THREAD

**Issue by Vinay0203** [openhwgroup/cva6#2185]
### Is there an existing CVA6 bug for this?

- [X] I have searched the existing bug issues

### Bug Description

Just like the details that are displayed in the log file [hello_world.cv32a60x.log.iss] when running a C code ( number of cycles, execution time), please help me get the power consumption report as well.
Early resolving of the issue is highly appreciated.

**Comment by JeanRochCoulon** [comment]
The CVA6 environment does not provide the power consumption. Any contribution is welcomed on this topic.

**Comment by JeanRochCoulon** [comment]
No updates... Re-open it if needed !
