### ISSUE TITLE
New LINT error introduced by #2178

### ISSUE THREAD

**Issue by JeanRochCoulon** [openhwgroup/cva6#2189]
![image](https://github.com/openhwgroup/cva6/assets/56552370/083b045a-666d-4225-9f6b-a7cbc084c200)

**Comment by JeanRochCoulon** [comment]
@Asmaa-Kassimi   Do you confirm this github issue can be closed ?

**Comment by Asmaa-Kassimi** [comment]
yes, the error has been resolved!
