### ISSUE TITLE
CSR spec improvements

### ISSUE THREAD

**Issue by JeanRochCoulon** [openhwgroup/cva6#2191]
Feedback on the CSR specification https://github.com/openhwgroup/cva6/blob/master/config/gen_from_riscv_config/cv32a65x/csr/csr.rst 
- Replace the WARL with only one value by ROCST (RO constant). Will be done in input specification @zchamski.
- Use ROVAR (RO variable) when a RO value can be modified by hardware. Need for the tests. 
- Before the register Summary, remind the definition of WARL, WLRL, WPRI, ROCST, ROVAR. Will be done by @zchamski.
- In Register Summary, add a column in the table to provide the access type : RW/RO
- In Register Description, add the access type before the table : RW/RO
![image](https://github.com/openhwgroup/cva6/assets/56552370/d24e3df5-047b-41fb-93b6-25c2b8d51712)

- Move the "Legal Values" column between "Type" and "Description" columns
- Replace "RESERVED" from Description column by "_Reserved_". See Table 10 in priv specification.
- In MISA, can you expand the EXTENSIONS field ?

**Comment by AnouarZajni** [comment]
@JeanRochCoulon , I think you are referring to https://github.com/openhwgroup/cva6/blob/master/config/gen_from_riscv_config/cv32a65x/csr/csr.rst ?

**Comment by JeanRochCoulon** [comment]
The above modifications has been implemented in the CSR specification. The PR can be closed.
