### ISSUE TITLE
Some confusion about using Verdi to view.vcd files

### ISSUE THREAD

**Issue by cllll402** [openhwgroup/cva6#2199]
Following the instructions, I have successfully generated the.vcd waveform file for the script smoke-tests.sh.

But when I opened the waveform file and wanted to analyze it in modules, I was confused. I don't know where to start, and there don't seem to be any guidelines in the documentation that mention this part.

Here are some of the attempts I made and the difficulties I encountered. I would appreciate it if anyone could give me some guidance.

First, I convert the.vcd file to the.fsdb file.
![image](https://github.com/openhwgroup/cva6/assets/64417143/148914e5-0133-4042-a5fe-3a2febbbc8e8)

Second, I reconfigured the Verdi command parameters and set the environment variables needed in the file Flist.cva6.
![image](https://github.com/openhwgroup/cva6/assets/64417143/676c888a-99c6-4618-bc8e-992bbcad1516)
![image](https://github.com/openhwgroup/cva6/assets/64417143/0c647ec5-b6a1-4c40-88ba-b3df8f08a004)
![image](https://github.com/openhwgroup/cva6/assets/64417143/26c61fd5-91ff-4d0e-8364-feb8ab7fbe56)

Finally, I use Verdi to open the file in the.vcd build directory.
![image](https://github.com/openhwgroup/cva6/assets/64417143/c4a5a4d5-3ca5-4f68-8a84-dbeee7aeaea9)

The error appears as follows:
![image](https://github.com/openhwgroup/cva6/assets/64417143/7ab6eb7e-48a4-4cc9-bd52-b3e77164c0ec)
![image](https://github.com/openhwgroup/cva6/assets/64417143/e41c90fb-e4a2-4bed-b38b-7ef789475344)

Is there anything else I didn't set up properly?

**Comment by JeanRochCoulon** [comment]
To use VERDI,     "export VERDI=1" before running the simulation.
Please close the issue if solved.

**Comment by cllll402** [comment]
Thank you for your answer. I enabled "export VERDI=1", but the problem still persists.

**Comment by JeanRochCoulon** [comment]
You should open verdi by executing cva6.py, is it the case on your side ?

**Comment by JeanRochCoulon** [comment]
No updates... I close the github issue, re-open it if needed.
