### ISSUE TITLE
[BUG] <title>How to verify the output of a certain c program after running on CVA6

### ISSUE THREAD

**Issue by PoojaR07** [openhwgroup/cva6#2220]
### Is there an existing CVA6 bug for this?

- [X] I have searched the existing bug issues

### Bug Description

I have referred all the previous bugs for running c programs on CVA6 and also generated the vcd files. After running a certain C program how do we verify the output and check whether its the correct output since we cannot directly print the output to the terminal.

**Comment by JeanRochCoulon** [comment]
One solution would be to support pk, which is not the case currently.
We are looking for volunteer to develop it !

**Comment by JeanRochCoulon** [comment]
As the github issue is mute for a while, I close it. Feel free to reopen another if needed.
