### ISSUE TITLE
Run make vcs to start the verdi waveform view some problems

### ISSUE THREAD

**Issue by cllll402** [openhwgroup/cva6#2245]
I run make vcs in the cva6 root directory to open verdi and view the waveform.
![image](https://github.com/openhwgroup/cva6/assets/64417143/6f035824-74d8-43f4-a7c8-33946dcb8287)
![image](https://github.com/openhwgroup/cva6/assets/64417143/bbe09c6e-82e1-4689-bdb0-4c66314a507d)

However, verdi has the following error. And when I try to use the command run 1000ns, I find that the waveform is incomplete, and only 110ns waveform is displayed. Why? Please help me.
![image](https://github.com/openhwgroup/cva6/assets/64417143/68e16531-d602-490b-94cb-2224749f5de5)
![image](https://github.com/openhwgroup/cva6/assets/64417143/f5e0a329-9024-4ad2-a21e-7eafb4c8b780)
![image](https://github.com/openhwgroup/cva6/assets/64417143/2f741f25-9502-4283-aba2-b7f0534195c9)

So I looked up the historical questions in the forum. Try to solve the problem. Follow #570  to the last step, but it seems to be the same problem: an invalid address for tohost. The trace log runs endlessly until it times out. So what am I supposed to do?
![image](https://github.com/openhwgroup/cva6/assets/64417143/5fa513f9-7340-44bb-9ada-c8c7e2ab0157)

**Comment by cllll402** [comment]
Considering that the DPI library was not recognized, I modified the command in the makefile to call it unconditionally.
![image](https://github.com/openhwgroup/cva6/assets/64417143/baa824d1-1f20-4b74-b5d0-aea2408a1360)

**Comment by JeanRochCoulon** [comment]
"make vcs" is not supported, please read the README.md to run a simulation with cva6.py
export VERDI=1 allows to activate the gui.
The issue can be closed

**Comment by cllll402** [comment]
Okay, thank you.
