### ISSUE TITLE
[BUG] Design doc generation: custom CSRs are missing in the CV32A65X documentation

### ISSUE THREAD

**Issue by zchamski** [openhwgroup/cva6#2268]
### Is there an existing CVA6 bug for this?

- [X] I have searched the existing bug issues

### Bug Description

The riscv-config specification of CV32A65X contains the description of CSRs `ICACHE` and `DCACHE`, but these registers are not rendered in the design documentation based on `riscv-config`.

The corresponding `riscv-config` output is located in file [config/riscv-config/cv32a65x/generated/custom_gen.yaml](https://github.com/openhwgroup/cva6/blob/master/config/riscv-config/cv32a65x/generated/custom_gen.yaml).

**Comment by JeanRochCoulon** [comment]
@AbdessamiiOukalrazqou, I suppose this task could be completed by you ?   I assign it to you, feel free to re-assign if needed

**Comment by AbdessamiiOukalrazqou** [comment]
@JeanRochCoulon ,@zchamski  it is under treatment
