### ISSUE TITLE
Page not found for "build prerequisites" and "the toolchain itself" in README

### ISSUE THREAD

**Issue by Tanishqgithub** [openhwgroup/cva6#2328]
I tried to access the link here in both : 
![image](https://github.com/openhwgroup/cva6/assets/108278729/a5b5621d-46c5-4596-b25f-260ac8193ecb)

But both are not accessible , is it only form me or is some development going on in background 

1. For "build prerequisites" page in link [build prerequisites](https://github.com/openhwgroup/cva6/blob/master/util/gcc-toolchain-builder/README.md#Prerequisites) 
![image](https://github.com/openhwgroup/cva6/assets/108278729/cab2c931-09ab-479f-9f97-b20c538dfa26)

2. For "the toolchain itself" page in link [the toolchain itself](https://github.com/openhwgroup/cva6/blob/master/util/gcc-toolchain-builder/README.md#Getting-started)
![image](https://github.com/openhwgroup/cva6/assets/108278729/189e9baa-282b-4d49-b9b8-a563d3bc4fdc)

**Comment by valentinThomazic** [comment]
I think this is due to https://github.com/openhwgroup/cva6/pull/2320 @math-gout

**Comment by JeanRochCoulon** [comment]
Fixed by #2332
