### ISSUE TITLE
Error while building the toolchain

### ISSUE THREAD

**Issue by Syedateeb24** [openhwgroup/cva6#2333]
After running the prerequisites command, while trying to build the toolchain i.e when running the following command 
"sh get-toolchain.sh gcc-13.1.0-baremetal" , i am receiving the following error :
![WhatsApp Image 2024-07-07 at 12 01 38_5cc94f3f](https://github.com/openhwgroup/cva6/assets/157878708/36f364b7-0e9a-49f3-bd16-53f7e240c2e4)

Please help me fix this !

**Comment by teobiton** [comment]
Have you tried running `bash get-toolchain.sh gcc-13.1.0-baremetal` instead of `sh` ?

**Comment by G3voman** [comment]
It works, thanks

**Comment by valentinThomazic** [comment]
@math-gout

**Comment by G3voman** [comment]
Thu, 11 Jul 2024 17:07:22 INFO     GCC Version: 13.1.0
Thu, 11 Jul 2024 17:07:23 ERROR    Please clean up Spike by executing: rm -r tools/spike verif/core-v-verif/vendor/riscv/riscv-isa-sim/build
Thu, 11 Jul 2024 17:07:23 ERROR    You are currently using version - unknown - of Spike, should be: 1.1.1-dev 66cd091b. Please install or reinstall it with the installation script.
