### ISSUE TITLE
[BUG] Violation of PMA : Unauthorized  Access to Vacant Memory Region

### ISSUE THREAD

**Issue by abdelhak-chkirid** [openhwgroup/cva6#2370]
### Is there an existing CVA6 bug for this?

- [X] I have searched the existing bug issues

### Bug Description

Access to vacant regions (e.g., the address 0xc0000100) is allowed for read and write operations with no exceptions appearing.
Addresses within the vacant region should not be accessible. All read/write operations should  result in an exception.

**Comment by JeanRochCoulon** [comment]
@abdelhak-chkirid   The riscv specification for 65x has been updated. Consider it: https://docs.openhwgroup.org/projects/cva6-user-manual/04_cv32a65x/riscv/priv.html#pma 
![image](https://github.com/user-attachments/assets/c6d69751-7afd-44e9-9e0e-c79928f42d57)
We simplified the specification by not supporting PMA inside CVA6.
To me, this Github issue can be close.

**Comment by JeanRochCoulon** [comment]
@abdelhak-chkirid   Can we close this issue ?

**Comment by abdelhak-chkirid** [comment]
yes , of course
