### ISSUE TITLE
[EXPLANATION PLEASE]<A way to switch execution modes>

### ISSUE THREAD

**Issue by ibooga** [openhwgroup/cva6#2421]
### Is there an existing CVA6 task for this?

- [X] I have searched the existing task issues

### Task Description

When running hello_world.c every instruction is executed in machine mode (priv_lvl = 3).

I would like to be able to switch the execution mode to something else (U or S) during simulation.

Is such a thing possible? Is it necessary to run linux on a cva6 flashed fpga to change execution modes?

### Required Changes

See task

### Current Status

N/A

### Description of Done

See Task

**Comment by niwis** [comment]
Hello @ibooga, privilege levels can be changed by using the `ECALL` and `xRET` instructions. See the [RISC-V Privileged Spec](https://github.com/riscv/riscv-isa-manual/releases/download/20240411/priv-isa-asciidoc.pdf) for more information.

**Comment by ibooga** [comment]
Thank you, @niwis

**Comment by ibooga** [comment]
Within the cva6 project are testbenches that switch Ariane's execution mode.

A good example is `/cva6/verif/tests/custom/sv32/vm_rwx_access_smode_01.S`
which uses the macros defined in /cva6/verif/tests/custom/sv32/macros.h and (I think?) cva6/tools/spike/include/riscv/encoding.h
/home/cai/cache_project/
The macros, ALL_MEM_PMP, CHANGE_T0_S_MODE, CHANGE_T0_U_MODE and INCREMENT_MEPC, 
are very helpful for changing execution modes. Yes, dear reader, that is a zero in ...T0_S_MODE and ...T0_U_MODE

vm_rwx_access_smode_01.S includes an example of how to modify the CSR registers using MSTATUS_MPP as well.
