### ISSUE TITLE
Issue regarding synthesis of cva6 using synopsys

### ISSUE THREAD

**Issue by Vinay0203** [openhwgroup/cva6#2447]
### Is there an existing CVA6 bug for this?

- [X] I have searched the existing bug issues

### Bug Description

I have noticed that you have mentioned about the synthesis of cva6 using synopsys in #2319 . I humbly request you to share the steps to perform the synthesis of cva6. I am sincerely interested in performing the synthesis of cva6 and I request you to help me with the steps to do so or the approach to be followed.
Thanks

**Comment by hhhsiang** [comment]
hi @Vinay0203 , do you successfully perform the synthesis of cva6?
