### ISSUE TITLE
How to Implement and Use a Custom Instruction in CVA6

### ISSUE THREAD

**Issue by mrbilandi** [openhwgroup/cva6#2499]
Hi

I want to implement a new instruction, but I can't find a clear explanation of how to do it. Is there any guide on how to add a custom instruction to the toolchain (I'm not sure where) and how to build our program with the new compiler?

The CVA6 already has an example coprocessor with the instruction "adds rs1, rs2(, rs3)." If I want to use this instruction in my code, how can I do that and how can I compile the code containing this instruction?

**Comment by Gchauvon** [comment]
Hello,

[verif/regress/cvxif_verif_regression.sh](https://github.com/openhwgroup/cva6/blob/master/verif/regress/cvxif_verif_regression.sh) and [verif/tests/testlist_cvxif.yaml](https://github.com/openhwgroup/cva6/blob/master/verif/tests/testlist_cvxif.yaml) will guide you on how to compile and run a test with custom instructions. Most of those defined in the example coprocessor are defined in software in [cvxif_macros.h](https://github.com/openhwgroup/cva6/blob/master/verif/tests/custom/cv_xif/cvxif_macros.h)
