### ISSUE TITLE
Torture tests are unstable in Travis and Gitlab CI

### ISSUE THREAD

**Issue by msfschaffner** [openhwgroup/cva6#251]
The torture tests do not seem to work well in CI. It is unclear whether this is a CI problem, or whether this is related to a bug in the core, hence more investigation is needed. For the time being, torture has been disabled in the CI. See also #248.

**Comment by stmach** [comment]
FYI, torture will fail (sooner or later) when patterns in the `fdiv` group are enabled due to the arithmetic bugs mentioned in #242

**Comment by MikeOpenHWGroup** [comment]
Hi @msfschaffner and @zarubaf.  This issue is truly ancient. Is it still valid?

**Comment by zarubaf** [comment]
Torture tests are not valid anymore. We are using `core-v-verif` for randomization.
