### ISSUE TITLE
CVXIF : commit_valid asserted more than 1 clk cycle

### ISSUE THREAD

**Issue by AyoubJalali** [openhwgroup/cva6#2630]
### Is there an existing CVA6 bug for this?

- [X] I have searched the existing bug issues

### Bug Description

Recording to the [CVXIF spec](https://github.com/openhwgroup/core-v-xif/blob/main/docs/source/x_ext.rst), the commit_valid should be asserted for only 1 clk cycle exactly

![image](https://github.com/user-attachments/assets/82372ea0-79da-4883-a0dc-9d050c9081cf)

this is not the case in the CVA6 as shown in the waveform : 

![image](https://github.com/user-attachments/assets/13fff72e-95f5-48c6-bdda-be298f97ae4a)

**Comment by fatimasaleem** [comment]
When back-to-back instructions are being committed then it is possible to have commit_valid being set for multiple cycles.

**Comment by AyoubJalali** [comment]
> When back-to-back instructions are being committed then it is possible to have commit_valid being set for multiple cycles.

In this case the commit_valid asserted more than one for the same ID

**Comment by AyoubJalali** [comment]
Also the spec doesn't mention ID related for commit_valid, I think we should create an issue for clarify the spec

**Comment by AyoubJalali** [comment]
@JeanRochCoulon @MikeOpenHWGroup what do you think ?

**Comment by AyoubJalali** [comment]
> When back-to-back instructions are being committed then it is possible to have commit_valid being set for multiple cycles.

![image](https://github.com/user-attachments/assets/c59ef08a-2678-4f2b-89f9-fd0b1c649424)

**Comment by fatimasaleem** [comment]
> > When back-to-back instructions are being committed then it is possible to have commit_valid being set for multiple cycles.
> 
> ![image](https://private-user-images.githubusercontent.com/110232072/389915780-c59ef08a-2678-4f2b-89f9-fd0b1c649424.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2MjQ0MjIsIm5iZiI6MTczMjYyNDEyMiwicGF0aCI6Ii8xMTAyMzIwNzIvMzg5OTE1NzgwLWM1OWVmMDhhLTI2NzgtNGYyYi04OWY5LWZkMGIxYzY0OTQyNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNlQxMjI4NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xODI5NmQ1MDQyYzg1YTViMTRkNWRkYjEwOWI0MjM2ZTdkNWJkZjc1MjA3ZTQzZTQyMTI1N2FkYjE4Y2UyMjM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.sHdwvrbYF2vbyWQhifoVUwuMkInJDQJ5U0apJkRVr44)

I see that commit_id 1 is missing. I think that is the issue. The issue is not causing any bug currently because we really don't use the trans_id in commit stage for anything.

**Comment by AyoubJalali** [comment]
> I see that commit_id 1 is missing. I think that is the issue. The issue is not causing any bug currently because we really don't use the trans_id in commit stage for anything.

your right, that's another issue because the CVA6 wait the agent ready signals to send response

**Comment by AyoubJalali** [comment]
and for commit_valid being set for multiple cycle for different IDs,  this is not be clear in the Spec.

**Comment by AyoubJalali** [comment]
Fixed by #2678
