### ISSUE TITLE
could not initializing SD

### ISSUE THREAD

**Issue by shirlynan** [openhwgroup/cva6#406]
Hello,
I am trying to boot linux on Ariane SoC on VCU118 but got the following terminal outputs:
However I got the terminal outputs:
Hello World!
init SPI
status: 0x0000000000000025
status: 0x0000000000000025
SPI initialized!
could not initialize sd... exiting

Whern I followed the 'Booting from SD card' steps from ariane-sdk to prepare my sd card I got the warning: Invalid partition data!
Information: Creating fresh partition table; will override earlier problems!
Warning! Mismatched GPT and MBR partition! MBR partition 1, of type 0x0C,
has no corresponding GPT partition! You may continue, but this condition
might cause data loss in the future!
The operation has completed successfully.

I wonder if i used a wrong card? What I used is SanDisk microSD 15G. Must I use 32GB SD card to apply the command sudo sgdisk --clear --new=1:2048:67583 --new=2 --typecode=1:3000 --typecode=2:8300 /dev/sdb for it?

**Comment by zarubaf** [comment]
I think the SPI master has problems communicating with the SD card. Seems to be a board problem (maybe timing violations on the VCU118). I remember that the PMOD SD card module was very brittle timing-wise.

**Comment by MikeOpenHWGroup** [comment]
Thanks for your interest in CVA6 @shirlynan!

This issue has not been updated for almost three years, so I will close it.  If you are still having problems, either re-open it (with additional information) or create a new issue.
