### ISSUE TITLE
The HW platform change

### ISSUE THREAD

**Issue by Yi1101** [openhwgroup/cva6#449]
Dear Author,
It seemed that the screen change into[ openhwgroup/cva6](url) the day before yesterday. Will this change have an effect on the Issues？ Dr. Florian Zaruba, he is really professional, experienced, nice, patient and gentle. What is more, he know how to reply the issue accurately. So will he continue to take charge of the platform ? If not, We will rather miss him...Anyway, hope everything is fine and stay healthy!

**Comment by zarubaf** [comment]
I will still try to help as much as I can, eventually, the core will hopefully be fully maintained by the OpenHW group.
