### ISSUE TITLE
What will happen when "request goes to I/O space" in wt_cache_subsystem?

### ISSUE THREAD

**Issue by whutddk** [openhwgroup/cva6#452]
Hello, I have reviewed the code in wt_cache_subsystem.
It seems that the cache will be bypassed when the cache is not enable or the request goes to I/O space.
>> // noncacheable if request goes to I/O space, or if cache is disabled

>>>assign paddr_is_nc = (~cache_en_q) | (~ariane_pkg::is_inside_cacheable_regions(ArianeCfg, {{64-ICACHE_TAG_WIDTH{1'b0}}, cl_tag_d, {ICACHE_INDEX_WIDTH{1'b0}}}));

But when produce in FSM, it seems that only *cache_en_q* was used. 
>>>end else if ((|cl_hit && cache_en_q) || areq_i.fetch_exception.valid) begin

So when the request goes to I/O space, how does the cache work？

**Comment by zarubaf** [comment]
If the cache is not enabled or the address is non-cacheable ("it goes to I/O space") the request will not be allocated in the cache.
