### ISSUE TITLE
where is the online documentation?

### ISSUE THREAD

**Issue by bp-ouhaha** [openhwgroup/cva6#457]
Hi all,

I've been looking for the online documentation of CVA6 core. Can't find it. I was hoping to find something nice like lowRISC/ibex core, with the protocols and integration example.

I've looked into docs folder, but that seems to be source-file you have to compile/build yourself.

Thanks in advance.

**Comment by zarubaf** [comment]
I think the original (outdated) online documentation got lost in the transition of the core.  Documentation will be added (similar to Ibex) in the very near-term future.

**Comment by whutddk** [comment]
@bp-ouhaha 

Hi, I'm searching for the docs, too. And I found that the source files of documentation were in 

> docs/_docs/arch

The graphs were in 

 > docs/img

Hopes it useful for you.
