### ISSUE TITLE
A quick question about the XFVEC in Ariane

### ISSUE THREAD

**Issue by zhaoxiahust** [openhwgroup/cva6#465]
Hi guys,

  In ariane, XFVEC represents whether the vectorial float extension (Xfvec) is enabled or not.  What's the relation between XFVEC and riscv vector instruction?

  In the decoder unit, it seems to me that the vectorial float extension is identified by using the "OpcodeOp" operation which actually represents an integer instruction. However, based on the riscv vector document, the vector instruction has the same opcode with the floating-point instructions. Any comments about this?

Many thanks
Xia

**Comment by zarubaf** [comment]
Xfvec is a custom vector instruction providing smaller (16 and 8 bit) SIMD-style vectors. It has nothing to do with the "official" vector extension. Hope that helps. Free feel to re-open.
