### ISSUE TITLE
Question regarding custom extensions

### ISSUE THREAD

**Issue by zzhu35** [openhwgroup/cva6#484]
According to the ISA listing in Table 24.1 of RISCV ISA Version 20191213, Page 129,
There are 4 opcodes for custom ISA extension, namely:
0001011
0101011
1011011
1111011
My question is: 
1) Are you using these custom opcodes for some Ariane specific functionailties? Or are there plans to do so? If I want to extend Ariane for my research work, would it be safe to use these opcodes?
2) Are you implementing the Compressed extension? Or are there plans? Is it safe to extend onto the 00-10 compression prefixes?

Thank you!

Zeran Zhu
University of Illinois Urbana-Champaign, USA

**Comment by zarubaf** [comment]
The opcodes for custom ISA extension are reserved for your usage and should not technically be used. There are currently no plans to use them from our side. The compressed extension is implemented, the opcode which is reserved by RISC-V is free as well.
