### ISSUE TITLE
verilator: Arbitrary limitation on binary size

### ISSUE THREAD

**Issue by zarubaf** [openhwgroup/cva6#508]
Currently, for the Verilator simulation, there is an arbitrary limit on the binary size imposed here:
https://github.com/openhwgroup/cva6/blob/8678fedda2d7f49784cc59eaccc3466776a98bdf/tb/ariane_tb.cpp#L322

The most elegant solution would be to load the entire binary size, probably one would need to modify the elf parser a bit to get the relevant information.

**Comment by MikeOpenHWGroup** [comment]
Hi @zarubaf, this issue is more than 2.5 years old.  Are we going to do anything about it?

**Comment by zarubaf** [comment]
I don't think we will fix this. Probably a better environment wouldn't hurt here. I don't see value in keeping this issue.
