### ISSUE TITLE
Can we Run RTOS?

### ISSUE THREAD

**Issue by suhasskrishanmurthy** [openhwgroup/cva6#546]
Hi,
    I am trying to run Freertos on ariane.
   I have two tasks task1 and task2, task1 will print something and enters block state there by giving time for task2 to print something and control goes back to task1 and process continues.
  while running on questa task1 will print and give control to task2 and then task2 will print but control is not going back to task1.
 I have ran the same elf on SPIKE and its working fine.
Why this is happening any idea?
Thanks in advance.

**Comment by zarubaf** [comment]
So Ariane has all the privileged specification implemented, the most of it you won't even need as far as I remember FreeRTOS. Unfortunately, I think with the high-level problem description I can't really help you.

**Comment by MikeOpenHWGroup** [comment]
Hi @suhasskrishanmurthy,  thanks for your interest in CVA6.  This issue has not been updated in more than two years, so I will assume it is resolved and will close this issue.  If you are still having trouble, please feel free to open another.
