### ISSUE TITLE
bootrom.bin can single alone use vivado   download ?

### ISSUE THREAD

**Issue by MrHaiCoder** [openhwgroup/cva6#552]
The DTC is modified and bootrom is planned to be burned separately to save compilation time。
Looking forward to your reply

**Comment by MikeOpenHWGroup** [comment]
Hi @MrHaiCoder, thanks for your interest in CVA6. This issue has not been updated in more than two years, so I will assume it is resolved and will close this issue. If you are still having trouble, please feel free to open another.
