### ISSUE TITLE
errors: about "make verilate DEBUG=1"

### ISSUE THREAD

**Issue by ckj119940887** [openhwgroup/cva6#553]
When I executed "make verilate DEBUG=1", I encounterd the following errors:

../tb/ariane_tb.cpp:113:10: error: ‘bool preload_aware_dtm_t::is_address_preloaded(addr_t, size_t)’ marked ‘override’, but does not override
     bool is_address_preloaded(addr_t taddr, size_t len) override { return true; }

my verilator version is : Verilator 4.008

**Comment by jatanpandya83** [comment]
I am also seeing this issue? Is this resolved? Any  suggestions will be helpful!

**Comment by Moschn** [comment]
For a quick fix, you can just remove the `override` keyword in the line mentioned in the error message.

**Comment by MikeOpenHWGroup** [comment]
Thanks for your insight @Moschn .

Hi @ckj119940887 , thanks for your interest in CVA6. This issue has not been updated in more than a year, so I will assume it is resolved and will close this issue. Note that I typically run using Verilator v4.100.

If you are still having trouble, please feel free to open another issue.
