### ISSUE TITLE
error occur during compiling verilator.h

### ISSUE THREAD

**Issue by S-Nomii** [openhwgroup/cva6#566]
Hi, I am trying to build simulation by make verilate, but it tells me that in tb/dpi/verilator.h file VerilatedVcdFile can not be derived. Then I find out the VerilatedVcdFile is a final type class in verilator include files. Can anyone tell me how it works.

**Comment by zarubaf** [comment]
It seems that somehow your Verilator installation is broken. Do you have your `$VERILATOR_ROOT` set correctly?

**Comment by TarekIbnZiad** [comment]
Hello,

I encountered the same error on ARCH linux with `verilator 4.106`. It works fine when I switched to the latest verilator from their repo. ` Verilator 4.109 devel rev v4.108-18-g5cadabeb`.

Thank you!

**Comment by zarubaf** [comment]
Just tried the same. My advice, for now, is to stick to `4.104`.

Unfortunately, ` 4.108` or `4.109` have different problems (#585). The Verilator simulation has been stable for some time but it seems that this has changed with the latest two releases.
