### ISSUE TITLE
Synthesis Constraint file

### ISSUE THREAD

**Issue by a7med7asan15** [openhwgroup/cva6#578]
Where can I find constraint file for dc synthesis?

**Comment by zarubaf** [comment]
Within CVA6 there isn't anything special to constraint (the clock of course), it is a pure single-edge triggered, synchronous design. For the system, this depends on what you want to synthesize.

**Comment by MikeOpenHWGroup** [comment]
Thanks for your insight @zarubaf.

Hi @a7med7asan15, thanks for your interest in CVA6.  This issue has not been updated in more than two years, so I will assume it is resolved and will close this issue.  If you are still having trouble, please feel free to open another.
