### ISSUE TITLE
"echo -e" in Makefile (for checkpoint_dromajo target)

### ISSUE THREAD

**Issue by pawelkudlakaldec** [openhwgroup/cva6#592]
If dash is linked by sh then *_boot.cfg and *.cfg files contain improperly -e.
See content of generated files:
**-e** {
    "version":1,
    "machine":"riscv64",
    "memory_size":256,
    "bios":"/home/tester/RISCV/dromajo_ci/cva6/tb/dromajo/run/checkpoints/rv64ud-p-fadd/rv64ud-p-fadd",
    "memory_base_addr":0x80000000,
    "missing_csrs": [0x323, 0x324, 0x325, 0x326, //mhpmevent csrs
                     0x327, 0x328, 0x329, 0x32a,
                     0x32b, 0x32c, 0x32d, 0x32e,
                     0x32f, 0x330, 0x331, 0x332,
                     0x333, 0x334, 0x335, 0x336,
                     0x337, 0x338, 0x339, 0x33a,
                     0x33b, 0x33c, 0x33d, 0x33e,
                     0x33f,
                     0x3a0, 0x3a1, 0x3a2, 0x3a3, //pmp csrs
                     0x3b0, 0x3b1, 0x3b2, 0x3b3,
                     0x3b4, 0x3b5, 0x3b6, 0x3b7,
                     0x3b8, 0x3b9, 0x3ba, 0x3bb,
                     0x3bc, 0x3bd, 0x3be, 0x3bf,
                     0x320], //mcountinhibit
    "maxinsns": 100,
        "clint_base_addr": 0x02000000,
  "clint_size": 0xC0000,
  "plic_base_addr": 0x0C000000,
  "plic_size": 0x3FFFFFF,
  "uart_base_addr": 0x10000000,
  "uart_size": 0x1000
  }

**-e** {
    "version":1,
    "machine":"riscv64",
    "memory_size":256,
    "bios":"/home/tester/RISCV/dromajo_ci/cva6/tb/dromajo/run/checkpoints/rv64ud-p-fadd/rv64ud-p-fadd",
    "load":"/home/tester/RISCV/dromajo_ci/cva6/tb/dromajo/run/checkpoints/rv64ud-p-fadd/rv64ud-p-fadd",
    "skip_commit": [0x73, 0x9002, 0x100073],
    "memory_base_addr":0x80000000,
        "clint_base_addr": 0x02000000,
  "clint_size": 0xC0000,
  "plic_base_addr": 0x0C000000,
  "plic_size": 0x3FFFFFF,
  "uart_base_addr": 0x10000000,
  "uart_size": 0x1000
  }

**Comment by MikeOpenHWGroup** [comment]
Hi @pawelkudlakaldec, thanks for your interest in CVA6.  This issue has not been updated in more than two years, so I will assume it is resolved and will close this issue.  If you are still having trouble, please feel free to open another.
