### ISSUE TITLE
running Ariane core with 32bit elf

### ISSUE THREAD

**Issue by jatanpandya83** [openhwgroup/cva6#617]
If I want to run Ariane using 32bit elf, do I need to configure the core? Or does it work out of the box?

Please let me know!

Thanks,
Jatan

**Comment by MikeOpenHWGroup** [comment]
Hi @jatanpandya83,  thanks for your interest in CVA6.  This issue has not been updated in almost two years, so I will assume it is resolved and will close this issue.  If you are still having trouble, please feel free to open another.
