### ISSUE TITLE
wt dcache tx transimit function 

### ISSUE THREAD

**Issue by S-Nomii** [openhwgroup/cva6#640]
Hi I am using cva core to study cache coherence. Can anyone help me with an understanding problem.

While wt cache write buffer use tx to transmit, the logic it use to split disaligned data is really odd to me. Here is my point of view. If If the valid area is 0000_0111, it wont match any of the given cases in toSize64 function, so it will marked as individual. What will happen is, instead of split into 0000_0011 and 0000_0100, it will split into 0000_0001, 0000_0010, 0000_0100. Because neither 0000_0111 nor 0000_0110 match any unique cases.

**Comment by MikeOpenHWGroup** [comment]
Hi @S-Nomii, this issue has not received a response in almost two years, so I am closing it now.
