### ISSUE TITLE
I can not log in to linux by default username root when starting the operating system

### ISSUE THREAD

**Issue by Wcm926** [openhwgroup/cva6#646]
Nothing happens when I type root , and the log is as follows

[ 0.000000] OF: fdt: Ignoring memory range 0x80000000 - 0x80200000
[ 0.000000] Linux version 5.1.0-rc7 (michscha@toscana.ee.ethz.ch) (gcc version 8.2.0 (GCC)) #2 SMP Tue Jun 4 23:34:11 CEST 2019
[ 0.000000] initrd not found or empty - disabling initrd
[ 0.000000] Zone ranges:
[ 0.000000] DMA32 [mem 0x0000000080200000-0x00000000bfffffff]
[ 0.000000] Normal empty
[ 0.000000] Movable zone start for each node
[ 0.000000] Early memory node ranges
[ 0.000000] node 0: [mem 0x0000000080200000-0x00000000bfffffff]
[ 0.000000] Initmem setup node 0 [mem 0x0000000080200000-0x00000000bfffffff]
[ 0.000000] software IO TLB: mapped [mem 0xbb1fd000-0xbf1fd000] (64MB)
[ 0.000000] elf_hwcap is 0x112d
[ 0.000000] percpu: Embedded 15 pages/cpu s24280 r8192 d28968 u61440
[ 0.000000] Built 1 zonelists, mobility grouping on. Total pages: 258055
[ 0.000000] Kernel command line: earlyprintk
[ 0.000000] Dentry cache hash table entries: 131072 (order: 8, 1048576 bytes)
[ 0.000000] Inode-cache hash table entries: 65536 (order: 7, 524288 bytes)
[ 0.000000] Sorting __ex_table...
[ 0.000000] Memory: 952132K/1046528K available (3710K kernel code, 225K rwdata, 1046K rodata, 6727K init, 797K bss, 94396K reserved, 0K cm)
[ 0.000000] SLUB: HWalign=64, Order=0-3, MinObjects=0, CPUs=1, Nodes=1
[ 0.000000] rcu: Hierarchical RCU implementation.
[ 0.000000] rcu: RCU event tracing is enabled.
[ 0.000000] rcu: RCU restricting CPUs from NR_CPUS=8 to nr_cpu_ids=1.
[ 0.000000] rcu: RCU calculated value of scheduler-enlistment delay is 10 jiffies.
[ 0.000000] rcu: Adjusting geometry for rcu_fanout_leaf=16, nr_cpu_ids=1
[ 0.000000] NR_IRQS: 0, nr_irqs: 0, preallocated irqs: 0
[ 0.000000] plic: mapped 3 interrupts with 1 handlers for 2 contexts.
[ 0.000000] riscv_timer_init_dt: Registering clocksource cpuid [0] hartid [0]
[ 0.000000] clocksource: riscv_clocksource: mask: 0xffffffffffffffff max_cycles: 0x6eb3e4560, max_idle_ns: 881590406254 ns
[ 0.000353] sched_clock: 64 bits at 15MHz, resolution 66ns, wraps every 4398046511080ns
[ 0.322857] printk: console [hvc0] enabled
[ 0.330378] Calibrating delay loop (skipped), value calculated using timer frequency.. 30.00 BogoMIPS (lpj=150000)
[ 0.347895] pid_max: default: 32768 minimum: 301
[ 0.365323] Mount-cache hash table entries: 2048 (order: 2, 16384 bytes)
[ 0.376823] Mountpoint-cache hash table entries: 2048 (order: 2, 16384 bytes)
[ 0.415649] *** VALIDATE proc ***
[ 0.470625] rcu: Hierarchical SRCU implementation.
[ 0.504449] smp: Bringing up secondary CPUs ...
[ 0.511317] smp: Brought up 1 node, 1 CPU
[ 0.538613] devtmpfs: initialized
[ 0.599438] random: get_random_bytes called from setup_net+0x32/0x15c with crng_init=0
[ 0.618473] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
[ 0.634829] futex hash table entries: 256 (order: 2, 16384 bytes)
[ 0.665528] NET: Registered protocol family 16
[ 1.106585] usbcore: registered new interface driver usbfs
[ 1.117690] usbcore: registered new interface driver hub
[ 1.128637] usbcore: registered new device driver usb
[ 1.177472] clocksource: Switched to clocksource riscv_clocksource
[ 1.253910] NET: Registered protocol family 2
[ 1.293509] tcp_listen_portaddr_hash hash table entries: 512 (order: 1, 8192 bytes)
[ 1.307995] TCP established hash table entries: 8192 (order: 4, 65536 bytes)
[ 1.323435] TCP bind hash table entries: 8192 (order: 5, 131072 bytes)
[ 1.341573] TCP: Hash tables configured (established 8192 bind 8192)
[ 1.362747] UDP hash table entries: 512 (order: 2, 16384 bytes)
[ 1.373308] UDP-Lite hash table entries: 512 (order: 2, 16384 bytes)
[ 1.391799] NET: Registered protocol family 1
[ 1.431964] RPC: Registered named UNIX socket transport module.
[ 1.441253] RPC: Registered udp transport module.
[ 1.448968] RPC: Registered tcp transport module.
[ 1.456996] RPC: Registered tcp NFSv4.1 backchannel transport module.
[ 22.714990] workingset: timestamp_bits=62 max_order=18 bucket_order=0
[ 23.332365] NFS: Registering the id_resolver key type
[ 23.341252] Key type id_resolver registered
[ 23.347356] Key type id_legacy registered
[ 23.353888] nfs4filelayout_init: NFSv4 File Layout Driver Registering...
[ 23.831282] io scheduler mq-deadline registered
[ 23.839212] io scheduler kyber registered
[ 26.951121] Serial: 8250/16550 driver, 4 ports, IRQ sharing disabled
[ 27.032430] 10000000.uart: ttyS0 at MMIO 0x10000000 (irq = 1, base_baud = 3125000) is a TI16750
[ 0.000000] OF: fdt: Ignoring memory range 0x80000000 - 0x80200000
[ 0.000000] OF: fdt: Ignoring memory range 0x80000000 - 0x80200000
[ 0.000000] Linux version 5.1.0-rc7 (michscha@toscana.ee.ethz.ch) (gcc version 8.2.0 (GCC)) #2 SMP Tue Jun 4 23:34:11 CEST 2019
[ 0.000000] Linux version 5.1.0-rc7 (michscha@toscana.ee.ethz.ch) (gcc version 8.2.0 (GCC)) #2 SMP Tue Jun 4 23:34:11 CEST 2019
[ 0.000000] initrd not found or empty - disabling initrd
[ 0.000000] initrd not found or empty - disabling initrd
[ 0.000000] Zone ranges:
[ 0.000000] Zone ranges:
[ 0.000000] DMA32 [mem 0x0000000080200000-0x00000000bfffffff]
[ 0.000000] DMA32 [mem 0x0000000080200000-0x00000000bfffffff]
[ 0.000000] Normal empty
[ 0.000000] Normal empty
[ 0.000000] Movable zone start for each node
[ 0.000000] Movable zone start for each node
[ 0.000000] Early memory node ranges
[ 0.000000] Early memory node ranges
[ 0.000000] node 0: [mem 0x0000000080200000-0x00000000bfffffff]
[ 0.000000] node 0: [mem 0x0000000080200000-0x00000000bfffffff]
[ 0.000000] Initmem setup node 0 [mem 0x0000000080200000-0x00000000bfffffff]
[ 0.000000] Initmem setup node 0 [mem 0x0000000080200000-0x00000000bfffffff]
[ 0.000000] software IO TLB: mapped [mem 0xbb1fd000-0xbf1fd000] (64MB)
[ 0.000000] software IO TLB: mapped [mem 0xbb1fd000-0xbf1fd000] (64MB)
[ 0.000000] elf_hwcap is 0x112d
[ 0.000000] elf_hwcap is 0x112d
[ 0.000000] percpu: Embedded 15 pages/cpu s24280 r8192 d28968 u61440
[ 0.000000] percpu: Embedded 15 pages/cpu s24280 r8192 d28968 u61440
[ 0.000000] Built 1 zonelists, mobility grouping on. Total pages: 258055
[ 0.000000] Built 1 zonelists, mobility grouping on. Total pages: 258055
[ 0.000000] Kernel command line: earlyprintk
[ 0.000000] Kernel command line: earlyprintk
[ 0.000000] Dentry cache hash table entries: 131072 (order: 8, 1048576 bytes)
[ 0.000000] Dentry cache hash table entries: 131072 (order: 8, 1048576 bytes)
[ 0.000000] Inode-cache hash table entries: 65536 (order: 7, 524288 bytes)
[ 0.000000] Inode-cache hash table entries: 65536 (order: 7, 524288 bytes)
[ 0.000000] Sorting __ex_table...
[ 0.000000] Sorting __ex_table...
[ 0.000000] Memory: 952132K/1046528K available (3710K kernel code, 225K rwdata, 1046K rodata, 6727K init, 797K bss, 94396K reserved, 0K cm)
[ 0.000000] Memory: 952132K/1046528K available (3710K kernel code, 225K rwdata, 1046K rodata, 6727K init, 797K bss, 94396K reserved, 0K cm)
[ 0.000000] SLUB: HWalign=64, Order=0-3, MinObjects=0, CPUs=1, Nodes=1
[ 0.000000] SLUB: HWalign=64, Order=0-3, MinObjects=0, CPUs=1, Nodes=1
[ 0.000000] rcu: Hierarchical RCU implementation.
[ 0.000000] rcu: Hierarchical RCU implementation.
[ 0.000000] rcu: RCU event tracing is enabled.
[ 0.000000] rcu: RCU event tracing is enabled.
[ 0.000000] rcu: RCU restricting CPUs from NR_CPUS=8 to nr_cpu_ids=1.
[ 0.000000] rcu: RCU restricting CPUs from NR_CPUS=8 to nr_cpu_ids=1.
[ 0.000000] rcu: RCU calculated value of scheduler-enlistment delay is 10 jiffies.
[ 0.000000] rcu: RCU calculated value of scheduler-enlistment delay is 10 jiffies.
[ 0.000000] rcu: Adjusting geometry for rcu_fanout_leaf=16, nr_cpu_ids=1
[ 0.000000] rcu: Adjusting geometry for rcu_fanout_leaf=16, nr_cpu_ids=1
[ 0.000000] NR_IRQS: 0, nr_irqs: 0, preallocated irqs: 0
[ 0.000000] NR_IRQS: 0, nr_irqs: 0, preallocated irqs: 0
[ 0.000000] plic: mapped 3 interrupts with 1 handlers for 2 contexts.
[ 0.000000] plic: mapped 3 interrupts with 1 handlers for 2 contexts.
[ 0.000000] riscv_timer_init_dt: Registering clocksource cpuid [0] hartid [0]
[ 0.000000] riscv_timer_init_dt: Registering clocksource cpuid [0] hartid [0]
[ 0.000000] clocksource: riscv_clocksource: mask: 0xffffffffffffffff max_cycles: 0x6eb3e4560, max_idle_ns: 881590406254 ns
[ 0.000000] clocksource: riscv_clocksource: mask: 0xffffffffffffffff max_cycles: 0x6eb3e4560, max_idle_ns: 881590406254 ns
[ 0.000353] sched_clock: 64 bits at 15MHz, resolution 66ns, wraps every 4398046511080ns
[ 0.000353] sched_clock: 64 bits at 15MHz, resolution 66ns, wraps every 4398046511080ns
[ 0.322857] printk: console [hvc0] enabled
[ 0.322857] printk: console [hvc0] enabled
[ 0.330378] Calibrating delay loop (skipped), value calculated using timer frequency.. 30.00 BogoMIPS (lpj=150000)
[ 0.330378] Calibrating delay loop (skipped), value calculated using timer frequency.. 30.00 BogoMIPS (lpj=150000)
[ 0.347895] pid_max: default: 32768 minimum: 301
[ 0.347895] pid_max: default: 32768 minimum: 301
[ 0.365323] Mount-cache hash table entries: 2048 (order: 2, 16384 bytes)
[ 0.365323] Mount-cache hash table entries: 2048 (order: 2, 16384 bytes)
[ 0.376823] Mountpoint-cache hash table entries: 2048 (order: 2, 16384 bytes)
[ 0.376823] Mountpoint-cache hash table entries: 2048 (order: 2, 16384 bytes)
[ 0.415649] *** VALIDATE proc ***
[ 0.415649] *** VALIDATE proc ***
[ 0.470625] rcu: Hierarchical SRCU implementation.
[ 0.470625] rcu: Hierarchical SRCU implementation.
[ 0.504449] smp: Bringing up secondary CPUs ...
[ 0.504449] smp: Bringing up secondary CPUs ...
[ 0.511317] smp: Brought up 1 node, 1 CPU
[ 0.511317] smp: Brought up 1 node, 1 CPU
[ 0.538613] devtmpfs: initialized
[ 0.538613] devtmpfs: initialized
[ 0.599438] random: get_random_bytes called from setup_net+0x32/0x15c with crng_init=0
[ 0.599438] random: get_random_bytes called from setup_net+0x32/0x15c with crng_init=0
[ 0.618473] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
[ 0.618473] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
[ 0.634829] futex hash table entries: 256 (order: 2, 16384 bytes)
[ 0.634829] futex hash table entries: 256 (order: 2, 16384 bytes)
[ 0.665528] NET: Registered protocol family 16
[ 0.665528] NET: Registered protocol family 16
[ 1.106585] usbcore: registered new interface driver usbfs
[ 1.106585] usbcore: registered new interface driver usbfs
[ 1.117690] usbcore: registered new interface driver hub
[ 1.117690] usbcore: registered new interface driver hub
[ 1.128637] usbcore: registered new device driver usb
[ 1.128637] usbcore: registered new device driver usb
[ 1.177472] clocksource: Switched to clocksource riscv_clocksource
[ 1.177472] clocksource: Switched to clocksource riscv_clocksource
[ 1.253910] NET: Registered protocol family 2
[ 1.253910] NET: Registered protocol family 2
[ 1.293509] tcp_listen_portaddr_hash hash table entries: 512 (order: 1, 8192 bytes)
[ 1.293509] tcp_listen_portaddr_hash hash table entries: 512 (order: 1, 8192 bytes)
[ 1.307995] TCP established hash table entries: 8192 (order: 4, 65536 bytes)
[ 1.307995] TCP established hash table entries: 8192 (order: 4, 65536 bytes)
[ 1.323435] TCP bind hash table entries: 8192 (order: 5, 131072 bytes)
[ 1.323435] TCP bind hash table entries: 8192 (order: 5, 131072 bytes)
[ 1.341573] TCP: Hash tables configured (established 8192 bind 8192)
[ 1.341573] TCP: Hash tables configured (established 8192 bind 8192)
[ 1.362747] UDP hash table entries: 512 (order: 2, 16384 bytes)
[ 1.362747] UDP hash table entries: 512 (order: 2, 16384 bytes)
[ 1.373308] UDP-Lite hash table entries: 512 (order: 2, 16384 bytes)
[ 1.373308] UDP-Lite hash table entries: 512 (order: 2, 16384 bytes)
[ 1.391799] NET: Registered protocol family 1
[ 1.391799] NET: Registered protocol family 1
[ 1.431964] RPC: Registered named UNIX socket transport module.
[ 1.431964] RPC: Registered named UNIX socket transport module.
[ 1.441253] RPC: Registered udp transport module.
[ 1.441253] RPC: Registered udp transport module.
[ 1.448968] RPC: Registered tcp transport module.
[ 1.448968] RPC: Registered tcp transport module.
[ 1.456996] RPC: Registered tcp NFSv4.1 backchannel transport module.
[ 1.456996] RPC: Registered tcp NFSv4.1 backchannel transport module.
[ 22.714990] workingset: timestamp_bits=62 max_order=18 bucket_order=0
[ 22.714990] workingset: timestamp_bits=62 max_order=18 bucket_order=0
[ 23.332365] NFS: Registering the id_resolver key type
[ 23.332365] NFS: Registering the id_resolver key type
[ 23.341252] Key type id_resolver registered
[ 23.341252] Key type id_resolver registered
[ 23.347356] Key type id_legacy registered
[ 23.347356] Key type id_legacy registered
[ 23.353888] nfs4filelayout_init: NFSv4 File Layout Driver Registering...
[ 23.353888] nfs4filelayout_init: NFSv4 File Layout Driver Registering...
[ 23.831282] io scheduler mq-deadline registered
[ 23.831282] io scheduler mq-deadline registered
[ 23.839212] io scheduler kyber registered
[ 23.839212] io scheduler kyber registered
[ 26.951121] Serial: 8250/16550 driver, 4 ports, IRQ sharing disabled
[ 26.951121] Serial: 8250/16550 driver, 4 ports, IRQ sharing disabled
[ 27.032430] 10000000.uart: ttyS0 at MMIO 0x10000000 (irq = 1, base_baud = 3125000) is a TI16750
[ 27.032430] 10000000.uart: ttyS0 at MMIO 0x10000000 (irq = 1, base_baud = 3125000) is a TI16750
[ 28.456022] printk: console [ttyS0] enabled
[ 28.456022] printk: console [ttyS0] enabled
[ 28.499169] piton_sd:v1.0 Apr 26, 2019
[ 28.499169]
[ 28.499169] piton_sd:v1.0 Apr 26, 2019
[ 28.499169]
[ 28.512048] vmap allocation for size 6592671433917067264 failed: use vmalloc= to increase size
[ 28.512048] vmap allocation for size 6592671433917067264 failed: use vmalloc= to increase size
[ 28.541583] ioremap returned NULL
[ 28.541583] ioremap returned NULL
[ 28.580783] xilinx_spi 20000000.xps-spi: at 0x20000000 mapped to 0x(ptrval), irq=2
[ 28.580783] xilinx_spi 20000000.xps-spi: at 0x20000000 mapped to 0x(ptrval), irq=2
[ 28.635093] libphy: Fixed MDIO Bus: probed
[ 28.635093] libphy: Fixed MDIO Bus: probed
[ 28.664137] lowrisc-digilent-ethernet: Lowrisc ethernet platform (30000000-30007FFF) mapped to ffffffd004028000
[ 28.664137] lowrisc-digilent-ethernet: Lowrisc ethernet platform (30000000-30007FFF) mapped to ffffffd004028000
[ 28.722389] libphy: GPIO Bitbanged LowRISC: probed
[ 28.722389] libphy: GPIO Bitbanged LowRISC: probed
[ 28.733909] Probing lowrisc-0:01 (address 1)
[ 28.733909] Probing lowrisc-0:01 (address 1)
[ 28.754303] RTL8211E Gigabit Ethernet lowrisc-0:01: attached PHY driver [RTL8211E Gigabit Ethernet] (mii_bus:phy_addr=lowrisc-0:01, irq=PO)
[ 28.754303] RTL8211E Gigabit Ethernet lowrisc-0:01: attached PHY driver [RTL8211E Gigabit Ethernet] (mii_bus:phy_addr=lowrisc-0:01, irq=PO)
[ 28.815609] lowrisc-eth 30000000.lowrisc-eth: Lowrisc Ether100MHz registered
[ 28.815609] lowrisc-eth 30000000.lowrisc-eth: Lowrisc Ether100MHz registered
[ 28.839233] ehci_hcd: USB 2.0 'Enhanced' Host Controller (EHCI) Driver
[ 28.839233] ehci_hcd: USB 2.0 'Enhanced' Host Controller (EHCI) Driver
[ 28.910747] mmc_spi spi0.0: SD/MMC host mmc0, no WP, no poweroff, cd polling
[ 28.910747] mmc_spi spi0.0: SD/MMC host mmc0, no WP, no poweroff, cd polling
[ 28.940760] usbcore: registered new interface driver usbhid
[ 28.940760] usbcore: registered new interface driver usbhid
[ 28.953214] usbhid: USB HID core driver
[ 28.953214] usbhid: USB HID core driver
[ 29.023510] NET: Registered protocol family 10
[ 29.023510] NET: Registered protocol family 10
[ 29.105931] Segment Routing with IPv6
[ 29.105931] Segment Routing with IPv6
[ 29.119385] sit: IPv6, IPv4 and MPLS over IPv4 tunneling driver
[ 29.119385] sit: IPv6, IPv4 and MPLS over IPv4 tunneling driver
[ 29.165944] NET: Registered protocol family 17
[ 29.165944] NET: Registered protocol family 17
[ 29.203072] Key type dns_resolver registered
[ 29.203072] Key type dns_resolver registered
[ 29.781215] Freeing unused kernel memory: 6724K
[ 29.781215] Freeing unused kernel memory: 6724K
[ 29.791386] This architecture does not have kernel memory protection.
[ 29.791386] This architecture does not have kernel memory protection.
[ 29.810886] Run /init as init process
[ 29.810886] Run /init as init process
[ 29.885485] mmc0: host does not support reading read-only switch, assuming write-enable
[ 29.885485] mmc0: host does not support reading read-only switch, assuming write-enable
[ 29.905690] mmc0: new SDXC card on SPI
[ 29.905690] mmc0: new SDXC card on SPI
[ 29.998184] mmcblk0: mmc0:0000 SD128 119 GiB
[ 29.998184] mmcblk0: mmc0:0000 SD128 119 GiB
[ 30.788633] mmcblk0: p1 p2
[ 30.788633] mmcblk0: p1 p2
Starting logging: OK
Initializing random number generator... [ 37.165131] random: dd: uninitialized urandom read (512 bytes read)
[ 37.165131] random: dd: uninitialized urandom read (512 bytes read)
done.
Starting rpcbind: OK
[ 40.402161] random: ssh-keygen: uninitialized urandom read (32 bytes read)
[ 40.402161] random: ssh-keygen: uninitialized urandom read (32 bytes read)
Starting sshd: [ 40.962577] random: sshd: uninitialized urandom read (32 bytes read)
[ 40.962577] random: sshd: uninitialized urandom read (32 bytes read)
OK
NFS preparation skipped, OK

Welcome to Buildroot
buildroot login:

**Comment by Moschn** [comment]
Solved in https://github.com/pulp-platform/ariane-sdk/issues/46
