### ISSUE TITLE
Empty vivado project

### ISSUE THREAD

**Issue by LIUQyou** [openhwgroup/cva6#651]
Hi,
I have a question about vivado project.
During the make FPGA, an Ariane.xpr vivado project file was created in the FPGA folder. If I open this file, the file is empty, should this be the case? I want to add other components in the Soc, if there is no working project, it would be more tedious.
Or is there any other way to create a working vivado project?
Thanks.

**Comment by MikeOpenHWGroup** [comment]
Hi @LIUQyou, thanks for your interest in CVA6.  However, we are not a Vivado support organization and as this issue has not received any further comments in ~1.75 years, I will close it now.
