### ISSUE TITLE
Could you tell me what method you use for board-level debugging during the design process？

### ISSUE THREAD

**Issue by Wcm926** [openhwgroup/cva6#657]
I've been having rsome problems trying to un a hello_world on the Genesys 2 and debug using OpenOCD.  I did (gdb) continue, but GDB never regains control. 
(gdb) c
Continuing...

then no response.

**Comment by Bill94l** [comment]
I have almost the same problem with another FPGA card
This publication may help you https://github.com/openhwgroup/cva6/issues/656

**Comment by MikeOpenHWGroup** [comment]
Thanks for your response @Bill94l.

Hi @Wcm926, given that this issue has not received any further comments in ~1.75 years, I will close it now.
