### ISSUE TITLE
Curious about Decoding

### ISSUE THREAD

**Issue by Iripi97** [openhwgroup/cva6#663]
I was wondering if the Compressed Decoder is necessary for the design? If it is removed will CVA6 still operate as intended and boot Linux, etc.?

**Comment by zarubaf** [comment]
No

**Comment by Iripi97** [comment]
What was the motivation behind splitting the decoding into two modules?

**Comment by MikeOpenHWGroup** [comment]
Hi @Iripi97, given that there has been no further update to this issue in > 1.5 years, I am closing it.
