### ISSUE TITLE
Error generating bit file in VCU118

### ISSUE THREAD

**Issue by Fog-cake** [openhwgroup/cva6#675]
Hi，
  I found that you have the constraint file corresponding to vcu118, and I also have a development board. So I modified all the board types that I could find in the Makefile. 
  The error is as follows.The software version I use is vivado2018.3.
![0e9a94e9baa8cddaf12c27d567c90bc](https://user-images.githubusercontent.com/61076176/120636382-29cc5300-c4a0-11eb-9df0-5532b5277cd2.png)

**Comment by Fog-cake** [comment]
I solved the problem after make clean, so I'm sorry to bother you.

**Comment by Fog-cake** [comment]
I am trying to specify the version of DDR3 to see how it turns out.

**Comment by Fog-cake** [comment]
This may be a version bug of vivado2018.3?

**Comment by Fog-cake** [comment]
The name mig_7series seems to be wrong.

**Comment by Bill94l** [comment]
For VCU118 FPGA board, you need to use DDR4

**Comment by Fog-cake** [comment]
> For VCU118 FPGA board, you need to use DDR4

Hi，Bill94l
Yes, I have switched to DDR4 and succeeded. But there is a problem, if I introduce DDR4_ sdram_ C1, in fact, can not output 200MHz clock. So I deleted this configuration.

**Comment by Bill94l** [comment]
The 200Mhz is just for Ethernet. You will be able to generate 250Mhz which will feed the clock generator, then from the clock generator you can add an output which gives you the 200MHz

**Comment by Bill94l** [comment]
did you manage to read the data from ddr4? I have a problem reading the data correctly

**Comment by Fog-cake** [comment]
> did you manage to read the data from ddr4? I have a problem reading the data correctly

I see the question you asked in issue, but it's a pity that I haven't done that yet. My JTAG actually works through a transfer card, and I have to modify my constraint file again.
