### ISSUE TITLE
Performance Counters width

### ISSUE THREAD

**Issue by nathpranay** [openhwgroup/cva6#683]
Hi Team,

As per riscv-privileged spec "All of these counters have 64-bit precision on RV32, RV64, and RV128." In CVA6 performance counter width is tied to XLEN value. According to the spec, the perf counters width should be 64 bits.

-Pranay

**Comment by MikeOpenHWGroup** [comment]
Hi @ASintzoff, can you respond to @nathpranay's question?  Thanks!

**Comment by ASintzoff** [comment]
In PR #1034 modifications are proposed to be compliant with the 64-bit width.

**Comment by ASintzoff** [comment]
Performance counter section in the User Manual refers to 64-bit width.
