### ISSUE TITLE
Field_name and its description while updating contain of the cva632a6_csr_template.yml and cva64a6_csr_template.yml

### ISSUE THREAD

**Issue by RanjanThales** [openhwgroup/cva6#696]
Hi Team,

While updating contain of the cva632a6_csr_template.yml and cva64a6_csr_template.yml, I couldn't find details on the field_name and its description. i.e. 

- csr: CSR_FFLAGS
  description: >
    Floating point Accrued Exceptions
  address: 0x001
  privilege_mode: U
  rv32:
    - field_name: *******
      description: >
        ********************************
      type: W/R
      reset_val: 0
      msb: 4
      lsb: 0

-Ranjan

**Comment by MikeOpenHWGroup** [comment]
The CSRs are specified in the Priviledged Specification which you can fetch from [riscv.org](https://riscv.org/technical/specifications/).  Below is an example of the field specification of the MISA CSR:
![image](https://user-images.githubusercontent.com/55248931/126319554-a8f38162-584a-4a62-b5fc-bcd8684b09be.png)


This illustrates that there are three fields in MISA, but only two contain actionable information:
- **MXL** in bits [XLEN-1 : XLEN-2] specifies the machine XLEN (32, 64 or 128 bits).
- **Extensions** in bits [25:0] is encoded to specify the instruction extenions supported by the core.
The remaining field from [XLEN-3 : 26] is a "write legal, read legal" (WLRL) field that does not do anything.  The CV32E40P User Manual specifies that its implementation of [misa](https://cv32e40p.readthedocs.io/en/latest/control_status_registers/#machine-isa-misa) is a read-only field that always returns zero.

The MISA is a good example of why we need a complete specification of the CVA6 CSRs in the CVA6 User Manual:
- The Priviledged Specification allows for specific cores to implement the CSR or not.  We must indicate that CVA6 _does_ implement this CSR.
- The valiue of MXL depends on whether the core is compiled/synthesized for 32 or 64 bits.
- The value of the unused WLRL field must be specified (the Priviledged Specification does not specify it).
- The value of the Extension bits is core-specific.
