### ISSUE TITLE
ci/travis-ci-emul.sh encounter problem

### ISSUE THREAD

**Issue by Yuxin-Yu** [openhwgroup/cva6#707]
Hi Bro:
when I input command:
`ci/travis-ci-emul.sh`
it shows:
![image](https://user-images.githubusercontent.com/38584421/129166690-decb6a0d-46d1-4fcb-a342-6c4e794df1fe.png)
Could you tell me how to fix this problem
thanks you so much

**Comment by MikeOpenHWGroup** [comment]
Hi @Yuxin-Yu, this issue is very old and has received no responses, so I will close it now. Please feel free to re-open it or create a new issue is this problem still persists for you.
