### ISSUE TITLE
PMP Configuration Registers pmpcgf1 and pmpcfg3 for CV32A6 is not present for CSR Read

### ISSUE THREAD

**Issue by nathpranay** [openhwgroup/cva6#733]
As per specification for 32 Bit CPU we should have CSR_PMPCFG0, CSR_PMPCFG1, CSR_PMPCFG2 and CSR_PMPCFG3. How ever for 64 bit CPU, it requires only CSR_PMPCFG0 and CSR_PMPCFG2 [ For CSR Read this is present in RTL].
For CSR Read CSR_PMPCFG1 and CSR_PMPCFG3 is not present which is required for 32 Bit CPU.

**Comment by JeanRochCoulon** [comment]
PMP has been designed one year ago by ETH Zurich. Adaptation was done for 32bits at this time. @zarubaf, could we assign the issue to the PMP designer ?

**Comment by zarubaf** [comment]
That would be @Moschn - maybe if we ask nicely he can have a look? 👀
