### ISSUE TITLE
Consolidate SV32 and SV39 MMUs

### ISSUE THREAD

**Issue by zarubaf** [openhwgroup/cva6#770]
Right now the files are mostly copies of each other but the differences are not small enough so that we can use SV parameters to capture them so we would need to revert to some sort of generation (templating, or similar).

**Comment by jquevremont** [comment]
For the record: Mako templates once considered (https://www.makotemplates.org) to generate SV files.

**Comment by MikeOpenHWGroup** [comment]
The policy used by CV32E40 cores for these types of Issues is to mark them as `Type:Enhancement` and `Status:Wont-fix` and then Close them.  Subsequent versions of the CVA6 can easily look for these issues and decide if they will be fixed.
