### ISSUE TITLE
Adding benchmarks

### ISSUE THREAD

**Issue by imadassir** [openhwgroup/cva6#793]
Hello,
As part of a personal project, I am working on adding a prefetcher for CVA6. To test its performance, I would like to run some benchmarks like SPEC or something similar. Are there any benchmark suites like SPEC that are supported for CVA6?
Thanks!

**Comment by MikeOpenHWGroup** [comment]
Hi @imadassir, thanks for your query and apologies for taking so long to respond.

@ASintzoff, can you answer this question?

**Comment by ASintzoff** [comment]
Unfortunately, I don't know any benchmark suite already "officially" supported.

Hopefully, in the coming weeks, CoreMark suite will be supported.
