### ISSUE TITLE
Multi-issue support

### ISSUE THREAD

**Issue by faridsamandi** [openhwgroup/cva6#807]
Hi. Apparently there was a branch implementing multi-issue, but it doesn't exist anymore. What happened to that? Does ariane not support multi issue?

**Comment by zarubaf** [comment]
Ariane, right now, is single issue. The superscalar branch was experimental but never reached a mature state.

**Comment by faridsamandi** [comment]
Hi Florian, thanks for the response. Was there a specific issue that prevented it from succeeding? Since I see some of the required infrastructure for a superscalar core already exist in the pipeline.
