### ISSUE TITLE
no makefile in core/example_tb

### ISSUE THREAD

**Issue by Rayz-b** [openhwgroup/cva6#811]
error while running following code from README.md:
<CODE>
$ cd core/example_tb
$ make veri_run
</CODE>

**Comment by Rayz-b** [comment]
ALSO: <code>make help</code> doesn't work
<code>make: *** no rule to make target help</code>

**Comment by zarubaf** [comment]
@MikeOpenHWGroup what was the intention of `example_tb`?

**Comment by TNdu** [comment]
I too have this error and cannot run the "make veri_run" command as stated in the **Build Model and Run Simulation** section at **To build, compile and run the CVA6 core-only in its example testbench using Verilator (known to work with V4.108)** step.

**Comment by zarubaf** [comment]
Ping @MikeOpenHWGroup

**Comment by pjlobo** [comment]
Please see https://github.com/openhwgroup/cva6/issues/877#issuecomment-1384234340

**Comment by MikeOpenHWGroup** [comment]
My apologies for letting this Issue go stale.  The `example_tb`was a failed experiment from more than a year ago.   This issue can be closed.

**Comment by hhhsiang** [comment]
Hi @MikeOpenHWGroup ,so the commands:
`$ cd core/example_tb`
`$ make veri_run`
are meaningless now, right? Thanks.
