### ISSUE TITLE
Inline Assembly code in cva6 -reg

### ISSUE THREAD

**Issue by SreeRanjaniRajendran** [openhwgroup/cva6#831]
Hi, anyone can suggest me how to run/compile a Inline Assembly code in cva6 core. Thanks in advance.

**Comment by eyssartk** [comment]
https://www.codeproject.com/Articles/15971/Using-Inline-Assembly-in-C-C

**Comment by MikeOpenHWGroup** [comment]
This Issue is almost one year old, so I will assume that @SreeRanjaniRajendran eventually received the answer they were looking for.

Closing.
