### ISSUE TITLE
interrupt nesting

### ISSUE THREAD

**Issue by LangQingjie** [openhwgroup/cva6#852]
Hello, I was reading the source code of cva6 recently, but I was a little confused about the implementation of interrupt nesting. I didn't understand how was it implement interrupt nesting in cva6 . Or cva6  had not implement interrupt nesting.

**Comment by MikeOpenHWGroup** [comment]
Hi @LangQingjie, thanks for your question and sorry it has taken so long to respond.  We are in the process of a significant update to the [CVA6 User Manual](https://docs.openhwgroup.org/projects/cva6-user-manual/index.html) and this question will be answered there.
