### ISSUE TITLE
[TASK] Raise a CQ (Eclipse contribution questionnaire)

### ISSUE THREAD

**Issue by jquevremont** [openhwgroup/cva6#872]
### Is there an existing CVA6-SDK task for this?

- [X] I have searched the existing task issues

### Task Description

Raise the Eclipse contribution questionnaire. Guidance from @DBees might be needed.
Goal: 2022-06-30.

### Description of Done

Contribution questionnaire raised (we might need to sort the details out).

**Comment by jquevremont** [comment]
Mike will talk to Duncan and get this kicked off.

**Comment by jquevremont** [comment]
The process might have changed. This is likely not needed anymore. Duncan will double check.

**Comment by jquevremont** [comment]
Process changed. Not needed anymore.

**Comment by DBees** [comment]
Correct @jquevremont
