### ISSUE TITLE
[TASK] <dummy-issue-ECC>

### ISSUE THREAD

**Issue by RanjanThales** [openhwgroup/cva6#874]
### Is there an existing CVA6-SDK task for this?

- [X] I have searched the existing task issues

### Task Description

NA

### Description of Done

NA

**Comment by MikeOpenHWGroup** [comment]
Hi @RanjanThales, what is the status of this Issue?  If it is not needed, please close it.

**Comment by RanjanThales** [comment]
Hi Mike, this issue was just opened for dummy purpose to test different labels/Projects, So this is not needed now (closing this right away :).
