### ISSUE TITLE
[TASK] Implementing CSR gap-performance counter size

### ISSUE THREAD

**Issue by TulikaSi** [openhwgroup/cva6#875]
### Is there an existing CVA6-SDK task for this?

- [X] I have searched the existing task issues

### Task Description

Build code to move Performance counter size to 64 bit and make it independent of XLEN.

### Description of Done

Acceptance of Pull request.

**Comment by jquevremont** [comment]
Reviewed with comments. Need to iterate with reviewers.

**Comment by jquevremont** [comment]
Test in progress. OK in Verilator. VSC failures to understand.

**Comment by TulikaSi** [comment]
A PR done for an early check on Github(as mentioned).The CI passed on Github.
Modified the code to resolve the errors generated through VCS but still some other errors are showing up wrt simulations. Working on debugging the errors. As soon as the error resolves I will raise the PR along with the document on Performance counters (Trying best to raise the PR by the end of this week).

**Comment by jquevremont** [comment]
Errors solved. Next step: draft PR.

**Comment by jquevremont** [comment]
PR merged. Working on gaps: ``mcountinhibit`` and shadow CSRs.

**Comment by jquevremont** [comment]
Gaps: investigating the gate increase.

**Comment by TulikaSi** [comment]
Increase in gate count resolved
PR merged
