### ISSUE TITLE
[Bug Report] CPU mode is not provided to the CVXIF interface

### ISSUE THREAD

**Issue by ZElkacimi** [openhwgroup/cva6#880]
When executing a simple test offloading a cvxif instruction (example: with core-v-verif, use the following command to execute cvxif_multi.S test; `python3 cva6.py --testlist=../tests/testlist_cvxif.yaml --test cvxif_multi  --iss_yaml cva6.yaml --target cv64a6_imafdc_sv39 --iss=vcs-uvm`), I notice at the log file that cva6 mode is 3 (machine mode).
Following is a snippet of the csv output file:
![image](https://user-images.githubusercontent.com/96719191/169838991-49444aea-d471-4c3b-82c3-6e1d235b5325.png)

While in the message printed by the agent’s monitor, the mode offloaded by the cvxif interface (issue_req.mode) is always 0.
In addition, Looking at the rtl code (cvxif_fu module), mode signal is never assigned.

**Comment by MikeOpenHWGroup** [comment]
Hi @ZElkacimi, this issue is more than 7 months old and has not received any updates. It looks like an important issue to me. Please work with @JeanRochCoulon to assign the right person to move this along.

**Comment by AyoubJalali** [comment]
This issue has been fixed by PR #1298
