### ISSUE TITLE
[Bug Report] Issue when randomizing the CVXIF issue_ready signal

### ISSUE THREAD

**Issue by ZElkacimi** [openhwgroup/cva6#881]
In the cvxif Spec, we have the following: 
-	The transaction signaled via issue_req and issue_resp is accepted when issue_valid and issue_ready are both 1. 
-	A CPU is allowed to retract its issue request transaction before it is accepted with issue_ready = 1 ...

So, when the cpu retract the request before issue_ready=1, it should not wait for the result of the corresponding transaction, else, the transaction should remain stable until it’s accepted with issue_ready=1.

For CVA6, When the cvxif agent randomize the issue_ready, in the case where issue_ready=0 && issue_valid=1, we notice that CVA6, retract its issue request before the issue_ready become 1. Yet, cva6 waits for the result of this transaction.

To reproduce the issue, in the config of the agent (uma_cvxif_cfg), change the value of
 ready_mode  from UVMA_CVXIF_ISSUE_READY_FIX; to  UVMA_CVXIF_ISSUE_READY_RANDOMIZED;
and run any test (with core-v-verif) offloading many instructions to meet the case where issue_ready=0 && issue_valid=1.

Note: one of the possible cases where this issue may present is when the Coprocessor is connected to many CPUs.

**Comment by MikeOpenHWGroup** [comment]
Hi @ZElkacimi, this issue is more than 7 months old and has not received any updates. It looks like an important issue to me. Please work with @JeanRochCoulon to assign the right person to move this along.
