### ISSUE TITLE
[Bug Report] Wrong type exception when access invalid memory

### ISSUE THREAD

**Issue by chenc6** [openhwgroup/cva6#883]
Hi,

Our test cases show that when cva6 jumps to an invalid address (e.g., 0x7ff84538), it throws an Instruction Page Fault exception (at 22990ns). However, we believe it should throw the Instruction Access Fault exception based on the priority of exception from the  RISC-V ISA Volume II: Privileged Architecture 20211203.

![image](https://user-images.githubusercontent.com/79608200/170134881-6bc98424-cf4b-4b12-ba71-b21814bd3a20.png)

![image](https://user-images.githubusercontent.com/79608200/170134085-819c9c2b-3508-40fd-9e0d-f57e4943bc68.png)

The test mem file and RTL log are attached.
[wrong_excep.zip](https://github.com/openhwgroup/cva6/files/8766313/wrong_excep.zip)

**Comment by MikeOpenHWGroup** [comment]
Hi @JeanRochCoulon, this issue is more than 7 months old and has not received any updates. It looks like an important issue to me. Please assign the right person to move this along.

**Comment by Jbalkind** [comment]
It's possible that this was addressed by the MMU changes in #968 but I'm not 100% sure. Worth checking

**Comment by JeanRochCoulon** [comment]
Hi André, as this GitHub issue is related to the traps, I feel good to assign it to you.

**Comment by ASintzoff** [comment]
According to Table 3.7 of RISC-V ISA Volume II: Privileged Architecture 20211203, the priority of page fault or access fault during instruction address translation is determined by the first one encountered.
Therefore the CVA6 behaviour is compliant with RISC-V specification.

BTW the exception cause code is not related at all to the exception priority.
