### ISSUE TITLE
[Bug report] miss illegal instruction exception when rd of MULHU is the same as rs1 or rs2

### ISSUE THREAD

**Issue by chenc6** [openhwgroup/cva6#885]
Hi,

The RISC-V ISA Volume I, 20190608, page 43 mentions: "MULH[[S]U] rdh, rs1, rs2; MUL
rdl, rs1, rs2 (source register specifiers must be in same order and rdh cannot be the same as rs1 or rs2)"
![image](https://user-images.githubusercontent.com/79608200/170154875-91a5238a-9b8d-4fc5-8d7a-6ef193ef5f70.png)

Our testcase shows cva6 will not throw illegal instruction exception in this case while spike does at line 84.
![image](https://user-images.githubusercontent.com/79608200/170155008-0d8d99f5-10ef-4ecd-90a5-33209612369a.png)

The testcase mem file, rtl trace log, and spike trace log are attached.
[missexcept.zip](https://github.com/openhwgroup/cva6/files/8767083/missexcept.zip)

Thank you

**Comment by MikeOpenHWGroup** [comment]
Hi @JeanRochCoulon , this issue is more than 7 months old and has not received any updates. It _looks_ like an important issue to me.  Please assign the right person to move this along.

**Comment by JeanRochCoulon** [comment]
@AyoubJalali  You should meet this case doing the ISACOV verification. Does ISACOV cover this case ?

**Comment by AyoubJalali** [comment]
@JeanRochCoulon It should be, but i'll look at it

**Comment by AyoubJalali** [comment]
@chenc6 hello, so I run a test with : 
_**main:             mulhsu     zero, zero, zero
                  mul        zero, zero, zero
                  slti       zero, t6, -972
                  div        ra, s2, s8
                  andi       s0, s9, -182
                  or         t6, a3, a5
                  auipc      t4, 691756
                  mul        tp, s3, t1
                  add        t0, a6, zero
                  srli       a7, a2, 7
                  sub        s5, s11, s11
                  srai       s7, s4, 26
                  or         a2, sp, t1
                  remu       ra, t2, a1
                  divu       a3, sp, s1
                  slli       s3, s4, 2
                  srl        s4, s3, t2
                  rem        tp, s1, a3
                  div        ra, t5, t5
                  j test_done**_
and i didn't get any illegal instructions exception on spike side as you see here : 

![image](https://user-images.githubusercontent.com/110232072/225043218-f9a1b8af-a146-401b-b01d-8f6b56e7735e.png)

so could you providing me with the source file .S, to try to reproduce the problem if it still.
@JeanRochCoulon just to answering your question it's cover as far as I know

**Comment by chenc6** [comment]
@AyoubJalali Sorry, I couldn't find the .S file, but it should be easy to reproduce because the issue is only related to one instruction.

Maybe you can change the instruction from `mulhsu` to `mulhu`, such that the binary code will be 0200`3`033 but not 0200`2`033?

**Comment by AyoubJalali** [comment]
@chenc6 I don't thing also it's a problem, because i covered all possible combinations between all multiplications instructions with all values of rx registers :

![image](https://user-images.githubusercontent.com/110232072/225052663-c33f487c-efa1-4917-a2e7-e200d4c636d0.png)

So could the problem be in spike version, so which version you use for this test ?

**Comment by JeanRochCoulon** [comment]
@chenc6 and @AyoubJalali   The RISCV specification tells us that "rdh cannot be the same as rs1 or rs2".    It is not clear to me if an illegal instruction must be triggered or not. Does the RISCV or the CVA6 ISA specification tells us what is the behaviour in that case?

**Comment by ASintzoff** [comment]
@JeanRochCoulon @chenc6 @AyoubJalali The CVA6 behaves correctly. There is no reason to raise an illegal instruction exception on `MULH[[S]U]` instruction. 

The specification only warns the software developer when using `MULH[[S]U]` and `MUL` instructions. If `rdh` is the same as `rs1` or `rs2` for `MULH[[S]U]`, then the following `MUL` will compute a result based on a modified `rs1` or `rs2`. Therefore, in such case, the `MUL` result will not be the expected one.

**Comment by AyoubJalali** [comment]
@JeanRochCoulon I don't think the cva6 should raised an illegal instruction it's just a recommendation if you want the lower & upper part of the multiplication you should use a sequence mentioned in the RISCV spec.

**Comment by JeanRochCoulon** [comment]
Understood. Thank for your investigation.

**Comment by AyoubJalali** [comment]
After the discussion above, I think there's no issue related to the instructions mentioned above
