### ISSUE TITLE
CVXIF feature missing: wait for the result of the instruction that raise the issue resp.exc signal

### ISSUE THREAD

**Issue by ZElkacimi** [openhwgroup/cva6#887]
CPU shall wait for the result of an instruction that raises the issue_resp.exc=1 signal (by the coprocessor), because it can then no longer retire (or commit via the commit interface) any younger instruction before it is known if the possible exception in the coprocessor actually happened or not, which will only be known at the corresponding result handshake (result.exc).
That is the easiest implementation; otherwise CPU might need to unroll/undo instructions that should not have been executed.

**Comment by MikeOpenHWGroup** [comment]
Hi @ZElkacimi, this issue is more than 6 months old and has not received any updates. Please work with @JeanRochCoulon to find the right person to move this along.

**Comment by Gchauvon** [comment]
Still relevant

**Comment by AyoubJalali** [comment]
The protocol has been updated to higher version v1.0.0
This issue is related to last version of protocol
