### ISSUE TITLE
CVA6 never raise the cvxif commit_kill signal

### ISSUE THREAD

**Issue by ZElkacimi** [openhwgroup/cva6#891]
If commit_valid is 1 and commit_kill is 0, then the core guarantees that the offloaded instruction (id) is no longer speculative, will not get killed (e.g. due to misspeculation or an exception in a preceding instruction), and is allowed to be committed. If commit_valid is 1 and commit_kill is 1, then the offloaded instruction (id) shall be killed in the coprocessor and the coprocessor must guarantee that the related instruction does/did not change architectural state.

In all tested cvxif custom instructions, cva6 have never raised the commit_kill signal, even when it has an exception in a preceding instruction.

**Comment by MikeOpenHWGroup** [comment]
Hi @ZElkacimi, this issue is more than 6 months old and has not received any updates. Pleas work with @JeanRochCoulon to find the right person to move this along.

**Comment by Gchauvon** [comment]
Feature not supported. Not a bug.
