### ISSUE TITLE
CVXIF result_ready is always 1

### ISSUE THREAD

**Issue by ZElkacimi** [openhwgroup/cva6#896]
CVA6 always sets the signal result_ready to 1.

**Comment by MikeOpenHWGroup** [comment]
Hi @ZElkacimi, this issue is more than 6 months old and has not received any updates.  Pleas work with @JeanRochCoulon to find the right person to move this along.

**Comment by Gchauvon** [comment]
Not a bug, this is the desired behaviour of the CVA6.
