### ISSUE TITLE
CVXIF issue_valid and commit_valid are always sent at the same clk cycle

### ISSUE THREAD

**Issue by ZElkacimi** [openhwgroup/cva6#897]
CVA6 always send the issue transaction and the commit transaction at the same clk cycle. It's allowed by the cvxif Spec, but if it is hard coded it may cause problems in some cases where cva6 needs to set the commit_kill (currently CVA6 never raise the commit_kill signal).

**Comment by MikeOpenHWGroup** [comment]
Hi @ZElkacimi, this issue is more than 6 months old and has not received a comment.  Can you work with @JeanRochCoulon to identify the right person to move this issue forward?

**Comment by Gchauvon** [comment]
Feature not supported. A fix might come with an update implementation of the CVXIF which is still in development.
