### ISSUE TITLE
work-ver/Variane_testharness Fail!

### ISSUE THREAD

**Issue by FranDuqueAyachi** [openhwgroup/cva6#902]
I have already make the command: make verilate DEBUG=1 succesfully to support vcd files.
But when I try to make any test from Variane_testharness as :
 
run a bare metal test to generate a VCD waveform:
    work-ver/Variane_testharness -v rv64ui-p-add.vcd $RISCV/riscv64-unknown-elf/share/riscv-tests/isa/rv64ui-p-add

it actually generate the rv64ui-p-add.vcd file but it is empty because I cant not open it on Questasim when I try to convert it from vcd to wlf file and also the terminal show me the next error:

Listening on port 38713
Variane_testharness: ../fesvr/elfloader.cc:23: std::map<std::__cxx11::basic_string<char>, long unsigned int> load_elf(const char*, memif_t*, reg_t*): Assertion `fd != -1' failed.

I have my RISCV variable correctly pointing into the same directory I put on the command.

But when I execute using pk with the comand: work-ver/Variane_testharness $RISCV/riscv64-unknown-elf/bin/pk hello.elf
everything works fine...
Any help? thank you so much!

**Comment by FranDuqueAyachi** [comment]
> I have already make the command: make verilate DEBUG=1 succesfully to support vcd files. But when I try to make any test from Variane_testharness as :
> 
> run a bare metal test to generate a VCD waveform: work-ver/Variane_testharness -v rv64ui-p-add.vcd $RISCV/riscv64-unknown-elf/share/riscv-tests/isa/rv64ui-p-add
> 
> it actually generate the rv64ui-p-add.vcd file but it is empty because I cant not open it on Questasim when I try to convert it from vcd to wlf file and also the terminal show me the next error:
> 
> Listening on port 38713 Variane_testharness: ../fesvr/elfloader.cc:23: std::map<std::__cxx11::basic_string, long unsigned int> load_elf(const char*, memif_t*, reg_t*): Assertion `fd != -1' failed.
> 
> I have my RISCV variable correctly pointing into the same directory I put on the command.
> 
> But when I execute using pk with the comand: work-ver/Variane_testharness $RISCV/riscv64-unknown-elf/bin/pk hello.elf everything works fine... Any help? thank you so much!

I have found that if I try it directly with the Makefile using the command:
make run-asm-tests-verilator
it actually works because the paths that it use isnt the same than:  $RISCV/riscv64-unknown-elf/share/riscv-tests/isa/rv64ui-p-add
instead of that path the command make run-asm-tests-verilator use the path: tmp/riscv-tests/build/isa//rv64ui-p-add

**Comment by XiaoAn109** [comment]
What is your verilator version? I can't parse "-v" parameter into the object. I tried "make verilate DEBUG=1" but it was no use.

**Comment by MikeOpenHWGroup** [comment]
Hi @FranDuqueAyachi, I _think_ your issue is resolved, so I am closing this issue.  Feel free to open a new issue if need be.

Thanks!
