### ISSUE TITLE
[Question] Atomic instruction AMOSWAP

### ISSUE THREAD

**Issue by Nicolas-Gaudin** [openhwgroup/cva6#903]
Hello !

I am intrigued by the behavior of an atomic instruction: **amoswap**. 
I observe the following behavior for amoswap rd, rs2, (rs1):
```
rd = M[rs1];
M[rs1]' = rs2;
rd' = rs2;
```
with at the end : 
**_rd' = rs2
M[rs1]' = rs2
rs2 not updated_**
So at no time is rs2 updated with the old value present in memory at address rs1.

I excepted to have the following behavior :
```
rd = M[rs1];
swap(rd , rs2); => rd' = rs2; rs2' = M[rs1];
M[rs1]' = rd' = rs2;
```
with at the end : 
**_rd'        = rs2
M[rs1]' = rs2
rs2'      = M[rs1]_**
Should we have this behavior?

_* M[x] => It is the data present at the address x
ry => initial value of the y register
ry' => final value of the y register_

**Comment by MikeOpenHWGroup** [comment]
Hi @Nicolas-Gaudin, this question is best answered by reading the RISC-V ISA, not a repository of an RTL implementation.
