### ISSUE TITLE
[TASK] Integration with latest Kernel from FreeRTOS.org

### ISSUE THREAD

**Issue by anjaliigedam** [openhwgroup/cva6#910]
### Is there an existing CVA6-SDK task for this?

- [X] I have searched the existing task issues

### Task Description

There is separate RISCV Portable area which has architectural level details

### Description of Done

Testcases working on CVA6 Genesys-2

**Comment by jquevremont** [comment]
Outstanding: Ethernet driver; resource to identify.

**Comment by MikeOpenHWGroup** [comment]
@jquevremont, @anjaliigedam, what is the status of this issue?

**Comment by jquevremont** [comment]
On hold for maternity leave.

**Comment by jquevremont** [comment]
Not yet resumed task.

**Comment by anjaliigedam** [comment]
"older" FreeRTOS working on recent CVA6.

Have migrated to use latest Kernel from FreeRTOS.org and get demo working. 
Execution stuck at initialization.

**Comment by anjaliigedam** [comment]
cva6 FreeRTOS is up-streamed on AWS FreeRTOS repository.
[https://github.com/FreeRTOS/FreeRTOS-Partner-Supported-Demos/tree/44b2426a9bba9456a8f7d0dfe2a5f849122f18be/RISC-V_cva6](url)

We can mark this task as closed.
