### ISSUE TITLE
[TASK] Add riscv-arch-test suite to existing CVA6 core-v-verif CI (32-bit and 64-bit)

### ISSUE THREAD

**Issue by spidugu444** [openhwgroup/cva6#912]
### Is there an existing CVA6-SDK task for this?

- [X] I have searched the existing task issues

### Task Description

Adding riscv-arch-test suite for cva6 environment.

steps:
1.Please find the [setup](https://github.com/openhwgroup/core-v-verif/pull/1254) used to bring up cva6   riscv-arch-tests with the riscof-dev infrastructure
2.Need to update [spike](https://github.com/riscv-software-src/riscv-isa-sim/releases/tag/v1.1.0) version 1.1.0.

### Description of Done

Need to run all test cases and perform CI flow.

**Comment by jquevremont** [comment]
This task belongs to core-v-verif. It's been closed here and re-created in core-v-verif.
