### ISSUE TITLE
[TASK] Integration with CORE-V-FreeRTOS

### ISSUE THREAD

**Issue by anjaliigedam** [openhwgroup/cva6#913]
### Is there an existing CVA6-SDK task for this?

- [X] I have searched the existing task issues

### Task Description

Core-v-FreeRTOS Project Launch is done. 
Once the project is ready to add more cores, we will add CVA6 FreeRTOS support to it.

### Description of Done

- Testcases working on CVA6 Genesys-2
- Acceptance of Pull Request by Robert Balas

**Comment by jquevremont** [comment]
Anjali Verma will (later) work on the CVA6 PMP integration in FreeRTOS.

**Comment by MikeOpenHWGroup** [comment]
@jquevremont, @anjaliigedam, what is the status of this issue?

**Comment by anjaliigedam** [comment]
A PA document has been prepared and shared with Jeremy Bennett for review.

**Comment by anjaliigedam** [comment]
PA for CVA6 FreeRTOS is available on below url.

[https://github.com/openhwgroup/programs/blob/master/Project-Descriptions-and-Plans/FreeRTOS/PA%20for%20CVA6%20FreeRTOS%20support.md](url)

We can mark this task as closed.
