### ISSUE TITLE
[TASK] Integrate Linux Boot on FPGA to Thales-CI Verification

### ISSUE THREAD

**Issue by Gchauvon** [openhwgroup/cva6#915]
### Is there an existing CVA6-SDK task for this?

- [X] I have searched the existing task issues

### Task Description

Integrate Linux Boot on Genesys2 FPGA to Thales-CI Verification.

- Commit necessary scripts for the task
- Result are visible on dashboard

### Description of Done

Every Pull Request on CVA6 trigger a boot of linux in Thales-CI.

**Comment by jquevremont** [comment]
Done for 64b Linux.
Complex to do for both 32b and 64b Linux as the Linux distro is on the SDCard.

**Comment by jquevremont** [comment]
Triggered by the CI, but only for one configuration.
Sébastien: able to load Linux through JTAG. Could it help support several configurations?

**Comment by MikeOpenHWGroup** [comment]
@jquevremont, @sjthales, @Gchauvon, what is the status of this issue?

**Comment by Gchauvon** [comment]
Done for 64b Linux.
Not started for 32b Linux, it is part of step 1 verification schedule.

**Comment by jquevremont** [comment]
The task is tracked in the verification GANTT. Closing it here.

**Comment by JeanRochCoulon** [comment]
@jquevremont  Can I ask you to review the task done by @Gchauvon and change the status from "Done" to "Finished - approved by reviewer" if you think the task is completed ?

**Comment by jquevremont** [comment]
Review performed offline. LGTM
