### ISSUE TITLE
[Maybe a bug] When run hello.elf An illegal instruction was executed!

### ISSUE THREAD

**Issue by shaoway** [openhwgroup/cva6#932]
#  run the model:
$ ./work-ver/Variane_testharness /opt/riscv/riscv64-unknown-elf/bin/pk ./hello.elf
This emulator compiled with JTAG Remote Bitbang client. To enable, use +jtag_rbb_enable=1.
Listening on port 42269
bbl loader
z  0000000000000000 ra ffffffc000001318 sp ffffffc00009ae10 gp 0000000000000000
tp 0000000000000000 t0 0000000000000000 t1 0000000000000000 t2 0000000090000000
s0 ffffffc00009d098 s1 0000000000000003 a0 000000008009e000 a1 ffffffbf80000000
a2 ffffffc00009f000 a3 0000000000000001 a4 00000000200278c7 a5 000000008009e000
a6 0000000000000012 a7 000000000000ff65 s2 0000000000013000 s3 0000000020027800
s4 ffffffc00009b000 s5 0000000000001000 s6 0000000000008012 s7 0000000000000001
s8 ffffffc00009d0a0 s9 0000000000015000 sA 0000000000000001 sB ffffffc000017080
t3 ffffffc000017028 t4 ffffffffffffffff t5 0000000002000000 t6 0000000002004000
pc ffffffc000001332 va/inst 0000000012090073 sr 8000000200006100
An illegal instruction was executed!
/opt/riscv/riscv64-unknown-elf/bin/pk *** FAILED *** (code = -1) after 2106314 cycles
CPU time used: 226838.38 ms
Wall clock time passed: 226997.17 ms

# run spike :
$ /opt/riscv/bin/spike /opt/riscv/riscv64-unknown-elf/bin/pk ./hello.elf          
bbl loader
Hello CVA6!

# verilator version
Verilator 4.225 devel rev v4.224-33-g3bd830ea

**Comment by MikeOpenHWGroup** [comment]
Hi @shaoway, thanks for your issue.  I see that this issue has not been updated in ~9 months, so I am closing it.  I am 99.9% confident the illegal instruction was generated by your toolchain.  If you are still having troubles please open a new issue.
