### ISSUE TITLE
[BUG] Incorrect exception type for LR instructions

### ISSUE THREAD

**Issue by Phantom1003** [openhwgroup/cva6#935]
### Is there an existing CVA6 bug for this?

- [X] I have searched the existing bug issues

### Bug Description

Our co-simulation framework found that the exception type of failed LR instruction is incorrect.
In the following test case, t6 points to page 0x10000, which hasn't been mapped yet.
When we use LR to access this page, cva6 throws a store page fault, while spike throws a load page fault.
```
[spike] core   0: 0x00000000000010ea (0x1b8f8f93) addi    t6, t6, 440
[cva6]  core   0: 0 0x00000000000010ea (0x1b8f8f93) x31 0x00000000000101b8
[cva6]      3002ns     2987 U 00000000000010ea 0 1b8f8f93 addi           t6, t6, 440           t6  :00000000000101b8 t6  :0000000000010000
[cva6]  Exception @    303600, PC: 00000000000010ee, Cause: Store Page Fault,
[cva6]                                  tval: 00000000000101b8
[spike] core   0: 0x00000000000010ee (0x100fb72f) lr.d    a4, (t6)
[spike] core   0: exception trap_load_page_fault, epc 0x00000000000010ee
[spike] core   0:           tval 0x00000000000101b8
```
[cva6-11.tar.gz](https://github.com/openhwgroup/cva6/files/9208447/cva6-11.tar.gz)

> @LuminaDCIX helps reproduce the problem

**Comment by MikeOpenHWGroup** [comment]
Hi @Phantom1003. Thanks for your issue. I see this issue has not been addressed for more than seven months so I am closing it. Feel free to open a new issue if you wish.
