### ISSUE TITLE
[BUG] why my program can't jump out of wfi loop

### ISSUE THREAD

**Issue by mazn123** [openhwgroup/cva6#946]
### Is there an existing CVA6 bug for this?

- [X] I have searched the existing bug issues

### Bug Description

When I run a test case with Makefile, I find that the instruction in trace_hart0.log has not jumped out of the wfi loop and entered the debug mode.The relevant signal of debug is always 0.I don't know where the problem is.Is there sth wrong with my C functions?

**Comment by MikeOpenHWGroup** [comment]
Hi @mazn123, thanks for your question.  I see that there have been no comments on this issue for more than six months so I am closing the issue.  Please create a new issue if you need to.
