### ISSUE TITLE
Data scratchpad evolution (L1W‑90 requirement)

### ISSUE THREAD

**Issue by jquevremont** [openhwgroup/cva6#970]
### Is there an existing CVA6 bug for this?

- [X] I have searched the existing bug issues

### Bug Description

After further discussion within the team, the requirement L1W‑90 "L1WTD should offer a feature to transform cache ways into a scratchpad." was a way to fulfil a need, not the only.
The consensus within the team is to transform this into a separate D cache and D scratchpad.
It's better also for complexity and max frequency.

**Comment by MikeOpenHWGroup** [comment]
Hi @jquevremont.  What is the status of this issue?   It has not moved forward for four months.

**Comment by jquevremont** [comment]
Solved in #981. Closing the issue.
