### ISSUE TITLE
[BUG] <title>illegal instruction running  dhrystone.riscv on the FPGA

### ISSUE THREAD

**Issue by StilluSmile** [openhwgroup/cva6#972]
### Is there an existing CVA6 bug for this?

- [X] I have searched the existing bug issues

### Bug Description

I have added the benchmark to the image file. After the system starts, when executing the hello.elf, it can be executed successfully. However execute dhrystone.riscv in the benchmark, and prompt:

# ./hello.elf
Hello CVA6!\n#
# ./dhrystone.riscv
[  298.077099] dhrystone.riscv[111]: unhandled signal 4 code 0x1 at 0x0000000080000040 in dhrystone.riscv[80000000+1000]
[  298.077099] dhrystone.riscv[111]: unhandled signal 4 code 0x1 at 0x0000000080000040 in dhrystone.riscv[80000000+1000]
[  298.096039] CPU: 0 PID: 111 Comm: dhrystone.riscv Not tainted 5.10.7 #5
[  298.096039] CPU: 0 PID: 111 Comm: dhrystone.riscv Not tainted 5.10.7 #5
[  298.110590] epc: 0000000080000040 ra : 0000000000000000 sp : 0000000000000000
[  298.110590] epc: 0000000080000040 ra : 0000000000000000 sp : 0000000000000000
[  298.124775]  gp : 0000000000000000 tp : 0000000000000000 t0 : 000000000001e000
[  298.124775]  gp : 0000000000000000 tp : 0000000000000000 t0 : 000000000001e000
[  298.140221]  t1 : 0000000000000000 t2 : 0000000000000000 s0 : 0000000000000000
[  298.140221]  t1 : 0000000000000000 t2 : 0000000000000000 s0 : 0000000000000000
[  298.154747]  s1 : 0000000000000000 a0 : 0000000000000000 a1 : 0000000000000000
[  298.154747]  s1 : 0000000000000000 a0 : 0000000000000000 a1 : 0000000000000000
[  298.170095]  a2 : 0000000000000000 a3 : 0000000000000000 a4 : 0000000000000000
[  298.170095]  a2 : 0000000000000000 a3 : 0000000000000000 a4 : 0000000000000000
[  298.184801]  a5 : 0000000000000000 a6 : 0000000000000000 a7 : 0000000000000000
[  298.184801]  a5 : 0000000000000000 a6 : 0000000000000000 a7 : 0000000000000000
[  298.200154]  s2 : 0000000000000000 s3 : 0000000000000000 s4 : 0000000000000000
[  298.200154]  s2 : 0000000000000000 s3 : 0000000000000000 s4 : 0000000000000000
[  298.214890]  s5 : 0000000000000000 s6 : 0000000000000000 s7 : 0000000000000000
[  298.214890]  s5 : 0000000000000000 s6 : 0000000000000000 s7 : 0000000000000000
[  298.230632]  s8 : 0000000000000000 s9 : 0000000000000000 s10: 0000000000000000
[  298.230632]  s8 : 0000000000000000 s9 : 0000000000000000 s10: 0000000000000000
[  298.245059]  s11: 0000000000000000 t3 : 0000000000000000 t4 : 0000000000000000
[  298.245059]  s11: 0000000000000000 t3 : 0000000000000000 t4 : 0000000000000000
[  298.260366]  t5 : 0000000000000000 t6 : 0000000000000000
[  298.260366]  t5 : 0000000000000000 t6 : 0000000000000000
[  298.272455] status: 0000000200004020 badaddr: 000000003002a073 cause: 0000000000000002
[  298.272455] status: 0000000200004020 badaddr: 000000003002a073 cause: 0000000000000002
Illegal instruction

Why is "Illegal Instruction" reported?

However, the simulation of work-ver/Variane_testharness can be executed normally.

StilluSmile@StilluSmile:~/cva6/tmp/riscv-tests/build/benchmarks$ ~/cva6/work-ver/Variane_testharness ./dhrystone.riscv
This emulator compiled with JTAG Remote Bitbang client. To enable, use +jtag_rbb_enable=1.
Listening on port 43531
Microseconds for one run through Dhrystone: 493
Dhrystones per Second:                      2025
mcycle = 246878
minstret = 196529
./dhrystone.riscv completed after 434888 cycles
CPU time used: 133765.71 ms
Wall clock time passed: 134149.29 ms

maybe i am missing something here. Has anyone else had this problem?  very grateful for any advice and help.

**Comment by MikeOpenHWGroup** [comment]
Hi @StilluSmile.  I see that this issue has gone stale.  I am 99.9% certain that your issue is related to the toolchain you used to compile the testprogram.   Please open a new issue if you are still having problems.
