### ISSUE TITLE
[BUG] make veri_run in the README is missing supporting Makefile and testbenches

### ISSUE THREAD

**Issue by tianrui-wei** [openhwgroup/cva6#977]
### Is there an existing CVA6 bug for this?

- [X] I have searched the existing bug issues

### Bug Description

The readme.md claims there's a core-only testbench with `make veri_run` [here](https://github.com/openhwgroup/cva6/blob/4c01614f83cd9dd91d115aa190bd4fc6a284b59e/README.md?plain=1#L140), but no Makefile or supporting testbench is available. It'd be great if someone could either update the instruction or add the supporting files

**Comment by kaamakshee** [comment]
I am also facing the same issue. Unable to run a core test due to this. Please help!!

**Comment by MikeOpenHWGroup** [comment]
Hi @ASintzoff.  According to "git blame", that comment about the core-only testbench was written by you.  Is this core-only testbench still supported?

**Comment by ASintzoff** [comment]
Hello @MikeOpenHWGroup in this case, "git blame" is not your friend. It is not able to identify that you ;-) are the one having written this. Unfortunately in CVA6 repository, all commits of a pull request are squashed in only one commit. The original commit is part of PR #667.

Whatever, PR #1050 is available.

**Comment by tianrui-wei** [comment]
Thanks for resolving this!
