### ISSUE TITLE
Bug in Make Verilate

### ISSUE THREAD

**Issue by Aleone7** [openhwgroup/cva6#978]
### Is there an existing CVA6 bug for this?

- [X] I have searched the existing bug issues

### Bug Description

Hello everyone,

We are 3 students to work on optimisation for CVA6 processor. We have been started the installation on our virtual machine (Debian version 11.5.0). We have followed the "getting started instructions":

we made the **Checkout Repo**

then we have **installed the toolchain risv-gnu-toolchain**

and we have started to **Install Verilator Simulation Flow**
-->export RISCV=/opt/riscv
-->./ci/setup.sh --> I have verifying that ventilator has been correctly installed (it is the version 4.110)

And when we enter the instruction **make verilate**  it happens this: the VM start to run instructions and at a point it crashed and after a while the VM just restart. --> That's why I was not able to catch all instruction and paste it there but I have attached a picture of the screen when the VM crashed.
<img width="810" alt="Capture d’écran 2022-10-17 à 10 22 38" src="https://user-images.githubusercontent.com/74099920/196126223-68146bc8-8e5a-4b9d-a850-0972661cadbf.png">

I hope I post my issue in the good section, I'm not very familiar with GitHub.

Thanks for your help,

Antoine

**Comment by MikeOpenHWGroup** [comment]
Hi @Aleone7, this issue has not been updated for three months so I am closing it.  Please re-open if this is still an issue for you.
