### ISSUE TITLE
[TASK] Submit CVA6 FPGA optimizations

### ISSUE THREAD

**Issue by jquevremont** [openhwgroup/cva6#987]
### Is there an existing CVA6 task for this?

- [X] I have searched the existing task issues

### Task Description

Submit pull request(s) with CVA6 FPGA optimization to master repo:
- FPGA memory
- Front end optimization
- TLB optimization
- Cache size optimization
- Scoreboard sizing
- Regfile optimization

### Description of Done

Pull request(s) submitted
CI OK with the pull request(s)
Reviews by @JeanRochCoulon OK

### Associated PRs

First PR: #983

**Comment by jquevremont** [comment]
First PR #983 submitted. More to come.

**Comment by jquevremont** [comment]
Decided to break down into several small PRs (rather than a large one, tougher to review).
Optimized BTB, scoreboard configuration have been merged.
Pending PR about fifo_v3.
Upcoming PR about optimized regfile and BHT.

**Comment by jquevremont** [comment]
1 PR pending.
3 PR upcoming.
Focus on frequency optimization in 2023 (mainly targetting FPGA).

**Comment by jquevremont** [comment]
1 merged PR to investigate ([#1130](https://github.com/openhwgroup/cva6/pull/1130)): timing analysis.

**Comment by JeanRochCoulon** [comment]
@jquevremont    What is the status of this task ?

**Comment by jquevremont** [comment]
Deferring future FPGA optimizations to a new task.
