### ISSUE TITLE
The IP XDMA implement on VCU118

### ISSUE THREAD

**Issue by Jett-tu** [openhwgroup/cva6#991]
Hello
      I want to implement the whole design on the development board of VCU118,
But I'm in the process of polling the files into the Vivado, I found the the XIlinx IP XDMA was missing. I can not find the TCL script for this IP. I want to konw where it is.

**Comment by MikeOpenHWGroup** [comment]
Hi @Jett-tu, the only FPGA Board we support is Genesys2.  We are not Xilinx experts and cannot offer Xilinx support.
