### ISSUE TITLE
CV32A6 Design Document includes floating point CSRs

### ISSUE THREAD

**Issue by MikeOpenHWGroup** [openhwgroup/cva6#997]
### Is there an existing CVA6 bug for this?

- [X] I have searched the existing bug issues

### Bug Description

The [register description](https://docs.openhwgroup.org/projects/cva6-user-manual/03_cv32a6_design/source/cv32a6_csr.html#register-descriptions) section of the CV32A6 Design Document lists a set of RV32F floating point CSRs.   As far as I am aware, the CV32A6 does not support floating point, so these registers should not exist and therefore not be part of the Design Document.

**Comment by JeanRochCoulon** [comment]
The FPU and trigger CSrs have been removed from Design Document, please refer to :
https://docs.openhwgroup.org/projects/cva6-user-manual/04_cv32a6_design/source/csr_list.html
